// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Address is an object representing the database table.
type Address struct {
	ID            string           `db:"id,pk" `
	UserID        string           `db:"user_id" `
	AddressesType string           `db:"addresses_type" `
	Line1         string           `db:"line1" `
	Line2         null.Val[string] `db:"line2" `
	Landmark      null.Val[string] `db:"landmark" `
	City          string           `db:"city" `
	Pincode       string           `db:"pincode" `
	District      string           `db:"district" `
	State         string           `db:"state" `
	Country       string           `db:"country" `
	IsDefault     bool             `db:"is_default" `
	CreatedAt     time.Time        `db:"created_at" `
	UpdatedAt     time.Time        `db:"updated_at" `

	R addressR `db:"-" `
}

// AddressSlice is an alias for a slice of pointers to Address.
// This should almost always be used instead of []*Address.
type AddressSlice []*Address

// Addresses contains methods to work with the addresses table
var Addresses = psql.NewTablex[*Address, AddressSlice, *AddressSetter]("", "addresses", buildAddressColumns("addresses"))

// AddressesQuery is a query on the addresses table
type AddressesQuery = *psql.ViewQuery[*Address, AddressSlice]

// addressR is where relationships are stored.
type addressR struct {
	User *User // addresses.addresses_user_id_fkey
}

func buildAddressColumns(alias string) addressColumns {
	return addressColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "user_id", "addresses_type", "line1", "line2", "landmark", "city", "pincode", "district", "state", "country", "is_default", "created_at", "updated_at",
		).WithParent("addresses"),
		tableAlias:    alias,
		ID:            psql.Quote(alias, "id"),
		UserID:        psql.Quote(alias, "user_id"),
		AddressesType: psql.Quote(alias, "addresses_type"),
		Line1:         psql.Quote(alias, "line1"),
		Line2:         psql.Quote(alias, "line2"),
		Landmark:      psql.Quote(alias, "landmark"),
		City:          psql.Quote(alias, "city"),
		Pincode:       psql.Quote(alias, "pincode"),
		District:      psql.Quote(alias, "district"),
		State:         psql.Quote(alias, "state"),
		Country:       psql.Quote(alias, "country"),
		IsDefault:     psql.Quote(alias, "is_default"),
		CreatedAt:     psql.Quote(alias, "created_at"),
		UpdatedAt:     psql.Quote(alias, "updated_at"),
	}
}

type addressColumns struct {
	expr.ColumnsExpr
	tableAlias    string
	ID            psql.Expression
	UserID        psql.Expression
	AddressesType psql.Expression
	Line1         psql.Expression
	Line2         psql.Expression
	Landmark      psql.Expression
	City          psql.Expression
	Pincode       psql.Expression
	District      psql.Expression
	State         psql.Expression
	Country       psql.Expression
	IsDefault     psql.Expression
	CreatedAt     psql.Expression
	UpdatedAt     psql.Expression
}

func (c addressColumns) Alias() string {
	return c.tableAlias
}

func (addressColumns) AliasedAs(alias string) addressColumns {
	return buildAddressColumns(alias)
}

// AddressSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type AddressSetter struct {
	ID            omit.Val[string]     `db:"id,pk" `
	UserID        omit.Val[string]     `db:"user_id" `
	AddressesType omit.Val[string]     `db:"addresses_type" `
	Line1         omit.Val[string]     `db:"line1" `
	Line2         omitnull.Val[string] `db:"line2" `
	Landmark      omitnull.Val[string] `db:"landmark" `
	City          omit.Val[string]     `db:"city" `
	Pincode       omit.Val[string]     `db:"pincode" `
	District      omit.Val[string]     `db:"district" `
	State         omit.Val[string]     `db:"state" `
	Country       omit.Val[string]     `db:"country" `
	IsDefault     omit.Val[bool]       `db:"is_default" `
	CreatedAt     omit.Val[time.Time]  `db:"created_at" `
	UpdatedAt     omit.Val[time.Time]  `db:"updated_at" `
}

func (s AddressSetter) SetColumns() []string {
	vals := make([]string, 0, 14)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.AddressesType.IsValue() {
		vals = append(vals, "addresses_type")
	}
	if s.Line1.IsValue() {
		vals = append(vals, "line1")
	}
	if !s.Line2.IsUnset() {
		vals = append(vals, "line2")
	}
	if !s.Landmark.IsUnset() {
		vals = append(vals, "landmark")
	}
	if s.City.IsValue() {
		vals = append(vals, "city")
	}
	if s.Pincode.IsValue() {
		vals = append(vals, "pincode")
	}
	if s.District.IsValue() {
		vals = append(vals, "district")
	}
	if s.State.IsValue() {
		vals = append(vals, "state")
	}
	if s.Country.IsValue() {
		vals = append(vals, "country")
	}
	if s.IsDefault.IsValue() {
		vals = append(vals, "is_default")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s AddressSetter) Overwrite(t *Address) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.AddressesType.IsValue() {
		t.AddressesType = s.AddressesType.MustGet()
	}
	if s.Line1.IsValue() {
		t.Line1 = s.Line1.MustGet()
	}
	if !s.Line2.IsUnset() {
		t.Line2 = s.Line2.MustGetNull()
	}
	if !s.Landmark.IsUnset() {
		t.Landmark = s.Landmark.MustGetNull()
	}
	if s.City.IsValue() {
		t.City = s.City.MustGet()
	}
	if s.Pincode.IsValue() {
		t.Pincode = s.Pincode.MustGet()
	}
	if s.District.IsValue() {
		t.District = s.District.MustGet()
	}
	if s.State.IsValue() {
		t.State = s.State.MustGet()
	}
	if s.Country.IsValue() {
		t.Country = s.Country.MustGet()
	}
	if s.IsDefault.IsValue() {
		t.IsDefault = s.IsDefault.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *AddressSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Addresses.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 14)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.UserID.IsValue() {
			vals[1] = psql.Arg(s.UserID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.AddressesType.IsValue() {
			vals[2] = psql.Arg(s.AddressesType.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Line1.IsValue() {
			vals[3] = psql.Arg(s.Line1.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if !s.Line2.IsUnset() {
			vals[4] = psql.Arg(s.Line2.MustGetNull())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if !s.Landmark.IsUnset() {
			vals[5] = psql.Arg(s.Landmark.MustGetNull())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.City.IsValue() {
			vals[6] = psql.Arg(s.City.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.Pincode.IsValue() {
			vals[7] = psql.Arg(s.Pincode.MustGet())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if s.District.IsValue() {
			vals[8] = psql.Arg(s.District.MustGet())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		if s.State.IsValue() {
			vals[9] = psql.Arg(s.State.MustGet())
		} else {
			vals[9] = psql.Raw("DEFAULT")
		}

		if s.Country.IsValue() {
			vals[10] = psql.Arg(s.Country.MustGet())
		} else {
			vals[10] = psql.Raw("DEFAULT")
		}

		if s.IsDefault.IsValue() {
			vals[11] = psql.Arg(s.IsDefault.MustGet())
		} else {
			vals[11] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[12] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[12] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[13] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[13] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s AddressSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s AddressSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 14)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if s.AddressesType.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "addresses_type")...),
			psql.Arg(s.AddressesType),
		}})
	}

	if s.Line1.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "line1")...),
			psql.Arg(s.Line1),
		}})
	}

	if !s.Line2.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "line2")...),
			psql.Arg(s.Line2),
		}})
	}

	if !s.Landmark.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "landmark")...),
			psql.Arg(s.Landmark),
		}})
	}

	if s.City.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "city")...),
			psql.Arg(s.City),
		}})
	}

	if s.Pincode.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "pincode")...),
			psql.Arg(s.Pincode),
		}})
	}

	if s.District.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "district")...),
			psql.Arg(s.District),
		}})
	}

	if s.State.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "state")...),
			psql.Arg(s.State),
		}})
	}

	if s.Country.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "country")...),
			psql.Arg(s.Country),
		}})
	}

	if s.IsDefault.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "is_default")...),
			psql.Arg(s.IsDefault),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindAddress retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindAddress(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*Address, error) {
	if len(cols) == 0 {
		return Addresses.Query(
			sm.Where(Addresses.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Addresses.Query(
		sm.Where(Addresses.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Addresses.Columns.Only(cols...)),
	).One(ctx, exec)
}

// AddressExists checks the presence of a single record by primary key
func AddressExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return Addresses.Query(
		sm.Where(Addresses.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Address is retrieved from the database
func (o *Address) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Addresses.AfterSelectHooks.RunHooks(ctx, exec, AddressSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Addresses.AfterInsertHooks.RunHooks(ctx, exec, AddressSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Addresses.AfterUpdateHooks.RunHooks(ctx, exec, AddressSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Addresses.AfterDeleteHooks.RunHooks(ctx, exec, AddressSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Address
func (o *Address) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Address) pkEQ() dialect.Expression {
	return psql.Quote("addresses", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Address
func (o *Address) Update(ctx context.Context, exec bob.Executor, s *AddressSetter) error {
	v, err := Addresses.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Address record with an executor
func (o *Address) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Addresses.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Address using the executor
func (o *Address) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Addresses.Query(
		sm.Where(Addresses.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after AddressSlice is retrieved from the database
func (o AddressSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Addresses.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Addresses.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Addresses.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Addresses.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o AddressSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("addresses", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o AddressSlice) copyMatchingRows(from ...*Address) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o AddressSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Addresses.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Address:
				o.copyMatchingRows(retrieved)
			case []*Address:
				o.copyMatchingRows(retrieved...)
			case AddressSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Address or a slice of Address
				// then run the AfterUpdateHooks on the slice
				_, err = Addresses.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o AddressSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Addresses.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Address:
				o.copyMatchingRows(retrieved)
			case []*Address:
				o.copyMatchingRows(retrieved...)
			case AddressSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Address or a slice of Address
				// then run the AfterDeleteHooks on the slice
				_, err = Addresses.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o AddressSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals AddressSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Addresses.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o AddressSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Addresses.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o AddressSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Addresses.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// User starts a query for related objects on users
func (o *Address) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os AddressSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkUserID = append(pkUserID, o.UserID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserID), "character varying[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachAddressUser0(ctx context.Context, exec bob.Executor, count int, address0 *Address, user1 *User) (*Address, error) {
	setter := &AddressSetter{
		UserID: omit.From(user1.ID),
	}

	err := address0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachAddressUser0: %w", err)
	}

	return address0, nil
}

func (address0 *Address) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachAddressUser0(ctx, exec, 1, address0, user1)
	if err != nil {
		return err
	}

	address0.R.User = user1

	user1.R.Addresses = append(user1.R.Addresses, address0)

	return nil
}

func (address0 *Address) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachAddressUser0(ctx, exec, 1, address0, user1)
	if err != nil {
		return err
	}

	address0.R.User = user1

	user1.R.Addresses = append(user1.R.Addresses, address0)

	return nil
}

type addressWhere[Q psql.Filterable] struct {
	ID            psql.WhereMod[Q, string]
	UserID        psql.WhereMod[Q, string]
	AddressesType psql.WhereMod[Q, string]
	Line1         psql.WhereMod[Q, string]
	Line2         psql.WhereNullMod[Q, string]
	Landmark      psql.WhereNullMod[Q, string]
	City          psql.WhereMod[Q, string]
	Pincode       psql.WhereMod[Q, string]
	District      psql.WhereMod[Q, string]
	State         psql.WhereMod[Q, string]
	Country       psql.WhereMod[Q, string]
	IsDefault     psql.WhereMod[Q, bool]
	CreatedAt     psql.WhereMod[Q, time.Time]
	UpdatedAt     psql.WhereMod[Q, time.Time]
}

func (addressWhere[Q]) AliasedAs(alias string) addressWhere[Q] {
	return buildAddressWhere[Q](buildAddressColumns(alias))
}

func buildAddressWhere[Q psql.Filterable](cols addressColumns) addressWhere[Q] {
	return addressWhere[Q]{
		ID:            psql.Where[Q, string](cols.ID),
		UserID:        psql.Where[Q, string](cols.UserID),
		AddressesType: psql.Where[Q, string](cols.AddressesType),
		Line1:         psql.Where[Q, string](cols.Line1),
		Line2:         psql.WhereNull[Q, string](cols.Line2),
		Landmark:      psql.WhereNull[Q, string](cols.Landmark),
		City:          psql.Where[Q, string](cols.City),
		Pincode:       psql.Where[Q, string](cols.Pincode),
		District:      psql.Where[Q, string](cols.District),
		State:         psql.Where[Q, string](cols.State),
		Country:       psql.Where[Q, string](cols.Country),
		IsDefault:     psql.Where[Q, bool](cols.IsDefault),
		CreatedAt:     psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:     psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *Address) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("address cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.Addresses = AddressSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("address has no relationship %q", name)
	}
}

type addressPreloader struct {
	User func(...psql.PreloadOption) psql.Preloader
}

func buildAddressPreloader() addressPreloader {
	return addressPreloader{
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "User",
				Sides: []psql.PreloadSide{
					{
						From:        Addresses,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type addressThenLoader[Q orm.Loadable] struct {
	User func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildAddressThenLoader[Q orm.Loadable]() addressThenLoader[Q] {
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return addressThenLoader[Q]{
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadUser loads the address's User into the .R struct
func (o *Address) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Addresses = AddressSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the address's User into the .R struct
func (os AddressSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			rel.R.Addresses = append(rel.R.Addresses, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

type addressJoins[Q dialect.Joinable] struct {
	typ  string
	User modAs[Q, userColumns]
}

func (j addressJoins[Q]) aliasedAs(alias string) addressJoins[Q] {
	return buildAddressJoins[Q](buildAddressColumns(alias), j.typ)
}

func buildAddressJoins[Q dialect.Joinable](cols addressColumns, typ string) addressJoins[Q] {
	return addressJoins[Q]{
		typ: typ,
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
