// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
)

var (
	SelectWhere     = Where[*dialect.SelectQuery]()
	UpdateWhere     = Where[*dialect.UpdateQuery]()
	DeleteWhere     = Where[*dialect.DeleteQuery]()
	OnConflictWhere = Where[*clause.ConflictClause]() // Used in ON CONFLICT DO UPDATE
)

func Where[Q psql.Filterable]() struct {
	Addresses addressWhere[Q]
	Books     bookWhere[Q]
	CartItems cartItemWhere[Q]
	Carts     cartWhere[Q]
	Orders    orderWhere[Q]
	Users     userWhere[Q]
} {
	return struct {
		Addresses addressWhere[Q]
		Books     bookWhere[Q]
		CartItems cartItemWhere[Q]
		Carts     cartWhere[Q]
		Orders    orderWhere[Q]
		Users     userWhere[Q]
	}{
		Addresses: buildAddressWhere[Q](Addresses.Columns),
		Books:     buildBookWhere[Q](Books.Columns),
		CartItems: buildCartItemWhere[Q](CartItems.Columns),
		Carts:     buildCartWhere[Q](Carts.Columns),
		Orders:    buildOrderWhere[Q](Orders.Columns),
		Users:     buildUserWhere[Q](Users.Columns),
	}
}
