// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Book is an object representing the database table.
type Book struct {
	ID          string           `db:"id,pk" `
	Isbn        string           `db:"isbn" `
	Title       string           `db:"title" `
	Author      string           `db:"author" `
	Description null.Val[string] `db:"description" `
	Price       decimal.Decimal  `db:"price" `
	Stock       int32            `db:"stock" `
	Reserved    int32            `db:"reserved" `
	IsActive    bool             `db:"is_active" `
	CreatedAt   time.Time        `db:"created_at" `
	UpdatedAt   time.Time        `db:"updated_at" `

	R bookR `db:"-" `
}

// BookSlice is an alias for a slice of pointers to Book.
// This should almost always be used instead of []*Book.
type BookSlice []*Book

// Books contains methods to work with the books table
var Books = psql.NewTablex[*Book, BookSlice, *BookSetter]("", "books", buildBookColumns("books"))

// BooksQuery is a query on the books table
type BooksQuery = *psql.ViewQuery[*Book, BookSlice]

// bookR is where relationships are stored.
type bookR struct {
	CartItems CartItemSlice // cart_items.cart_items_book_id_fkey
}

func buildBookColumns(alias string) bookColumns {
	return bookColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "isbn", "title", "author", "description", "price", "stock", "reserved", "is_active", "created_at", "updated_at",
		).WithParent("books"),
		tableAlias:  alias,
		ID:          psql.Quote(alias, "id"),
		Isbn:        psql.Quote(alias, "isbn"),
		Title:       psql.Quote(alias, "title"),
		Author:      psql.Quote(alias, "author"),
		Description: psql.Quote(alias, "description"),
		Price:       psql.Quote(alias, "price"),
		Stock:       psql.Quote(alias, "stock"),
		Reserved:    psql.Quote(alias, "reserved"),
		IsActive:    psql.Quote(alias, "is_active"),
		CreatedAt:   psql.Quote(alias, "created_at"),
		UpdatedAt:   psql.Quote(alias, "updated_at"),
	}
}

type bookColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	ID          psql.Expression
	Isbn        psql.Expression
	Title       psql.Expression
	Author      psql.Expression
	Description psql.Expression
	Price       psql.Expression
	Stock       psql.Expression
	Reserved    psql.Expression
	IsActive    psql.Expression
	CreatedAt   psql.Expression
	UpdatedAt   psql.Expression
}

func (c bookColumns) Alias() string {
	return c.tableAlias
}

func (bookColumns) AliasedAs(alias string) bookColumns {
	return buildBookColumns(alias)
}

// BookSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type BookSetter struct {
	ID          omit.Val[string]          `db:"id,pk" `
	Isbn        omit.Val[string]          `db:"isbn" `
	Title       omit.Val[string]          `db:"title" `
	Author      omit.Val[string]          `db:"author" `
	Description omitnull.Val[string]      `db:"description" `
	Price       omit.Val[decimal.Decimal] `db:"price" `
	Stock       omit.Val[int32]           `db:"stock" `
	Reserved    omit.Val[int32]           `db:"reserved" `
	IsActive    omit.Val[bool]            `db:"is_active" `
	CreatedAt   omit.Val[time.Time]       `db:"created_at" `
	UpdatedAt   omit.Val[time.Time]       `db:"updated_at" `
}

func (s BookSetter) SetColumns() []string {
	vals := make([]string, 0, 11)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Isbn.IsValue() {
		vals = append(vals, "isbn")
	}
	if s.Title.IsValue() {
		vals = append(vals, "title")
	}
	if s.Author.IsValue() {
		vals = append(vals, "author")
	}
	if !s.Description.IsUnset() {
		vals = append(vals, "description")
	}
	if s.Price.IsValue() {
		vals = append(vals, "price")
	}
	if s.Stock.IsValue() {
		vals = append(vals, "stock")
	}
	if s.Reserved.IsValue() {
		vals = append(vals, "reserved")
	}
	if s.IsActive.IsValue() {
		vals = append(vals, "is_active")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s BookSetter) Overwrite(t *Book) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Isbn.IsValue() {
		t.Isbn = s.Isbn.MustGet()
	}
	if s.Title.IsValue() {
		t.Title = s.Title.MustGet()
	}
	if s.Author.IsValue() {
		t.Author = s.Author.MustGet()
	}
	if !s.Description.IsUnset() {
		t.Description = s.Description.MustGetNull()
	}
	if s.Price.IsValue() {
		t.Price = s.Price.MustGet()
	}
	if s.Stock.IsValue() {
		t.Stock = s.Stock.MustGet()
	}
	if s.Reserved.IsValue() {
		t.Reserved = s.Reserved.MustGet()
	}
	if s.IsActive.IsValue() {
		t.IsActive = s.IsActive.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *BookSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Books.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 11)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Isbn.IsValue() {
			vals[1] = psql.Arg(s.Isbn.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Title.IsValue() {
			vals[2] = psql.Arg(s.Title.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Author.IsValue() {
			vals[3] = psql.Arg(s.Author.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if !s.Description.IsUnset() {
			vals[4] = psql.Arg(s.Description.MustGetNull())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.Price.IsValue() {
			vals[5] = psql.Arg(s.Price.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.Stock.IsValue() {
			vals[6] = psql.Arg(s.Stock.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.Reserved.IsValue() {
			vals[7] = psql.Arg(s.Reserved.MustGet())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if s.IsActive.IsValue() {
			vals[8] = psql.Arg(s.IsActive.MustGet())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[9] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[9] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[10] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[10] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s BookSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s BookSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 11)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Isbn.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "isbn")...),
			psql.Arg(s.Isbn),
		}})
	}

	if s.Title.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "title")...),
			psql.Arg(s.Title),
		}})
	}

	if s.Author.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "author")...),
			psql.Arg(s.Author),
		}})
	}

	if !s.Description.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "description")...),
			psql.Arg(s.Description),
		}})
	}

	if s.Price.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "price")...),
			psql.Arg(s.Price),
		}})
	}

	if s.Stock.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "stock")...),
			psql.Arg(s.Stock),
		}})
	}

	if s.Reserved.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "reserved")...),
			psql.Arg(s.Reserved),
		}})
	}

	if s.IsActive.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "is_active")...),
			psql.Arg(s.IsActive),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindBook retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindBook(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*Book, error) {
	if len(cols) == 0 {
		return Books.Query(
			sm.Where(Books.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Books.Query(
		sm.Where(Books.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Books.Columns.Only(cols...)),
	).One(ctx, exec)
}

// BookExists checks the presence of a single record by primary key
func BookExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return Books.Query(
		sm.Where(Books.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Book is retrieved from the database
func (o *Book) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Books.AfterSelectHooks.RunHooks(ctx, exec, BookSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Books.AfterInsertHooks.RunHooks(ctx, exec, BookSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Books.AfterUpdateHooks.RunHooks(ctx, exec, BookSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Books.AfterDeleteHooks.RunHooks(ctx, exec, BookSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Book
func (o *Book) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Book) pkEQ() dialect.Expression {
	return psql.Quote("books", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Book
func (o *Book) Update(ctx context.Context, exec bob.Executor, s *BookSetter) error {
	v, err := Books.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Book record with an executor
func (o *Book) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Books.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Book using the executor
func (o *Book) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Books.Query(
		sm.Where(Books.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after BookSlice is retrieved from the database
func (o BookSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Books.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Books.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Books.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Books.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o BookSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("books", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o BookSlice) copyMatchingRows(from ...*Book) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o BookSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Books.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Book:
				o.copyMatchingRows(retrieved)
			case []*Book:
				o.copyMatchingRows(retrieved...)
			case BookSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Book or a slice of Book
				// then run the AfterUpdateHooks on the slice
				_, err = Books.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o BookSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Books.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Book:
				o.copyMatchingRows(retrieved)
			case []*Book:
				o.copyMatchingRows(retrieved...)
			case BookSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Book or a slice of Book
				// then run the AfterDeleteHooks on the slice
				_, err = Books.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o BookSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals BookSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Books.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o BookSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Books.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o BookSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Books.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// CartItems starts a query for related objects on cart_items
func (o *Book) CartItems(mods ...bob.Mod[*dialect.SelectQuery]) CartItemsQuery {
	return CartItems.Query(append(mods,
		sm.Where(CartItems.Columns.BookID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os BookSlice) CartItems(mods ...bob.Mod[*dialect.SelectQuery]) CartItemsQuery {
	pkID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "character varying[]")),
	))

	return CartItems.Query(append(mods,
		sm.Where(psql.Group(CartItems.Columns.BookID).OP("IN", PKArgExpr)),
	)...)
}

func insertBookCartItems0(ctx context.Context, exec bob.Executor, cartItems1 []*CartItemSetter, book0 *Book) (CartItemSlice, error) {
	for i := range cartItems1 {
		cartItems1[i].BookID = omit.From(book0.ID)
	}

	ret, err := CartItems.Insert(bob.ToMods(cartItems1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertBookCartItems0: %w", err)
	}

	return ret, nil
}

func attachBookCartItems0(ctx context.Context, exec bob.Executor, count int, cartItems1 CartItemSlice, book0 *Book) (CartItemSlice, error) {
	setter := &CartItemSetter{
		BookID: omit.From(book0.ID),
	}

	err := cartItems1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachBookCartItems0: %w", err)
	}

	return cartItems1, nil
}

func (book0 *Book) InsertCartItems(ctx context.Context, exec bob.Executor, related ...*CartItemSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	cartItems1, err := insertBookCartItems0(ctx, exec, related, book0)
	if err != nil {
		return err
	}

	book0.R.CartItems = append(book0.R.CartItems, cartItems1...)

	for _, rel := range cartItems1 {
		rel.R.Book = book0
	}
	return nil
}

func (book0 *Book) AttachCartItems(ctx context.Context, exec bob.Executor, related ...*CartItem) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	cartItems1 := CartItemSlice(related)

	_, err = attachBookCartItems0(ctx, exec, len(related), cartItems1, book0)
	if err != nil {
		return err
	}

	book0.R.CartItems = append(book0.R.CartItems, cartItems1...)

	for _, rel := range related {
		rel.R.Book = book0
	}

	return nil
}

type bookWhere[Q psql.Filterable] struct {
	ID          psql.WhereMod[Q, string]
	Isbn        psql.WhereMod[Q, string]
	Title       psql.WhereMod[Q, string]
	Author      psql.WhereMod[Q, string]
	Description psql.WhereNullMod[Q, string]
	Price       psql.WhereMod[Q, decimal.Decimal]
	Stock       psql.WhereMod[Q, int32]
	Reserved    psql.WhereMod[Q, int32]
	IsActive    psql.WhereMod[Q, bool]
	CreatedAt   psql.WhereMod[Q, time.Time]
	UpdatedAt   psql.WhereMod[Q, time.Time]
}

func (bookWhere[Q]) AliasedAs(alias string) bookWhere[Q] {
	return buildBookWhere[Q](buildBookColumns(alias))
}

func buildBookWhere[Q psql.Filterable](cols bookColumns) bookWhere[Q] {
	return bookWhere[Q]{
		ID:          psql.Where[Q, string](cols.ID),
		Isbn:        psql.Where[Q, string](cols.Isbn),
		Title:       psql.Where[Q, string](cols.Title),
		Author:      psql.Where[Q, string](cols.Author),
		Description: psql.WhereNull[Q, string](cols.Description),
		Price:       psql.Where[Q, decimal.Decimal](cols.Price),
		Stock:       psql.Where[Q, int32](cols.Stock),
		Reserved:    psql.Where[Q, int32](cols.Reserved),
		IsActive:    psql.Where[Q, bool](cols.IsActive),
		CreatedAt:   psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:   psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *Book) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "CartItems":
		rels, ok := retrieved.(CartItemSlice)
		if !ok {
			return fmt.Errorf("book cannot load %T as %q", retrieved, name)
		}

		o.R.CartItems = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Book = o
			}
		}
		return nil
	default:
		return fmt.Errorf("book has no relationship %q", name)
	}
}

type bookPreloader struct{}

func buildBookPreloader() bookPreloader {
	return bookPreloader{}
}

type bookThenLoader[Q orm.Loadable] struct {
	CartItems func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildBookThenLoader[Q orm.Loadable]() bookThenLoader[Q] {
	type CartItemsLoadInterface interface {
		LoadCartItems(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return bookThenLoader[Q]{
		CartItems: thenLoadBuilder[Q](
			"CartItems",
			func(ctx context.Context, exec bob.Executor, retrieved CartItemsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCartItems(ctx, exec, mods...)
			},
		),
	}
}

// LoadCartItems loads the book's CartItems into the .R struct
func (o *Book) LoadCartItems(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.CartItems = nil

	related, err := o.CartItems(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Book = o
	}

	o.R.CartItems = related
	return nil
}

// LoadCartItems loads the book's CartItems into the .R struct
func (os BookSlice) LoadCartItems(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	cartItems, err := os.CartItems(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.CartItems = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range cartItems {

			if !(o.ID == rel.BookID) {
				continue
			}

			rel.R.Book = o

			o.R.CartItems = append(o.R.CartItems, rel)
		}
	}

	return nil
}

type bookJoins[Q dialect.Joinable] struct {
	typ       string
	CartItems modAs[Q, cartItemColumns]
}

func (j bookJoins[Q]) aliasedAs(alias string) bookJoins[Q] {
	return buildBookJoins[Q](buildBookColumns(alias), j.typ)
}

func buildBookJoins[Q dialect.Joinable](cols bookColumns, typ string) bookJoins[Q] {
	return bookJoins[Q]{
		typ: typ,
		CartItems: modAs[Q, cartItemColumns]{
			c: CartItems.Columns,
			f: func(to cartItemColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, CartItems.Name().As(to.Alias())).On(
						to.BookID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
