// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// CartItem is an object representing the database table.
type CartItem struct {
	ID        string    `db:"id,pk" `
	CartID    string    `db:"cart_id" `
	BookID    string    `db:"book_id" `
	Quantity  int32     `db:"quantity" `
	CreatedAt time.Time `db:"created_at" `
	UpdatedAt time.Time `db:"updated_at" `

	R cartItemR `db:"-" `
}

// CartItemSlice is an alias for a slice of pointers to CartItem.
// This should almost always be used instead of []*CartItem.
type CartItemSlice []*CartItem

// CartItems contains methods to work with the cart_items table
var CartItems = psql.NewTablex[*CartItem, CartItemSlice, *CartItemSetter]("", "cart_items", buildCartItemColumns("cart_items"))

// CartItemsQuery is a query on the cart_items table
type CartItemsQuery = *psql.ViewQuery[*CartItem, CartItemSlice]

// cartItemR is where relationships are stored.
type cartItemR struct {
	Book *Book // cart_items.cart_items_book_id_fkey
	Cart *Cart // cart_items.cart_items_cart_id_fkey
}

func buildCartItemColumns(alias string) cartItemColumns {
	return cartItemColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "cart_id", "book_id", "quantity", "created_at", "updated_at",
		).WithParent("cart_items"),
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		CartID:     psql.Quote(alias, "cart_id"),
		BookID:     psql.Quote(alias, "book_id"),
		Quantity:   psql.Quote(alias, "quantity"),
		CreatedAt:  psql.Quote(alias, "created_at"),
		UpdatedAt:  psql.Quote(alias, "updated_at"),
	}
}

type cartItemColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         psql.Expression
	CartID     psql.Expression
	BookID     psql.Expression
	Quantity   psql.Expression
	CreatedAt  psql.Expression
	UpdatedAt  psql.Expression
}

func (c cartItemColumns) Alias() string {
	return c.tableAlias
}

func (cartItemColumns) AliasedAs(alias string) cartItemColumns {
	return buildCartItemColumns(alias)
}

// CartItemSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type CartItemSetter struct {
	ID        omit.Val[string]    `db:"id,pk" `
	CartID    omit.Val[string]    `db:"cart_id" `
	BookID    omit.Val[string]    `db:"book_id" `
	Quantity  omit.Val[int32]     `db:"quantity" `
	CreatedAt omit.Val[time.Time] `db:"created_at" `
	UpdatedAt omit.Val[time.Time] `db:"updated_at" `
}

func (s CartItemSetter) SetColumns() []string {
	vals := make([]string, 0, 6)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.CartID.IsValue() {
		vals = append(vals, "cart_id")
	}
	if s.BookID.IsValue() {
		vals = append(vals, "book_id")
	}
	if s.Quantity.IsValue() {
		vals = append(vals, "quantity")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s CartItemSetter) Overwrite(t *CartItem) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.CartID.IsValue() {
		t.CartID = s.CartID.MustGet()
	}
	if s.BookID.IsValue() {
		t.BookID = s.BookID.MustGet()
	}
	if s.Quantity.IsValue() {
		t.Quantity = s.Quantity.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *CartItemSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return CartItems.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 6)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.CartID.IsValue() {
			vals[1] = psql.Arg(s.CartID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.BookID.IsValue() {
			vals[2] = psql.Arg(s.BookID.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Quantity.IsValue() {
			vals[3] = psql.Arg(s.Quantity.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[4] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[5] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s CartItemSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s CartItemSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 6)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.CartID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "cart_id")...),
			psql.Arg(s.CartID),
		}})
	}

	if s.BookID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "book_id")...),
			psql.Arg(s.BookID),
		}})
	}

	if s.Quantity.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "quantity")...),
			psql.Arg(s.Quantity),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindCartItem retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindCartItem(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*CartItem, error) {
	if len(cols) == 0 {
		return CartItems.Query(
			sm.Where(CartItems.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return CartItems.Query(
		sm.Where(CartItems.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(CartItems.Columns.Only(cols...)),
	).One(ctx, exec)
}

// CartItemExists checks the presence of a single record by primary key
func CartItemExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return CartItems.Query(
		sm.Where(CartItems.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after CartItem is retrieved from the database
func (o *CartItem) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = CartItems.AfterSelectHooks.RunHooks(ctx, exec, CartItemSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = CartItems.AfterInsertHooks.RunHooks(ctx, exec, CartItemSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = CartItems.AfterUpdateHooks.RunHooks(ctx, exec, CartItemSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = CartItems.AfterDeleteHooks.RunHooks(ctx, exec, CartItemSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the CartItem
func (o *CartItem) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *CartItem) pkEQ() dialect.Expression {
	return psql.Quote("cart_items", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the CartItem
func (o *CartItem) Update(ctx context.Context, exec bob.Executor, s *CartItemSetter) error {
	v, err := CartItems.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single CartItem record with an executor
func (o *CartItem) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := CartItems.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the CartItem using the executor
func (o *CartItem) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := CartItems.Query(
		sm.Where(CartItems.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after CartItemSlice is retrieved from the database
func (o CartItemSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = CartItems.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = CartItems.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = CartItems.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = CartItems.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o CartItemSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("cart_items", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o CartItemSlice) copyMatchingRows(from ...*CartItem) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o CartItemSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return CartItems.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *CartItem:
				o.copyMatchingRows(retrieved)
			case []*CartItem:
				o.copyMatchingRows(retrieved...)
			case CartItemSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a CartItem or a slice of CartItem
				// then run the AfterUpdateHooks on the slice
				_, err = CartItems.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o CartItemSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return CartItems.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *CartItem:
				o.copyMatchingRows(retrieved)
			case []*CartItem:
				o.copyMatchingRows(retrieved...)
			case CartItemSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a CartItem or a slice of CartItem
				// then run the AfterDeleteHooks on the slice
				_, err = CartItems.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o CartItemSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals CartItemSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := CartItems.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o CartItemSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := CartItems.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o CartItemSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := CartItems.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Book starts a query for related objects on books
func (o *CartItem) Book(mods ...bob.Mod[*dialect.SelectQuery]) BooksQuery {
	return Books.Query(append(mods,
		sm.Where(Books.Columns.ID.EQ(psql.Arg(o.BookID))),
	)...)
}

func (os CartItemSlice) Book(mods ...bob.Mod[*dialect.SelectQuery]) BooksQuery {
	pkBookID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkBookID = append(pkBookID, o.BookID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkBookID), "character varying[]")),
	))

	return Books.Query(append(mods,
		sm.Where(psql.Group(Books.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// Cart starts a query for related objects on carts
func (o *CartItem) Cart(mods ...bob.Mod[*dialect.SelectQuery]) CartsQuery {
	return Carts.Query(append(mods,
		sm.Where(Carts.Columns.ID.EQ(psql.Arg(o.CartID))),
	)...)
}

func (os CartItemSlice) Cart(mods ...bob.Mod[*dialect.SelectQuery]) CartsQuery {
	pkCartID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkCartID = append(pkCartID, o.CartID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkCartID), "character varying[]")),
	))

	return Carts.Query(append(mods,
		sm.Where(psql.Group(Carts.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachCartItemBook0(ctx context.Context, exec bob.Executor, count int, cartItem0 *CartItem, book1 *Book) (*CartItem, error) {
	setter := &CartItemSetter{
		BookID: omit.From(book1.ID),
	}

	err := cartItem0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachCartItemBook0: %w", err)
	}

	return cartItem0, nil
}

func (cartItem0 *CartItem) InsertBook(ctx context.Context, exec bob.Executor, related *BookSetter) error {
	var err error

	book1, err := Books.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachCartItemBook0(ctx, exec, 1, cartItem0, book1)
	if err != nil {
		return err
	}

	cartItem0.R.Book = book1

	book1.R.CartItems = append(book1.R.CartItems, cartItem0)

	return nil
}

func (cartItem0 *CartItem) AttachBook(ctx context.Context, exec bob.Executor, book1 *Book) error {
	var err error

	_, err = attachCartItemBook0(ctx, exec, 1, cartItem0, book1)
	if err != nil {
		return err
	}

	cartItem0.R.Book = book1

	book1.R.CartItems = append(book1.R.CartItems, cartItem0)

	return nil
}

func attachCartItemCart0(ctx context.Context, exec bob.Executor, count int, cartItem0 *CartItem, cart1 *Cart) (*CartItem, error) {
	setter := &CartItemSetter{
		CartID: omit.From(cart1.ID),
	}

	err := cartItem0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachCartItemCart0: %w", err)
	}

	return cartItem0, nil
}

func (cartItem0 *CartItem) InsertCart(ctx context.Context, exec bob.Executor, related *CartSetter) error {
	var err error

	cart1, err := Carts.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachCartItemCart0(ctx, exec, 1, cartItem0, cart1)
	if err != nil {
		return err
	}

	cartItem0.R.Cart = cart1

	cart1.R.CartItems = append(cart1.R.CartItems, cartItem0)

	return nil
}

func (cartItem0 *CartItem) AttachCart(ctx context.Context, exec bob.Executor, cart1 *Cart) error {
	var err error

	_, err = attachCartItemCart0(ctx, exec, 1, cartItem0, cart1)
	if err != nil {
		return err
	}

	cartItem0.R.Cart = cart1

	cart1.R.CartItems = append(cart1.R.CartItems, cartItem0)

	return nil
}

type cartItemWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, string]
	CartID    psql.WhereMod[Q, string]
	BookID    psql.WhereMod[Q, string]
	Quantity  psql.WhereMod[Q, int32]
	CreatedAt psql.WhereMod[Q, time.Time]
	UpdatedAt psql.WhereMod[Q, time.Time]
}

func (cartItemWhere[Q]) AliasedAs(alias string) cartItemWhere[Q] {
	return buildCartItemWhere[Q](buildCartItemColumns(alias))
}

func buildCartItemWhere[Q psql.Filterable](cols cartItemColumns) cartItemWhere[Q] {
	return cartItemWhere[Q]{
		ID:        psql.Where[Q, string](cols.ID),
		CartID:    psql.Where[Q, string](cols.CartID),
		BookID:    psql.Where[Q, string](cols.BookID),
		Quantity:  psql.Where[Q, int32](cols.Quantity),
		CreatedAt: psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt: psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *CartItem) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Book":
		rel, ok := retrieved.(*Book)
		if !ok {
			return fmt.Errorf("cartItem cannot load %T as %q", retrieved, name)
		}

		o.R.Book = rel

		if rel != nil {
			rel.R.CartItems = CartItemSlice{o}
		}
		return nil
	case "Cart":
		rel, ok := retrieved.(*Cart)
		if !ok {
			return fmt.Errorf("cartItem cannot load %T as %q", retrieved, name)
		}

		o.R.Cart = rel

		if rel != nil {
			rel.R.CartItems = CartItemSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("cartItem has no relationship %q", name)
	}
}

type cartItemPreloader struct {
	Book func(...psql.PreloadOption) psql.Preloader
	Cart func(...psql.PreloadOption) psql.Preloader
}

func buildCartItemPreloader() cartItemPreloader {
	return cartItemPreloader{
		Book: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Book, BookSlice](psql.PreloadRel{
				Name: "Book",
				Sides: []psql.PreloadSide{
					{
						From:        CartItems,
						To:          Books,
						FromColumns: []string{"book_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Books.Columns.Names(), opts...)
		},
		Cart: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Cart, CartSlice](psql.PreloadRel{
				Name: "Cart",
				Sides: []psql.PreloadSide{
					{
						From:        CartItems,
						To:          Carts,
						FromColumns: []string{"cart_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Carts.Columns.Names(), opts...)
		},
	}
}

type cartItemThenLoader[Q orm.Loadable] struct {
	Book func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Cart func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildCartItemThenLoader[Q orm.Loadable]() cartItemThenLoader[Q] {
	type BookLoadInterface interface {
		LoadBook(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type CartLoadInterface interface {
		LoadCart(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return cartItemThenLoader[Q]{
		Book: thenLoadBuilder[Q](
			"Book",
			func(ctx context.Context, exec bob.Executor, retrieved BookLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadBook(ctx, exec, mods...)
			},
		),
		Cart: thenLoadBuilder[Q](
			"Cart",
			func(ctx context.Context, exec bob.Executor, retrieved CartLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCart(ctx, exec, mods...)
			},
		),
	}
}

// LoadBook loads the cartItem's Book into the .R struct
func (o *CartItem) LoadBook(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Book = nil

	related, err := o.Book(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.CartItems = CartItemSlice{o}

	o.R.Book = related
	return nil
}

// LoadBook loads the cartItem's Book into the .R struct
func (os CartItemSlice) LoadBook(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	books, err := os.Book(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range books {

			if !(o.BookID == rel.ID) {
				continue
			}

			rel.R.CartItems = append(rel.R.CartItems, o)

			o.R.Book = rel
			break
		}
	}

	return nil
}

// LoadCart loads the cartItem's Cart into the .R struct
func (o *CartItem) LoadCart(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Cart = nil

	related, err := o.Cart(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.CartItems = CartItemSlice{o}

	o.R.Cart = related
	return nil
}

// LoadCart loads the cartItem's Cart into the .R struct
func (os CartItemSlice) LoadCart(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	carts, err := os.Cart(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range carts {

			if !(o.CartID == rel.ID) {
				continue
			}

			rel.R.CartItems = append(rel.R.CartItems, o)

			o.R.Cart = rel
			break
		}
	}

	return nil
}

type cartItemJoins[Q dialect.Joinable] struct {
	typ  string
	Book modAs[Q, bookColumns]
	Cart modAs[Q, cartColumns]
}

func (j cartItemJoins[Q]) aliasedAs(alias string) cartItemJoins[Q] {
	return buildCartItemJoins[Q](buildCartItemColumns(alias), j.typ)
}

func buildCartItemJoins[Q dialect.Joinable](cols cartItemColumns, typ string) cartItemJoins[Q] {
	return cartItemJoins[Q]{
		typ: typ,
		Book: modAs[Q, bookColumns]{
			c: Books.Columns,
			f: func(to bookColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Books.Name().As(to.Alias())).On(
						to.ID.EQ(cols.BookID),
					))
				}

				return mods
			},
		},
		Cart: modAs[Q, cartColumns]{
			c: Carts.Columns,
			f: func(to cartColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Carts.Name().As(to.Alias())).On(
						to.ID.EQ(cols.CartID),
					))
				}

				return mods
			},
		},
	}
}
