// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Cart is an object representing the database table.
type Cart struct {
	ID        string    `db:"id,pk" `
	UserID    string    `db:"user_id" `
	Status    string    `db:"status" `
	CreatedAt time.Time `db:"created_at" `
	UpdatedAt time.Time `db:"updated_at" `

	R cartR `db:"-" `
}

// CartSlice is an alias for a slice of pointers to Cart.
// This should almost always be used instead of []*Cart.
type CartSlice []*Cart

// Carts contains methods to work with the carts table
var Carts = psql.NewTablex[*Cart, CartSlice, *CartSetter]("", "carts", buildCartColumns("carts"))

// CartsQuery is a query on the carts table
type CartsQuery = *psql.ViewQuery[*Cart, CartSlice]

// cartR is where relationships are stored.
type cartR struct {
	CartItems CartItemSlice // cart_items.cart_items_cart_id_fkey
	User      *User         // carts.carts_user_id_fkey
}

func buildCartColumns(alias string) cartColumns {
	return cartColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "user_id", "status", "created_at", "updated_at",
		).WithParent("carts"),
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		UserID:     psql.Quote(alias, "user_id"),
		Status:     psql.Quote(alias, "status"),
		CreatedAt:  psql.Quote(alias, "created_at"),
		UpdatedAt:  psql.Quote(alias, "updated_at"),
	}
}

type cartColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         psql.Expression
	UserID     psql.Expression
	Status     psql.Expression
	CreatedAt  psql.Expression
	UpdatedAt  psql.Expression
}

func (c cartColumns) Alias() string {
	return c.tableAlias
}

func (cartColumns) AliasedAs(alias string) cartColumns {
	return buildCartColumns(alias)
}

// CartSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type CartSetter struct {
	ID        omit.Val[string]    `db:"id,pk" `
	UserID    omit.Val[string]    `db:"user_id" `
	Status    omit.Val[string]    `db:"status" `
	CreatedAt omit.Val[time.Time] `db:"created_at" `
	UpdatedAt omit.Val[time.Time] `db:"updated_at" `
}

func (s CartSetter) SetColumns() []string {
	vals := make([]string, 0, 5)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.Status.IsValue() {
		vals = append(vals, "status")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s CartSetter) Overwrite(t *Cart) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.Status.IsValue() {
		t.Status = s.Status.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *CartSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Carts.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 5)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.UserID.IsValue() {
			vals[1] = psql.Arg(s.UserID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Status.IsValue() {
			vals[2] = psql.Arg(s.Status.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[3] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[4] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s CartSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s CartSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 5)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if s.Status.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "status")...),
			psql.Arg(s.Status),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindCart retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindCart(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*Cart, error) {
	if len(cols) == 0 {
		return Carts.Query(
			sm.Where(Carts.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Carts.Query(
		sm.Where(Carts.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Carts.Columns.Only(cols...)),
	).One(ctx, exec)
}

// CartExists checks the presence of a single record by primary key
func CartExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return Carts.Query(
		sm.Where(Carts.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Cart is retrieved from the database
func (o *Cart) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Carts.AfterSelectHooks.RunHooks(ctx, exec, CartSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Carts.AfterInsertHooks.RunHooks(ctx, exec, CartSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Carts.AfterUpdateHooks.RunHooks(ctx, exec, CartSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Carts.AfterDeleteHooks.RunHooks(ctx, exec, CartSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Cart
func (o *Cart) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Cart) pkEQ() dialect.Expression {
	return psql.Quote("carts", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Cart
func (o *Cart) Update(ctx context.Context, exec bob.Executor, s *CartSetter) error {
	v, err := Carts.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Cart record with an executor
func (o *Cart) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Carts.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Cart using the executor
func (o *Cart) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Carts.Query(
		sm.Where(Carts.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after CartSlice is retrieved from the database
func (o CartSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Carts.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Carts.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Carts.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Carts.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o CartSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("carts", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o CartSlice) copyMatchingRows(from ...*Cart) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o CartSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Carts.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Cart:
				o.copyMatchingRows(retrieved)
			case []*Cart:
				o.copyMatchingRows(retrieved...)
			case CartSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Cart or a slice of Cart
				// then run the AfterUpdateHooks on the slice
				_, err = Carts.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o CartSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Carts.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Cart:
				o.copyMatchingRows(retrieved)
			case []*Cart:
				o.copyMatchingRows(retrieved...)
			case CartSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Cart or a slice of Cart
				// then run the AfterDeleteHooks on the slice
				_, err = Carts.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o CartSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals CartSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Carts.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o CartSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Carts.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o CartSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Carts.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// CartItems starts a query for related objects on cart_items
func (o *Cart) CartItems(mods ...bob.Mod[*dialect.SelectQuery]) CartItemsQuery {
	return CartItems.Query(append(mods,
		sm.Where(CartItems.Columns.CartID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os CartSlice) CartItems(mods ...bob.Mod[*dialect.SelectQuery]) CartItemsQuery {
	pkID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "character varying[]")),
	))

	return CartItems.Query(append(mods,
		sm.Where(psql.Group(CartItems.Columns.CartID).OP("IN", PKArgExpr)),
	)...)
}

// User starts a query for related objects on users
func (o *Cart) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os CartSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkUserID = append(pkUserID, o.UserID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserID), "character varying[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func insertCartCartItems0(ctx context.Context, exec bob.Executor, cartItems1 []*CartItemSetter, cart0 *Cart) (CartItemSlice, error) {
	for i := range cartItems1 {
		cartItems1[i].CartID = omit.From(cart0.ID)
	}

	ret, err := CartItems.Insert(bob.ToMods(cartItems1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertCartCartItems0: %w", err)
	}

	return ret, nil
}

func attachCartCartItems0(ctx context.Context, exec bob.Executor, count int, cartItems1 CartItemSlice, cart0 *Cart) (CartItemSlice, error) {
	setter := &CartItemSetter{
		CartID: omit.From(cart0.ID),
	}

	err := cartItems1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachCartCartItems0: %w", err)
	}

	return cartItems1, nil
}

func (cart0 *Cart) InsertCartItems(ctx context.Context, exec bob.Executor, related ...*CartItemSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	cartItems1, err := insertCartCartItems0(ctx, exec, related, cart0)
	if err != nil {
		return err
	}

	cart0.R.CartItems = append(cart0.R.CartItems, cartItems1...)

	for _, rel := range cartItems1 {
		rel.R.Cart = cart0
	}
	return nil
}

func (cart0 *Cart) AttachCartItems(ctx context.Context, exec bob.Executor, related ...*CartItem) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	cartItems1 := CartItemSlice(related)

	_, err = attachCartCartItems0(ctx, exec, len(related), cartItems1, cart0)
	if err != nil {
		return err
	}

	cart0.R.CartItems = append(cart0.R.CartItems, cartItems1...)

	for _, rel := range related {
		rel.R.Cart = cart0
	}

	return nil
}

func attachCartUser0(ctx context.Context, exec bob.Executor, count int, cart0 *Cart, user1 *User) (*Cart, error) {
	setter := &CartSetter{
		UserID: omit.From(user1.ID),
	}

	err := cart0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachCartUser0: %w", err)
	}

	return cart0, nil
}

func (cart0 *Cart) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachCartUser0(ctx, exec, 1, cart0, user1)
	if err != nil {
		return err
	}

	cart0.R.User = user1

	user1.R.Carts = append(user1.R.Carts, cart0)

	return nil
}

func (cart0 *Cart) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachCartUser0(ctx, exec, 1, cart0, user1)
	if err != nil {
		return err
	}

	cart0.R.User = user1

	user1.R.Carts = append(user1.R.Carts, cart0)

	return nil
}

type cartWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, string]
	UserID    psql.WhereMod[Q, string]
	Status    psql.WhereMod[Q, string]
	CreatedAt psql.WhereMod[Q, time.Time]
	UpdatedAt psql.WhereMod[Q, time.Time]
}

func (cartWhere[Q]) AliasedAs(alias string) cartWhere[Q] {
	return buildCartWhere[Q](buildCartColumns(alias))
}

func buildCartWhere[Q psql.Filterable](cols cartColumns) cartWhere[Q] {
	return cartWhere[Q]{
		ID:        psql.Where[Q, string](cols.ID),
		UserID:    psql.Where[Q, string](cols.UserID),
		Status:    psql.Where[Q, string](cols.Status),
		CreatedAt: psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt: psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *Cart) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "CartItems":
		rels, ok := retrieved.(CartItemSlice)
		if !ok {
			return fmt.Errorf("cart cannot load %T as %q", retrieved, name)
		}

		o.R.CartItems = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Cart = o
			}
		}
		return nil
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("cart cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.Carts = CartSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("cart has no relationship %q", name)
	}
}

type cartPreloader struct {
	User func(...psql.PreloadOption) psql.Preloader
}

func buildCartPreloader() cartPreloader {
	return cartPreloader{
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "User",
				Sides: []psql.PreloadSide{
					{
						From:        Carts,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type cartThenLoader[Q orm.Loadable] struct {
	CartItems func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	User      func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildCartThenLoader[Q orm.Loadable]() cartThenLoader[Q] {
	type CartItemsLoadInterface interface {
		LoadCartItems(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return cartThenLoader[Q]{
		CartItems: thenLoadBuilder[Q](
			"CartItems",
			func(ctx context.Context, exec bob.Executor, retrieved CartItemsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCartItems(ctx, exec, mods...)
			},
		),
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadCartItems loads the cart's CartItems into the .R struct
func (o *Cart) LoadCartItems(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.CartItems = nil

	related, err := o.CartItems(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Cart = o
	}

	o.R.CartItems = related
	return nil
}

// LoadCartItems loads the cart's CartItems into the .R struct
func (os CartSlice) LoadCartItems(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	cartItems, err := os.CartItems(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.CartItems = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range cartItems {

			if !(o.ID == rel.CartID) {
				continue
			}

			rel.R.Cart = o

			o.R.CartItems = append(o.R.CartItems, rel)
		}
	}

	return nil
}

// LoadUser loads the cart's User into the .R struct
func (o *Cart) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Carts = CartSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the cart's User into the .R struct
func (os CartSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			rel.R.Carts = append(rel.R.Carts, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

type cartJoins[Q dialect.Joinable] struct {
	typ       string
	CartItems modAs[Q, cartItemColumns]
	User      modAs[Q, userColumns]
}

func (j cartJoins[Q]) aliasedAs(alias string) cartJoins[Q] {
	return buildCartJoins[Q](buildCartColumns(alias), j.typ)
}

func buildCartJoins[Q dialect.Joinable](cols cartColumns, typ string) cartJoins[Q] {
	return cartJoins[Q]{
		typ: typ,
		CartItems: modAs[Q, cartItemColumns]{
			c: CartItems.Columns,
			f: func(to cartItemColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, CartItems.Name().As(to.Alias())).On(
						to.CartID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
