// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Order is an object representing the database table.
type Order struct {
	ID               string          `db:"id,pk" `
	UserID           string          `db:"user_id" `
	CartID           string          `db:"cart_id" `
	Amount           decimal.Decimal `db:"amount" `
	DelieveryAddress string          `db:"delievery_address" `
	CreatedAt        time.Time       `db:"created_at" `
	UpdatedAt        time.Time       `db:"updated_at" `

	R orderR `db:"-" `
}

// OrderSlice is an alias for a slice of pointers to Order.
// This should almost always be used instead of []*Order.
type OrderSlice []*Order

// Orders contains methods to work with the orders table
var Orders = psql.NewTablex[*Order, OrderSlice, *OrderSetter]("", "orders", buildOrderColumns("orders"))

// OrdersQuery is a query on the orders table
type OrdersQuery = *psql.ViewQuery[*Order, OrderSlice]

// orderR is where relationships are stored.
type orderR struct {
	Cart *Cart // orders.orders_cart_id_fkey
	User *User // orders.orders_user_id_fkey
}

func buildOrderColumns(alias string) orderColumns {
	return orderColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "user_id", "cart_id", "amount", "delievery_address", "created_at", "updated_at",
		).WithParent("orders"),
		tableAlias:       alias,
		ID:               psql.Quote(alias, "id"),
		UserID:           psql.Quote(alias, "user_id"),
		CartID:           psql.Quote(alias, "cart_id"),
		Amount:           psql.Quote(alias, "amount"),
		DelieveryAddress: psql.Quote(alias, "delievery_address"),
		CreatedAt:        psql.Quote(alias, "created_at"),
		UpdatedAt:        psql.Quote(alias, "updated_at"),
	}
}

type orderColumns struct {
	expr.ColumnsExpr
	tableAlias       string
	ID               psql.Expression
	UserID           psql.Expression
	CartID           psql.Expression
	Amount           psql.Expression
	DelieveryAddress psql.Expression
	CreatedAt        psql.Expression
	UpdatedAt        psql.Expression
}

func (c orderColumns) Alias() string {
	return c.tableAlias
}

func (orderColumns) AliasedAs(alias string) orderColumns {
	return buildOrderColumns(alias)
}

// OrderSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type OrderSetter struct {
	ID               omit.Val[string]          `db:"id,pk" `
	UserID           omit.Val[string]          `db:"user_id" `
	CartID           omit.Val[string]          `db:"cart_id" `
	Amount           omit.Val[decimal.Decimal] `db:"amount" `
	DelieveryAddress omit.Val[string]          `db:"delievery_address" `
	CreatedAt        omit.Val[time.Time]       `db:"created_at" `
	UpdatedAt        omit.Val[time.Time]       `db:"updated_at" `
}

func (s OrderSetter) SetColumns() []string {
	vals := make([]string, 0, 7)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.CartID.IsValue() {
		vals = append(vals, "cart_id")
	}
	if s.Amount.IsValue() {
		vals = append(vals, "amount")
	}
	if s.DelieveryAddress.IsValue() {
		vals = append(vals, "delievery_address")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s OrderSetter) Overwrite(t *Order) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.CartID.IsValue() {
		t.CartID = s.CartID.MustGet()
	}
	if s.Amount.IsValue() {
		t.Amount = s.Amount.MustGet()
	}
	if s.DelieveryAddress.IsValue() {
		t.DelieveryAddress = s.DelieveryAddress.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *OrderSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Orders.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 7)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.UserID.IsValue() {
			vals[1] = psql.Arg(s.UserID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.CartID.IsValue() {
			vals[2] = psql.Arg(s.CartID.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Amount.IsValue() {
			vals[3] = psql.Arg(s.Amount.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.DelieveryAddress.IsValue() {
			vals[4] = psql.Arg(s.DelieveryAddress.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[5] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[6] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s OrderSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s OrderSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 7)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if s.CartID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "cart_id")...),
			psql.Arg(s.CartID),
		}})
	}

	if s.Amount.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "amount")...),
			psql.Arg(s.Amount),
		}})
	}

	if s.DelieveryAddress.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "delievery_address")...),
			psql.Arg(s.DelieveryAddress),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindOrder retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindOrder(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*Order, error) {
	if len(cols) == 0 {
		return Orders.Query(
			sm.Where(Orders.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Orders.Query(
		sm.Where(Orders.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Orders.Columns.Only(cols...)),
	).One(ctx, exec)
}

// OrderExists checks the presence of a single record by primary key
func OrderExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return Orders.Query(
		sm.Where(Orders.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Order is retrieved from the database
func (o *Order) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Orders.AfterSelectHooks.RunHooks(ctx, exec, OrderSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Orders.AfterInsertHooks.RunHooks(ctx, exec, OrderSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Orders.AfterUpdateHooks.RunHooks(ctx, exec, OrderSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Orders.AfterDeleteHooks.RunHooks(ctx, exec, OrderSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Order
func (o *Order) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Order) pkEQ() dialect.Expression {
	return psql.Quote("orders", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Order
func (o *Order) Update(ctx context.Context, exec bob.Executor, s *OrderSetter) error {
	v, err := Orders.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Order record with an executor
func (o *Order) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Orders.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Order using the executor
func (o *Order) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Orders.Query(
		sm.Where(Orders.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after OrderSlice is retrieved from the database
func (o OrderSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Orders.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Orders.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Orders.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Orders.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o OrderSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("orders", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o OrderSlice) copyMatchingRows(from ...*Order) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o OrderSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Orders.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Order:
				o.copyMatchingRows(retrieved)
			case []*Order:
				o.copyMatchingRows(retrieved...)
			case OrderSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Order or a slice of Order
				// then run the AfterUpdateHooks on the slice
				_, err = Orders.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o OrderSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Orders.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Order:
				o.copyMatchingRows(retrieved)
			case []*Order:
				o.copyMatchingRows(retrieved...)
			case OrderSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Order or a slice of Order
				// then run the AfterDeleteHooks on the slice
				_, err = Orders.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o OrderSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals OrderSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Orders.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o OrderSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Orders.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o OrderSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Orders.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Cart starts a query for related objects on carts
func (o *Order) Cart(mods ...bob.Mod[*dialect.SelectQuery]) CartsQuery {
	return Carts.Query(append(mods,
		sm.Where(Carts.Columns.ID.EQ(psql.Arg(o.CartID))),
	)...)
}

func (os OrderSlice) Cart(mods ...bob.Mod[*dialect.SelectQuery]) CartsQuery {
	pkCartID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkCartID = append(pkCartID, o.CartID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkCartID), "character varying[]")),
	))

	return Carts.Query(append(mods,
		sm.Where(psql.Group(Carts.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// User starts a query for related objects on users
func (o *Order) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os OrderSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkUserID = append(pkUserID, o.UserID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserID), "character varying[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachOrderCart0(ctx context.Context, exec bob.Executor, count int, order0 *Order, cart1 *Cart) (*Order, error) {
	setter := &OrderSetter{
		CartID: omit.From(cart1.ID),
	}

	err := order0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachOrderCart0: %w", err)
	}

	return order0, nil
}

func (order0 *Order) InsertCart(ctx context.Context, exec bob.Executor, related *CartSetter) error {
	var err error

	cart1, err := Carts.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachOrderCart0(ctx, exec, 1, order0, cart1)
	if err != nil {
		return err
	}

	order0.R.Cart = cart1

	cart1.R.Orders = append(cart1.R.Orders, order0)

	return nil
}

func (order0 *Order) AttachCart(ctx context.Context, exec bob.Executor, cart1 *Cart) error {
	var err error

	_, err = attachOrderCart0(ctx, exec, 1, order0, cart1)
	if err != nil {
		return err
	}

	order0.R.Cart = cart1

	cart1.R.Orders = append(cart1.R.Orders, order0)

	return nil
}

func attachOrderUser0(ctx context.Context, exec bob.Executor, count int, order0 *Order, user1 *User) (*Order, error) {
	setter := &OrderSetter{
		UserID: omit.From(user1.ID),
	}

	err := order0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachOrderUser0: %w", err)
	}

	return order0, nil
}

func (order0 *Order) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachOrderUser0(ctx, exec, 1, order0, user1)
	if err != nil {
		return err
	}

	order0.R.User = user1

	user1.R.Orders = append(user1.R.Orders, order0)

	return nil
}

func (order0 *Order) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachOrderUser0(ctx, exec, 1, order0, user1)
	if err != nil {
		return err
	}

	order0.R.User = user1

	user1.R.Orders = append(user1.R.Orders, order0)

	return nil
}

type orderWhere[Q psql.Filterable] struct {
	ID               psql.WhereMod[Q, string]
	UserID           psql.WhereMod[Q, string]
	CartID           psql.WhereMod[Q, string]
	Amount           psql.WhereMod[Q, decimal.Decimal]
	DelieveryAddress psql.WhereMod[Q, string]
	CreatedAt        psql.WhereMod[Q, time.Time]
	UpdatedAt        psql.WhereMod[Q, time.Time]
}

func (orderWhere[Q]) AliasedAs(alias string) orderWhere[Q] {
	return buildOrderWhere[Q](buildOrderColumns(alias))
}

func buildOrderWhere[Q psql.Filterable](cols orderColumns) orderWhere[Q] {
	return orderWhere[Q]{
		ID:               psql.Where[Q, string](cols.ID),
		UserID:           psql.Where[Q, string](cols.UserID),
		CartID:           psql.Where[Q, string](cols.CartID),
		Amount:           psql.Where[Q, decimal.Decimal](cols.Amount),
		DelieveryAddress: psql.Where[Q, string](cols.DelieveryAddress),
		CreatedAt:        psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:        psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *Order) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Cart":
		rel, ok := retrieved.(*Cart)
		if !ok {
			return fmt.Errorf("order cannot load %T as %q", retrieved, name)
		}

		o.R.Cart = rel

		if rel != nil {
			rel.R.Orders = OrderSlice{o}
		}
		return nil
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("order cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.Orders = OrderSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("order has no relationship %q", name)
	}
}

type orderPreloader struct {
	Cart func(...psql.PreloadOption) psql.Preloader
	User func(...psql.PreloadOption) psql.Preloader
}

func buildOrderPreloader() orderPreloader {
	return orderPreloader{
		Cart: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Cart, CartSlice](psql.PreloadRel{
				Name: "Cart",
				Sides: []psql.PreloadSide{
					{
						From:        Orders,
						To:          Carts,
						FromColumns: []string{"cart_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Carts.Columns.Names(), opts...)
		},
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "User",
				Sides: []psql.PreloadSide{
					{
						From:        Orders,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type orderThenLoader[Q orm.Loadable] struct {
	Cart func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	User func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildOrderThenLoader[Q orm.Loadable]() orderThenLoader[Q] {
	type CartLoadInterface interface {
		LoadCart(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return orderThenLoader[Q]{
		Cart: thenLoadBuilder[Q](
			"Cart",
			func(ctx context.Context, exec bob.Executor, retrieved CartLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCart(ctx, exec, mods...)
			},
		),
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadCart loads the order's Cart into the .R struct
func (o *Order) LoadCart(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Cart = nil

	related, err := o.Cart(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Orders = OrderSlice{o}

	o.R.Cart = related
	return nil
}

// LoadCart loads the order's Cart into the .R struct
func (os OrderSlice) LoadCart(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	carts, err := os.Cart(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range carts {

			if !(o.CartID == rel.ID) {
				continue
			}

			rel.R.Orders = append(rel.R.Orders, o)

			o.R.Cart = rel
			break
		}
	}

	return nil
}

// LoadUser loads the order's User into the .R struct
func (o *Order) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Orders = OrderSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the order's User into the .R struct
func (os OrderSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			rel.R.Orders = append(rel.R.Orders, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

type orderJoins[Q dialect.Joinable] struct {
	typ  string
	Cart modAs[Q, cartColumns]
	User modAs[Q, userColumns]
}

func (j orderJoins[Q]) aliasedAs(alias string) orderJoins[Q] {
	return buildOrderJoins[Q](buildOrderColumns(alias), j.typ)
}

func buildOrderJoins[Q dialect.Joinable](cols orderColumns, typ string) orderJoins[Q] {
	return orderJoins[Q]{
		typ: typ,
		Cart: modAs[Q, cartColumns]{
			c: Carts.Columns,
			f: func(to cartColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Carts.Name().As(to.Alias())).On(
						to.ID.EQ(cols.CartID),
					))
				}

				return mods
			},
		},
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
