// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Order is an object representing the database table.
type Order struct {
	ID              string                      `db:"id,pk" `
	UserID          string                      `db:"user_id" `
	Status          string                      `db:"status" `
	DiscountValue   decimal.Decimal             `db:"discount_value" `
	DiscountType    string                      `db:"discount_type" `
	GrossAmount     decimal.Decimal             `db:"gross_amount" `
	NetAmount       decimal.Decimal             `db:"net_amount" `
	ShippingAddress types.JSON[json.RawMessage] `db:"shipping_address" `
	ShippingCity    string                      `db:"shipping_city" `
	ShippingState   string                      `db:"shipping_state" `
	ShippingPincode string                      `db:"shipping_pincode" `
	PaymentStatus   string                      `db:"payment_status" `
	PaymentMethod   string                      `db:"payment_method" `
	Currency        string                      `db:"currency" `
	CreatedAt       time.Time                   `db:"created_at" `
	UpdatedAt       time.Time                   `db:"updated_at" `

	R orderR `db:"-" `
}

// OrderSlice is an alias for a slice of pointers to Order.
// This should almost always be used instead of []*Order.
type OrderSlice []*Order

// Orders contains methods to work with the orders table
var Orders = psql.NewTablex[*Order, OrderSlice, *OrderSetter]("", "orders", buildOrderColumns("orders"))

// OrdersQuery is a query on the orders table
type OrdersQuery = *psql.ViewQuery[*Order, OrderSlice]

// orderR is where relationships are stored.
type orderR struct {
	OrderItems OrderItemSlice // order_items.order_items_order_id_fkey
	User       *User          // orders.orders_user_id_fkey
}

func buildOrderColumns(alias string) orderColumns {
	return orderColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "user_id", "status", "discount_value", "discount_type", "gross_amount", "net_amount", "shipping_address", "shipping_city", "shipping_state", "shipping_pincode", "payment_status", "payment_method", "currency", "created_at", "updated_at",
		).WithParent("orders"),
		tableAlias:      alias,
		ID:              psql.Quote(alias, "id"),
		UserID:          psql.Quote(alias, "user_id"),
		Status:          psql.Quote(alias, "status"),
		DiscountValue:   psql.Quote(alias, "discount_value"),
		DiscountType:    psql.Quote(alias, "discount_type"),
		GrossAmount:     psql.Quote(alias, "gross_amount"),
		NetAmount:       psql.Quote(alias, "net_amount"),
		ShippingAddress: psql.Quote(alias, "shipping_address"),
		ShippingCity:    psql.Quote(alias, "shipping_city"),
		ShippingState:   psql.Quote(alias, "shipping_state"),
		ShippingPincode: psql.Quote(alias, "shipping_pincode"),
		PaymentStatus:   psql.Quote(alias, "payment_status"),
		PaymentMethod:   psql.Quote(alias, "payment_method"),
		Currency:        psql.Quote(alias, "currency"),
		CreatedAt:       psql.Quote(alias, "created_at"),
		UpdatedAt:       psql.Quote(alias, "updated_at"),
	}
}

type orderColumns struct {
	expr.ColumnsExpr
	tableAlias      string
	ID              psql.Expression
	UserID          psql.Expression
	Status          psql.Expression
	DiscountValue   psql.Expression
	DiscountType    psql.Expression
	GrossAmount     psql.Expression
	NetAmount       psql.Expression
	ShippingAddress psql.Expression
	ShippingCity    psql.Expression
	ShippingState   psql.Expression
	ShippingPincode psql.Expression
	PaymentStatus   psql.Expression
	PaymentMethod   psql.Expression
	Currency        psql.Expression
	CreatedAt       psql.Expression
	UpdatedAt       psql.Expression
}

func (c orderColumns) Alias() string {
	return c.tableAlias
}

func (orderColumns) AliasedAs(alias string) orderColumns {
	return buildOrderColumns(alias)
}

// OrderSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type OrderSetter struct {
	ID              omit.Val[string]                      `db:"id,pk" `
	UserID          omit.Val[string]                      `db:"user_id" `
	Status          omit.Val[string]                      `db:"status" `
	DiscountValue   omit.Val[decimal.Decimal]             `db:"discount_value" `
	DiscountType    omit.Val[string]                      `db:"discount_type" `
	GrossAmount     omit.Val[decimal.Decimal]             `db:"gross_amount" `
	NetAmount       omit.Val[decimal.Decimal]             `db:"net_amount" `
	ShippingAddress omit.Val[types.JSON[json.RawMessage]] `db:"shipping_address" `
	ShippingCity    omit.Val[string]                      `db:"shipping_city" `
	ShippingState   omit.Val[string]                      `db:"shipping_state" `
	ShippingPincode omit.Val[string]                      `db:"shipping_pincode" `
	PaymentStatus   omit.Val[string]                      `db:"payment_status" `
	PaymentMethod   omit.Val[string]                      `db:"payment_method" `
	Currency        omit.Val[string]                      `db:"currency" `
	CreatedAt       omit.Val[time.Time]                   `db:"created_at" `
	UpdatedAt       omit.Val[time.Time]                   `db:"updated_at" `
}

func (s OrderSetter) SetColumns() []string {
	vals := make([]string, 0, 16)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.Status.IsValue() {
		vals = append(vals, "status")
	}
	if s.DiscountValue.IsValue() {
		vals = append(vals, "discount_value")
	}
	if s.DiscountType.IsValue() {
		vals = append(vals, "discount_type")
	}
	if s.GrossAmount.IsValue() {
		vals = append(vals, "gross_amount")
	}
	if s.NetAmount.IsValue() {
		vals = append(vals, "net_amount")
	}
	if s.ShippingAddress.IsValue() {
		vals = append(vals, "shipping_address")
	}
	if s.ShippingCity.IsValue() {
		vals = append(vals, "shipping_city")
	}
	if s.ShippingState.IsValue() {
		vals = append(vals, "shipping_state")
	}
	if s.ShippingPincode.IsValue() {
		vals = append(vals, "shipping_pincode")
	}
	if s.PaymentStatus.IsValue() {
		vals = append(vals, "payment_status")
	}
	if s.PaymentMethod.IsValue() {
		vals = append(vals, "payment_method")
	}
	if s.Currency.IsValue() {
		vals = append(vals, "currency")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s OrderSetter) Overwrite(t *Order) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.Status.IsValue() {
		t.Status = s.Status.MustGet()
	}
	if s.DiscountValue.IsValue() {
		t.DiscountValue = s.DiscountValue.MustGet()
	}
	if s.DiscountType.IsValue() {
		t.DiscountType = s.DiscountType.MustGet()
	}
	if s.GrossAmount.IsValue() {
		t.GrossAmount = s.GrossAmount.MustGet()
	}
	if s.NetAmount.IsValue() {
		t.NetAmount = s.NetAmount.MustGet()
	}
	if s.ShippingAddress.IsValue() {
		t.ShippingAddress = s.ShippingAddress.MustGet()
	}
	if s.ShippingCity.IsValue() {
		t.ShippingCity = s.ShippingCity.MustGet()
	}
	if s.ShippingState.IsValue() {
		t.ShippingState = s.ShippingState.MustGet()
	}
	if s.ShippingPincode.IsValue() {
		t.ShippingPincode = s.ShippingPincode.MustGet()
	}
	if s.PaymentStatus.IsValue() {
		t.PaymentStatus = s.PaymentStatus.MustGet()
	}
	if s.PaymentMethod.IsValue() {
		t.PaymentMethod = s.PaymentMethod.MustGet()
	}
	if s.Currency.IsValue() {
		t.Currency = s.Currency.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *OrderSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Orders.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 16)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.UserID.IsValue() {
			vals[1] = psql.Arg(s.UserID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Status.IsValue() {
			vals[2] = psql.Arg(s.Status.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.DiscountValue.IsValue() {
			vals[3] = psql.Arg(s.DiscountValue.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.DiscountType.IsValue() {
			vals[4] = psql.Arg(s.DiscountType.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.GrossAmount.IsValue() {
			vals[5] = psql.Arg(s.GrossAmount.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.NetAmount.IsValue() {
			vals[6] = psql.Arg(s.NetAmount.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.ShippingAddress.IsValue() {
			vals[7] = psql.Arg(s.ShippingAddress.MustGet())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if s.ShippingCity.IsValue() {
			vals[8] = psql.Arg(s.ShippingCity.MustGet())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		if s.ShippingState.IsValue() {
			vals[9] = psql.Arg(s.ShippingState.MustGet())
		} else {
			vals[9] = psql.Raw("DEFAULT")
		}

		if s.ShippingPincode.IsValue() {
			vals[10] = psql.Arg(s.ShippingPincode.MustGet())
		} else {
			vals[10] = psql.Raw("DEFAULT")
		}

		if s.PaymentStatus.IsValue() {
			vals[11] = psql.Arg(s.PaymentStatus.MustGet())
		} else {
			vals[11] = psql.Raw("DEFAULT")
		}

		if s.PaymentMethod.IsValue() {
			vals[12] = psql.Arg(s.PaymentMethod.MustGet())
		} else {
			vals[12] = psql.Raw("DEFAULT")
		}

		if s.Currency.IsValue() {
			vals[13] = psql.Arg(s.Currency.MustGet())
		} else {
			vals[13] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[14] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[14] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[15] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[15] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s OrderSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s OrderSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 16)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if s.Status.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "status")...),
			psql.Arg(s.Status),
		}})
	}

	if s.DiscountValue.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "discount_value")...),
			psql.Arg(s.DiscountValue),
		}})
	}

	if s.DiscountType.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "discount_type")...),
			psql.Arg(s.DiscountType),
		}})
	}

	if s.GrossAmount.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "gross_amount")...),
			psql.Arg(s.GrossAmount),
		}})
	}

	if s.NetAmount.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "net_amount")...),
			psql.Arg(s.NetAmount),
		}})
	}

	if s.ShippingAddress.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "shipping_address")...),
			psql.Arg(s.ShippingAddress),
		}})
	}

	if s.ShippingCity.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "shipping_city")...),
			psql.Arg(s.ShippingCity),
		}})
	}

	if s.ShippingState.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "shipping_state")...),
			psql.Arg(s.ShippingState),
		}})
	}

	if s.ShippingPincode.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "shipping_pincode")...),
			psql.Arg(s.ShippingPincode),
		}})
	}

	if s.PaymentStatus.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "payment_status")...),
			psql.Arg(s.PaymentStatus),
		}})
	}

	if s.PaymentMethod.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "payment_method")...),
			psql.Arg(s.PaymentMethod),
		}})
	}

	if s.Currency.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "currency")...),
			psql.Arg(s.Currency),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindOrder retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindOrder(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*Order, error) {
	if len(cols) == 0 {
		return Orders.Query(
			sm.Where(Orders.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Orders.Query(
		sm.Where(Orders.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Orders.Columns.Only(cols...)),
	).One(ctx, exec)
}

// OrderExists checks the presence of a single record by primary key
func OrderExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return Orders.Query(
		sm.Where(Orders.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Order is retrieved from the database
func (o *Order) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Orders.AfterSelectHooks.RunHooks(ctx, exec, OrderSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Orders.AfterInsertHooks.RunHooks(ctx, exec, OrderSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Orders.AfterUpdateHooks.RunHooks(ctx, exec, OrderSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Orders.AfterDeleteHooks.RunHooks(ctx, exec, OrderSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Order
func (o *Order) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Order) pkEQ() dialect.Expression {
	return psql.Quote("orders", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Order
func (o *Order) Update(ctx context.Context, exec bob.Executor, s *OrderSetter) error {
	v, err := Orders.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Order record with an executor
func (o *Order) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Orders.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Order using the executor
func (o *Order) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Orders.Query(
		sm.Where(Orders.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after OrderSlice is retrieved from the database
func (o OrderSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Orders.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Orders.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Orders.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Orders.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o OrderSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("orders", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o OrderSlice) copyMatchingRows(from ...*Order) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o OrderSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Orders.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Order:
				o.copyMatchingRows(retrieved)
			case []*Order:
				o.copyMatchingRows(retrieved...)
			case OrderSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Order or a slice of Order
				// then run the AfterUpdateHooks on the slice
				_, err = Orders.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o OrderSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Orders.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Order:
				o.copyMatchingRows(retrieved)
			case []*Order:
				o.copyMatchingRows(retrieved...)
			case OrderSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Order or a slice of Order
				// then run the AfterDeleteHooks on the slice
				_, err = Orders.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o OrderSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals OrderSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Orders.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o OrderSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Orders.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o OrderSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Orders.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// OrderItems starts a query for related objects on order_items
func (o *Order) OrderItems(mods ...bob.Mod[*dialect.SelectQuery]) OrderItemsQuery {
	return OrderItems.Query(append(mods,
		sm.Where(OrderItems.Columns.OrderID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os OrderSlice) OrderItems(mods ...bob.Mod[*dialect.SelectQuery]) OrderItemsQuery {
	pkID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "character varying[]")),
	))

	return OrderItems.Query(append(mods,
		sm.Where(psql.Group(OrderItems.Columns.OrderID).OP("IN", PKArgExpr)),
	)...)
}

// User starts a query for related objects on users
func (o *Order) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os OrderSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkUserID = append(pkUserID, o.UserID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserID), "character varying[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func insertOrderOrderItems0(ctx context.Context, exec bob.Executor, orderItems1 []*OrderItemSetter, order0 *Order) (OrderItemSlice, error) {
	for i := range orderItems1 {
		orderItems1[i].OrderID = omit.From(order0.ID)
	}

	ret, err := OrderItems.Insert(bob.ToMods(orderItems1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertOrderOrderItems0: %w", err)
	}

	return ret, nil
}

func attachOrderOrderItems0(ctx context.Context, exec bob.Executor, count int, orderItems1 OrderItemSlice, order0 *Order) (OrderItemSlice, error) {
	setter := &OrderItemSetter{
		OrderID: omit.From(order0.ID),
	}

	err := orderItems1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachOrderOrderItems0: %w", err)
	}

	return orderItems1, nil
}

func (order0 *Order) InsertOrderItems(ctx context.Context, exec bob.Executor, related ...*OrderItemSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	orderItems1, err := insertOrderOrderItems0(ctx, exec, related, order0)
	if err != nil {
		return err
	}

	order0.R.OrderItems = append(order0.R.OrderItems, orderItems1...)

	for _, rel := range orderItems1 {
		rel.R.Order = order0
	}
	return nil
}

func (order0 *Order) AttachOrderItems(ctx context.Context, exec bob.Executor, related ...*OrderItem) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	orderItems1 := OrderItemSlice(related)

	_, err = attachOrderOrderItems0(ctx, exec, len(related), orderItems1, order0)
	if err != nil {
		return err
	}

	order0.R.OrderItems = append(order0.R.OrderItems, orderItems1...)

	for _, rel := range related {
		rel.R.Order = order0
	}

	return nil
}

func attachOrderUser0(ctx context.Context, exec bob.Executor, count int, order0 *Order, user1 *User) (*Order, error) {
	setter := &OrderSetter{
		UserID: omit.From(user1.ID),
	}

	err := order0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachOrderUser0: %w", err)
	}

	return order0, nil
}

func (order0 *Order) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachOrderUser0(ctx, exec, 1, order0, user1)
	if err != nil {
		return err
	}

	order0.R.User = user1

	user1.R.Orders = append(user1.R.Orders, order0)

	return nil
}

func (order0 *Order) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachOrderUser0(ctx, exec, 1, order0, user1)
	if err != nil {
		return err
	}

	order0.R.User = user1

	user1.R.Orders = append(user1.R.Orders, order0)

	return nil
}

type orderWhere[Q psql.Filterable] struct {
	ID              psql.WhereMod[Q, string]
	UserID          psql.WhereMod[Q, string]
	Status          psql.WhereMod[Q, string]
	DiscountValue   psql.WhereMod[Q, decimal.Decimal]
	DiscountType    psql.WhereMod[Q, string]
	GrossAmount     psql.WhereMod[Q, decimal.Decimal]
	NetAmount       psql.WhereMod[Q, decimal.Decimal]
	ShippingAddress psql.WhereMod[Q, types.JSON[json.RawMessage]]
	ShippingCity    psql.WhereMod[Q, string]
	ShippingState   psql.WhereMod[Q, string]
	ShippingPincode psql.WhereMod[Q, string]
	PaymentStatus   psql.WhereMod[Q, string]
	PaymentMethod   psql.WhereMod[Q, string]
	Currency        psql.WhereMod[Q, string]
	CreatedAt       psql.WhereMod[Q, time.Time]
	UpdatedAt       psql.WhereMod[Q, time.Time]
}

func (orderWhere[Q]) AliasedAs(alias string) orderWhere[Q] {
	return buildOrderWhere[Q](buildOrderColumns(alias))
}

func buildOrderWhere[Q psql.Filterable](cols orderColumns) orderWhere[Q] {
	return orderWhere[Q]{
		ID:              psql.Where[Q, string](cols.ID),
		UserID:          psql.Where[Q, string](cols.UserID),
		Status:          psql.Where[Q, string](cols.Status),
		DiscountValue:   psql.Where[Q, decimal.Decimal](cols.DiscountValue),
		DiscountType:    psql.Where[Q, string](cols.DiscountType),
		GrossAmount:     psql.Where[Q, decimal.Decimal](cols.GrossAmount),
		NetAmount:       psql.Where[Q, decimal.Decimal](cols.NetAmount),
		ShippingAddress: psql.Where[Q, types.JSON[json.RawMessage]](cols.ShippingAddress),
		ShippingCity:    psql.Where[Q, string](cols.ShippingCity),
		ShippingState:   psql.Where[Q, string](cols.ShippingState),
		ShippingPincode: psql.Where[Q, string](cols.ShippingPincode),
		PaymentStatus:   psql.Where[Q, string](cols.PaymentStatus),
		PaymentMethod:   psql.Where[Q, string](cols.PaymentMethod),
		Currency:        psql.Where[Q, string](cols.Currency),
		CreatedAt:       psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:       psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *Order) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "OrderItems":
		rels, ok := retrieved.(OrderItemSlice)
		if !ok {
			return fmt.Errorf("order cannot load %T as %q", retrieved, name)
		}

		o.R.OrderItems = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Order = o
			}
		}
		return nil
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("order cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.Orders = OrderSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("order has no relationship %q", name)
	}
}

type orderPreloader struct {
	User func(...psql.PreloadOption) psql.Preloader
}

func buildOrderPreloader() orderPreloader {
	return orderPreloader{
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "User",
				Sides: []psql.PreloadSide{
					{
						From:        Orders,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type orderThenLoader[Q orm.Loadable] struct {
	OrderItems func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	User       func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildOrderThenLoader[Q orm.Loadable]() orderThenLoader[Q] {
	type OrderItemsLoadInterface interface {
		LoadOrderItems(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return orderThenLoader[Q]{
		OrderItems: thenLoadBuilder[Q](
			"OrderItems",
			func(ctx context.Context, exec bob.Executor, retrieved OrderItemsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadOrderItems(ctx, exec, mods...)
			},
		),
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadOrderItems loads the order's OrderItems into the .R struct
func (o *Order) LoadOrderItems(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.OrderItems = nil

	related, err := o.OrderItems(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Order = o
	}

	o.R.OrderItems = related
	return nil
}

// LoadOrderItems loads the order's OrderItems into the .R struct
func (os OrderSlice) LoadOrderItems(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	orderItems, err := os.OrderItems(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.OrderItems = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range orderItems {

			if !(o.ID == rel.OrderID) {
				continue
			}

			rel.R.Order = o

			o.R.OrderItems = append(o.R.OrderItems, rel)
		}
	}

	return nil
}

// LoadUser loads the order's User into the .R struct
func (o *Order) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Orders = OrderSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the order's User into the .R struct
func (os OrderSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			rel.R.Orders = append(rel.R.Orders, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

type orderJoins[Q dialect.Joinable] struct {
	typ        string
	OrderItems modAs[Q, orderItemColumns]
	User       modAs[Q, userColumns]
}

func (j orderJoins[Q]) aliasedAs(alias string) orderJoins[Q] {
	return buildOrderJoins[Q](buildOrderColumns(alias), j.typ)
}

func buildOrderJoins[Q dialect.Joinable](cols orderColumns, typ string) orderJoins[Q] {
	return orderJoins[Q]{
		typ: typ,
		OrderItems: modAs[Q, orderItemColumns]{
			c: OrderItems.Columns,
			f: func(to orderItemColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, OrderItems.Name().As(to.Alias())).On(
						to.OrderID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
