// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// OrderItem is an object representing the database table.
type OrderItem struct {
	ID         string          `db:"id,pk" `
	OrderID    string          `db:"order_id" `
	BookID     string          `db:"book_id" `
	Title      string          `db:"title" `
	Price      decimal.Decimal `db:"price" `
	Quantity   int32           `db:"quantity" `
	TotalPrice decimal.Decimal `db:"total_price" `
	CreatedAt  time.Time       `db:"created_at" `
	UpdatedAt  time.Time       `db:"updated_at" `

	R orderItemR `db:"-" `
}

// OrderItemSlice is an alias for a slice of pointers to OrderItem.
// This should almost always be used instead of []*OrderItem.
type OrderItemSlice []*OrderItem

// OrderItems contains methods to work with the order_items table
var OrderItems = psql.NewTablex[*OrderItem, OrderItemSlice, *OrderItemSetter]("", "order_items", buildOrderItemColumns("order_items"))

// OrderItemsQuery is a query on the order_items table
type OrderItemsQuery = *psql.ViewQuery[*OrderItem, OrderItemSlice]

// orderItemR is where relationships are stored.
type orderItemR struct {
	Book  *Book  // order_items.order_items_book_id_fkey
	Order *Order // order_items.order_items_order_id_fkey
}

func buildOrderItemColumns(alias string) orderItemColumns {
	return orderItemColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "order_id", "book_id", "title", "price", "quantity", "total_price", "created_at", "updated_at",
		).WithParent("order_items"),
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		OrderID:    psql.Quote(alias, "order_id"),
		BookID:     psql.Quote(alias, "book_id"),
		Title:      psql.Quote(alias, "title"),
		Price:      psql.Quote(alias, "price"),
		Quantity:   psql.Quote(alias, "quantity"),
		TotalPrice: psql.Quote(alias, "total_price"),
		CreatedAt:  psql.Quote(alias, "created_at"),
		UpdatedAt:  psql.Quote(alias, "updated_at"),
	}
}

type orderItemColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         psql.Expression
	OrderID    psql.Expression
	BookID     psql.Expression
	Title      psql.Expression
	Price      psql.Expression
	Quantity   psql.Expression
	TotalPrice psql.Expression
	CreatedAt  psql.Expression
	UpdatedAt  psql.Expression
}

func (c orderItemColumns) Alias() string {
	return c.tableAlias
}

func (orderItemColumns) AliasedAs(alias string) orderItemColumns {
	return buildOrderItemColumns(alias)
}

// OrderItemSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type OrderItemSetter struct {
	ID         omit.Val[string]          `db:"id,pk" `
	OrderID    omit.Val[string]          `db:"order_id" `
	BookID     omit.Val[string]          `db:"book_id" `
	Title      omit.Val[string]          `db:"title" `
	Price      omit.Val[decimal.Decimal] `db:"price" `
	Quantity   omit.Val[int32]           `db:"quantity" `
	TotalPrice omit.Val[decimal.Decimal] `db:"total_price" `
	CreatedAt  omit.Val[time.Time]       `db:"created_at" `
	UpdatedAt  omit.Val[time.Time]       `db:"updated_at" `
}

func (s OrderItemSetter) SetColumns() []string {
	vals := make([]string, 0, 9)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.OrderID.IsValue() {
		vals = append(vals, "order_id")
	}
	if s.BookID.IsValue() {
		vals = append(vals, "book_id")
	}
	if s.Title.IsValue() {
		vals = append(vals, "title")
	}
	if s.Price.IsValue() {
		vals = append(vals, "price")
	}
	if s.Quantity.IsValue() {
		vals = append(vals, "quantity")
	}
	if s.TotalPrice.IsValue() {
		vals = append(vals, "total_price")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s OrderItemSetter) Overwrite(t *OrderItem) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.OrderID.IsValue() {
		t.OrderID = s.OrderID.MustGet()
	}
	if s.BookID.IsValue() {
		t.BookID = s.BookID.MustGet()
	}
	if s.Title.IsValue() {
		t.Title = s.Title.MustGet()
	}
	if s.Price.IsValue() {
		t.Price = s.Price.MustGet()
	}
	if s.Quantity.IsValue() {
		t.Quantity = s.Quantity.MustGet()
	}
	if s.TotalPrice.IsValue() {
		t.TotalPrice = s.TotalPrice.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *OrderItemSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return OrderItems.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 9)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.OrderID.IsValue() {
			vals[1] = psql.Arg(s.OrderID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.BookID.IsValue() {
			vals[2] = psql.Arg(s.BookID.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Title.IsValue() {
			vals[3] = psql.Arg(s.Title.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.Price.IsValue() {
			vals[4] = psql.Arg(s.Price.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.Quantity.IsValue() {
			vals[5] = psql.Arg(s.Quantity.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.TotalPrice.IsValue() {
			vals[6] = psql.Arg(s.TotalPrice.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[7] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[8] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s OrderItemSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s OrderItemSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 9)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.OrderID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "order_id")...),
			psql.Arg(s.OrderID),
		}})
	}

	if s.BookID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "book_id")...),
			psql.Arg(s.BookID),
		}})
	}

	if s.Title.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "title")...),
			psql.Arg(s.Title),
		}})
	}

	if s.Price.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "price")...),
			psql.Arg(s.Price),
		}})
	}

	if s.Quantity.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "quantity")...),
			psql.Arg(s.Quantity),
		}})
	}

	if s.TotalPrice.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "total_price")...),
			psql.Arg(s.TotalPrice),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindOrderItem retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindOrderItem(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*OrderItem, error) {
	if len(cols) == 0 {
		return OrderItems.Query(
			sm.Where(OrderItems.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return OrderItems.Query(
		sm.Where(OrderItems.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(OrderItems.Columns.Only(cols...)),
	).One(ctx, exec)
}

// OrderItemExists checks the presence of a single record by primary key
func OrderItemExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return OrderItems.Query(
		sm.Where(OrderItems.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after OrderItem is retrieved from the database
func (o *OrderItem) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = OrderItems.AfterSelectHooks.RunHooks(ctx, exec, OrderItemSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = OrderItems.AfterInsertHooks.RunHooks(ctx, exec, OrderItemSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = OrderItems.AfterUpdateHooks.RunHooks(ctx, exec, OrderItemSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = OrderItems.AfterDeleteHooks.RunHooks(ctx, exec, OrderItemSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the OrderItem
func (o *OrderItem) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *OrderItem) pkEQ() dialect.Expression {
	return psql.Quote("order_items", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the OrderItem
func (o *OrderItem) Update(ctx context.Context, exec bob.Executor, s *OrderItemSetter) error {
	v, err := OrderItems.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single OrderItem record with an executor
func (o *OrderItem) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := OrderItems.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the OrderItem using the executor
func (o *OrderItem) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := OrderItems.Query(
		sm.Where(OrderItems.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after OrderItemSlice is retrieved from the database
func (o OrderItemSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = OrderItems.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = OrderItems.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = OrderItems.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = OrderItems.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o OrderItemSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("order_items", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o OrderItemSlice) copyMatchingRows(from ...*OrderItem) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o OrderItemSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return OrderItems.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *OrderItem:
				o.copyMatchingRows(retrieved)
			case []*OrderItem:
				o.copyMatchingRows(retrieved...)
			case OrderItemSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a OrderItem or a slice of OrderItem
				// then run the AfterUpdateHooks on the slice
				_, err = OrderItems.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o OrderItemSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return OrderItems.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *OrderItem:
				o.copyMatchingRows(retrieved)
			case []*OrderItem:
				o.copyMatchingRows(retrieved...)
			case OrderItemSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a OrderItem or a slice of OrderItem
				// then run the AfterDeleteHooks on the slice
				_, err = OrderItems.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o OrderItemSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals OrderItemSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := OrderItems.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o OrderItemSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := OrderItems.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o OrderItemSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := OrderItems.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Book starts a query for related objects on books
func (o *OrderItem) Book(mods ...bob.Mod[*dialect.SelectQuery]) BooksQuery {
	return Books.Query(append(mods,
		sm.Where(Books.Columns.ID.EQ(psql.Arg(o.BookID))),
	)...)
}

func (os OrderItemSlice) Book(mods ...bob.Mod[*dialect.SelectQuery]) BooksQuery {
	pkBookID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkBookID = append(pkBookID, o.BookID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkBookID), "character varying[]")),
	))

	return Books.Query(append(mods,
		sm.Where(psql.Group(Books.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// Order starts a query for related objects on orders
func (o *OrderItem) Order(mods ...bob.Mod[*dialect.SelectQuery]) OrdersQuery {
	return Orders.Query(append(mods,
		sm.Where(Orders.Columns.ID.EQ(psql.Arg(o.OrderID))),
	)...)
}

func (os OrderItemSlice) Order(mods ...bob.Mod[*dialect.SelectQuery]) OrdersQuery {
	pkOrderID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkOrderID = append(pkOrderID, o.OrderID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkOrderID), "character varying[]")),
	))

	return Orders.Query(append(mods,
		sm.Where(psql.Group(Orders.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachOrderItemBook0(ctx context.Context, exec bob.Executor, count int, orderItem0 *OrderItem, book1 *Book) (*OrderItem, error) {
	setter := &OrderItemSetter{
		BookID: omit.From(book1.ID),
	}

	err := orderItem0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachOrderItemBook0: %w", err)
	}

	return orderItem0, nil
}

func (orderItem0 *OrderItem) InsertBook(ctx context.Context, exec bob.Executor, related *BookSetter) error {
	var err error

	book1, err := Books.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachOrderItemBook0(ctx, exec, 1, orderItem0, book1)
	if err != nil {
		return err
	}

	orderItem0.R.Book = book1

	book1.R.OrderItems = append(book1.R.OrderItems, orderItem0)

	return nil
}

func (orderItem0 *OrderItem) AttachBook(ctx context.Context, exec bob.Executor, book1 *Book) error {
	var err error

	_, err = attachOrderItemBook0(ctx, exec, 1, orderItem0, book1)
	if err != nil {
		return err
	}

	orderItem0.R.Book = book1

	book1.R.OrderItems = append(book1.R.OrderItems, orderItem0)

	return nil
}

func attachOrderItemOrder0(ctx context.Context, exec bob.Executor, count int, orderItem0 *OrderItem, order1 *Order) (*OrderItem, error) {
	setter := &OrderItemSetter{
		OrderID: omit.From(order1.ID),
	}

	err := orderItem0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachOrderItemOrder0: %w", err)
	}

	return orderItem0, nil
}

func (orderItem0 *OrderItem) InsertOrder(ctx context.Context, exec bob.Executor, related *OrderSetter) error {
	var err error

	order1, err := Orders.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachOrderItemOrder0(ctx, exec, 1, orderItem0, order1)
	if err != nil {
		return err
	}

	orderItem0.R.Order = order1

	order1.R.OrderItems = append(order1.R.OrderItems, orderItem0)

	return nil
}

func (orderItem0 *OrderItem) AttachOrder(ctx context.Context, exec bob.Executor, order1 *Order) error {
	var err error

	_, err = attachOrderItemOrder0(ctx, exec, 1, orderItem0, order1)
	if err != nil {
		return err
	}

	orderItem0.R.Order = order1

	order1.R.OrderItems = append(order1.R.OrderItems, orderItem0)

	return nil
}

type orderItemWhere[Q psql.Filterable] struct {
	ID         psql.WhereMod[Q, string]
	OrderID    psql.WhereMod[Q, string]
	BookID     psql.WhereMod[Q, string]
	Title      psql.WhereMod[Q, string]
	Price      psql.WhereMod[Q, decimal.Decimal]
	Quantity   psql.WhereMod[Q, int32]
	TotalPrice psql.WhereMod[Q, decimal.Decimal]
	CreatedAt  psql.WhereMod[Q, time.Time]
	UpdatedAt  psql.WhereMod[Q, time.Time]
}

func (orderItemWhere[Q]) AliasedAs(alias string) orderItemWhere[Q] {
	return buildOrderItemWhere[Q](buildOrderItemColumns(alias))
}

func buildOrderItemWhere[Q psql.Filterable](cols orderItemColumns) orderItemWhere[Q] {
	return orderItemWhere[Q]{
		ID:         psql.Where[Q, string](cols.ID),
		OrderID:    psql.Where[Q, string](cols.OrderID),
		BookID:     psql.Where[Q, string](cols.BookID),
		Title:      psql.Where[Q, string](cols.Title),
		Price:      psql.Where[Q, decimal.Decimal](cols.Price),
		Quantity:   psql.Where[Q, int32](cols.Quantity),
		TotalPrice: psql.Where[Q, decimal.Decimal](cols.TotalPrice),
		CreatedAt:  psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:  psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *OrderItem) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Book":
		rel, ok := retrieved.(*Book)
		if !ok {
			return fmt.Errorf("orderItem cannot load %T as %q", retrieved, name)
		}

		o.R.Book = rel

		if rel != nil {
			rel.R.OrderItems = OrderItemSlice{o}
		}
		return nil
	case "Order":
		rel, ok := retrieved.(*Order)
		if !ok {
			return fmt.Errorf("orderItem cannot load %T as %q", retrieved, name)
		}

		o.R.Order = rel

		if rel != nil {
			rel.R.OrderItems = OrderItemSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("orderItem has no relationship %q", name)
	}
}

type orderItemPreloader struct {
	Book  func(...psql.PreloadOption) psql.Preloader
	Order func(...psql.PreloadOption) psql.Preloader
}

func buildOrderItemPreloader() orderItemPreloader {
	return orderItemPreloader{
		Book: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Book, BookSlice](psql.PreloadRel{
				Name: "Book",
				Sides: []psql.PreloadSide{
					{
						From:        OrderItems,
						To:          Books,
						FromColumns: []string{"book_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Books.Columns.Names(), opts...)
		},
		Order: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Order, OrderSlice](psql.PreloadRel{
				Name: "Order",
				Sides: []psql.PreloadSide{
					{
						From:        OrderItems,
						To:          Orders,
						FromColumns: []string{"order_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Orders.Columns.Names(), opts...)
		},
	}
}

type orderItemThenLoader[Q orm.Loadable] struct {
	Book  func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Order func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildOrderItemThenLoader[Q orm.Loadable]() orderItemThenLoader[Q] {
	type BookLoadInterface interface {
		LoadBook(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type OrderLoadInterface interface {
		LoadOrder(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return orderItemThenLoader[Q]{
		Book: thenLoadBuilder[Q](
			"Book",
			func(ctx context.Context, exec bob.Executor, retrieved BookLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadBook(ctx, exec, mods...)
			},
		),
		Order: thenLoadBuilder[Q](
			"Order",
			func(ctx context.Context, exec bob.Executor, retrieved OrderLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadOrder(ctx, exec, mods...)
			},
		),
	}
}

// LoadBook loads the orderItem's Book into the .R struct
func (o *OrderItem) LoadBook(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Book = nil

	related, err := o.Book(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.OrderItems = OrderItemSlice{o}

	o.R.Book = related
	return nil
}

// LoadBook loads the orderItem's Book into the .R struct
func (os OrderItemSlice) LoadBook(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	books, err := os.Book(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range books {

			if !(o.BookID == rel.ID) {
				continue
			}

			rel.R.OrderItems = append(rel.R.OrderItems, o)

			o.R.Book = rel
			break
		}
	}

	return nil
}

// LoadOrder loads the orderItem's Order into the .R struct
func (o *OrderItem) LoadOrder(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Order = nil

	related, err := o.Order(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.OrderItems = OrderItemSlice{o}

	o.R.Order = related
	return nil
}

// LoadOrder loads the orderItem's Order into the .R struct
func (os OrderItemSlice) LoadOrder(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	orders, err := os.Order(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range orders {

			if !(o.OrderID == rel.ID) {
				continue
			}

			rel.R.OrderItems = append(rel.R.OrderItems, o)

			o.R.Order = rel
			break
		}
	}

	return nil
}

type orderItemJoins[Q dialect.Joinable] struct {
	typ   string
	Book  modAs[Q, bookColumns]
	Order modAs[Q, orderColumns]
}

func (j orderItemJoins[Q]) aliasedAs(alias string) orderItemJoins[Q] {
	return buildOrderItemJoins[Q](buildOrderItemColumns(alias), j.typ)
}

func buildOrderItemJoins[Q dialect.Joinable](cols orderItemColumns, typ string) orderItemJoins[Q] {
	return orderItemJoins[Q]{
		typ: typ,
		Book: modAs[Q, bookColumns]{
			c: Books.Columns,
			f: func(to bookColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Books.Name().As(to.Alias())).On(
						to.ID.EQ(cols.BookID),
					))
				}

				return mods
			},
		},
		Order: modAs[Q, orderColumns]{
			c: Orders.Columns,
			f: func(to orderColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Orders.Name().As(to.Alias())).On(
						to.ID.EQ(cols.OrderID),
					))
				}

				return mods
			},
		},
	}
}
