// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// User is an object representing the database table.
type User struct {
	ID        string    `db:"id,pk" `
	Name      string    `db:"name" `
	Email     string    `db:"email" `
	Password  string    `db:"password" `
	Role      string    `db:"role" `
	CreatedAt time.Time `db:"created_at" `
	UpdatedAt time.Time `db:"updated_at" `

	R userR `db:"-" `
}

// UserSlice is an alias for a slice of pointers to User.
// This should almost always be used instead of []*User.
type UserSlice []*User

// Users contains methods to work with the users table
var Users = psql.NewTablex[*User, UserSlice, *UserSetter]("", "users", buildUserColumns("users"))

// UsersQuery is a query on the users table
type UsersQuery = *psql.ViewQuery[*User, UserSlice]

// userR is where relationships are stored.
type userR struct {
	Addresses AddressSlice // addresses.addresses_user_id_fkey
	Carts     CartSlice    // carts.carts_user_id_fkey
	Orders    OrderSlice   // orders.orders_user_id_fkey
}

func buildUserColumns(alias string) userColumns {
	return userColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "name", "email", "password", "role", "created_at", "updated_at",
		).WithParent("users"),
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		Name:       psql.Quote(alias, "name"),
		Email:      psql.Quote(alias, "email"),
		Password:   psql.Quote(alias, "password"),
		Role:       psql.Quote(alias, "role"),
		CreatedAt:  psql.Quote(alias, "created_at"),
		UpdatedAt:  psql.Quote(alias, "updated_at"),
	}
}

type userColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         psql.Expression
	Name       psql.Expression
	Email      psql.Expression
	Password   psql.Expression
	Role       psql.Expression
	CreatedAt  psql.Expression
	UpdatedAt  psql.Expression
}

func (c userColumns) Alias() string {
	return c.tableAlias
}

func (userColumns) AliasedAs(alias string) userColumns {
	return buildUserColumns(alias)
}

// UserSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type UserSetter struct {
	ID        omit.Val[string]    `db:"id,pk" `
	Name      omit.Val[string]    `db:"name" `
	Email     omit.Val[string]    `db:"email" `
	Password  omit.Val[string]    `db:"password" `
	Role      omit.Val[string]    `db:"role" `
	CreatedAt omit.Val[time.Time] `db:"created_at" `
	UpdatedAt omit.Val[time.Time] `db:"updated_at" `
}

func (s UserSetter) SetColumns() []string {
	vals := make([]string, 0, 7)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.Email.IsValue() {
		vals = append(vals, "email")
	}
	if s.Password.IsValue() {
		vals = append(vals, "password")
	}
	if s.Role.IsValue() {
		vals = append(vals, "role")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s UserSetter) Overwrite(t *User) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.Email.IsValue() {
		t.Email = s.Email.MustGet()
	}
	if s.Password.IsValue() {
		t.Password = s.Password.MustGet()
	}
	if s.Role.IsValue() {
		t.Role = s.Role.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *UserSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Users.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 7)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Name.IsValue() {
			vals[1] = psql.Arg(s.Name.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Email.IsValue() {
			vals[2] = psql.Arg(s.Email.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Password.IsValue() {
			vals[3] = psql.Arg(s.Password.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.Role.IsValue() {
			vals[4] = psql.Arg(s.Role.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[5] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[6] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s UserSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s UserSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 7)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.Email.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "email")...),
			psql.Arg(s.Email),
		}})
	}

	if s.Password.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "password")...),
			psql.Arg(s.Password),
		}})
	}

	if s.Role.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "role")...),
			psql.Arg(s.Role),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindUser retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindUser(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*User, error) {
	if len(cols) == 0 {
		return Users.Query(
			sm.Where(Users.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Users.Query(
		sm.Where(Users.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Users.Columns.Only(cols...)),
	).One(ctx, exec)
}

// UserExists checks the presence of a single record by primary key
func UserExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return Users.Query(
		sm.Where(Users.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after User is retrieved from the database
func (o *User) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Users.AfterSelectHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Users.AfterInsertHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, UserSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the User
func (o *User) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *User) pkEQ() dialect.Expression {
	return psql.Quote("users", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the User
func (o *User) Update(ctx context.Context, exec bob.Executor, s *UserSetter) error {
	v, err := Users.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single User record with an executor
func (o *User) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Users.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the User using the executor
func (o *User) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Users.Query(
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after UserSlice is retrieved from the database
func (o UserSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Users.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Users.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o UserSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("users", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o UserSlice) copyMatchingRows(from ...*User) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o UserSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Users.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *User:
				o.copyMatchingRows(retrieved)
			case []*User:
				o.copyMatchingRows(retrieved...)
			case UserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a User or a slice of User
				// then run the AfterUpdateHooks on the slice
				_, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o UserSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Users.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *User:
				o.copyMatchingRows(retrieved)
			case []*User:
				o.copyMatchingRows(retrieved...)
			case UserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a User or a slice of User
				// then run the AfterDeleteHooks on the slice
				_, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o UserSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals UserSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Users.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o UserSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Users.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o UserSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Users.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Addresses starts a query for related objects on addresses
func (o *User) Addresses(mods ...bob.Mod[*dialect.SelectQuery]) AddressesQuery {
	return Addresses.Query(append(mods,
		sm.Where(Addresses.Columns.UserID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserSlice) Addresses(mods ...bob.Mod[*dialect.SelectQuery]) AddressesQuery {
	pkID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "character varying[]")),
	))

	return Addresses.Query(append(mods,
		sm.Where(psql.Group(Addresses.Columns.UserID).OP("IN", PKArgExpr)),
	)...)
}

// Carts starts a query for related objects on carts
func (o *User) Carts(mods ...bob.Mod[*dialect.SelectQuery]) CartsQuery {
	return Carts.Query(append(mods,
		sm.Where(Carts.Columns.UserID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserSlice) Carts(mods ...bob.Mod[*dialect.SelectQuery]) CartsQuery {
	pkID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "character varying[]")),
	))

	return Carts.Query(append(mods,
		sm.Where(psql.Group(Carts.Columns.UserID).OP("IN", PKArgExpr)),
	)...)
}

// Orders starts a query for related objects on orders
func (o *User) Orders(mods ...bob.Mod[*dialect.SelectQuery]) OrdersQuery {
	return Orders.Query(append(mods,
		sm.Where(Orders.Columns.UserID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserSlice) Orders(mods ...bob.Mod[*dialect.SelectQuery]) OrdersQuery {
	pkID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "character varying[]")),
	))

	return Orders.Query(append(mods,
		sm.Where(psql.Group(Orders.Columns.UserID).OP("IN", PKArgExpr)),
	)...)
}

func insertUserAddresses0(ctx context.Context, exec bob.Executor, addresses1 []*AddressSetter, user0 *User) (AddressSlice, error) {
	for i := range addresses1 {
		addresses1[i].UserID = omit.From(user0.ID)
	}

	ret, err := Addresses.Insert(bob.ToMods(addresses1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserAddresses0: %w", err)
	}

	return ret, nil
}

func attachUserAddresses0(ctx context.Context, exec bob.Executor, count int, addresses1 AddressSlice, user0 *User) (AddressSlice, error) {
	setter := &AddressSetter{
		UserID: omit.From(user0.ID),
	}

	err := addresses1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserAddresses0: %w", err)
	}

	return addresses1, nil
}

func (user0 *User) InsertAddresses(ctx context.Context, exec bob.Executor, related ...*AddressSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	addresses1, err := insertUserAddresses0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.Addresses = append(user0.R.Addresses, addresses1...)

	for _, rel := range addresses1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachAddresses(ctx context.Context, exec bob.Executor, related ...*Address) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	addresses1 := AddressSlice(related)

	_, err = attachUserAddresses0(ctx, exec, len(related), addresses1, user0)
	if err != nil {
		return err
	}

	user0.R.Addresses = append(user0.R.Addresses, addresses1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}

func insertUserCarts0(ctx context.Context, exec bob.Executor, carts1 []*CartSetter, user0 *User) (CartSlice, error) {
	for i := range carts1 {
		carts1[i].UserID = omit.From(user0.ID)
	}

	ret, err := Carts.Insert(bob.ToMods(carts1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserCarts0: %w", err)
	}

	return ret, nil
}

func attachUserCarts0(ctx context.Context, exec bob.Executor, count int, carts1 CartSlice, user0 *User) (CartSlice, error) {
	setter := &CartSetter{
		UserID: omit.From(user0.ID),
	}

	err := carts1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserCarts0: %w", err)
	}

	return carts1, nil
}

func (user0 *User) InsertCarts(ctx context.Context, exec bob.Executor, related ...*CartSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	carts1, err := insertUserCarts0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.Carts = append(user0.R.Carts, carts1...)

	for _, rel := range carts1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachCarts(ctx context.Context, exec bob.Executor, related ...*Cart) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	carts1 := CartSlice(related)

	_, err = attachUserCarts0(ctx, exec, len(related), carts1, user0)
	if err != nil {
		return err
	}

	user0.R.Carts = append(user0.R.Carts, carts1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}

func insertUserOrders0(ctx context.Context, exec bob.Executor, orders1 []*OrderSetter, user0 *User) (OrderSlice, error) {
	for i := range orders1 {
		orders1[i].UserID = omit.From(user0.ID)
	}

	ret, err := Orders.Insert(bob.ToMods(orders1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserOrders0: %w", err)
	}

	return ret, nil
}

func attachUserOrders0(ctx context.Context, exec bob.Executor, count int, orders1 OrderSlice, user0 *User) (OrderSlice, error) {
	setter := &OrderSetter{
		UserID: omit.From(user0.ID),
	}

	err := orders1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserOrders0: %w", err)
	}

	return orders1, nil
}

func (user0 *User) InsertOrders(ctx context.Context, exec bob.Executor, related ...*OrderSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	orders1, err := insertUserOrders0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.Orders = append(user0.R.Orders, orders1...)

	for _, rel := range orders1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachOrders(ctx context.Context, exec bob.Executor, related ...*Order) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	orders1 := OrderSlice(related)

	_, err = attachUserOrders0(ctx, exec, len(related), orders1, user0)
	if err != nil {
		return err
	}

	user0.R.Orders = append(user0.R.Orders, orders1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}

type userWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, string]
	Name      psql.WhereMod[Q, string]
	Email     psql.WhereMod[Q, string]
	Password  psql.WhereMod[Q, string]
	Role      psql.WhereMod[Q, string]
	CreatedAt psql.WhereMod[Q, time.Time]
	UpdatedAt psql.WhereMod[Q, time.Time]
}

func (userWhere[Q]) AliasedAs(alias string) userWhere[Q] {
	return buildUserWhere[Q](buildUserColumns(alias))
}

func buildUserWhere[Q psql.Filterable](cols userColumns) userWhere[Q] {
	return userWhere[Q]{
		ID:        psql.Where[Q, string](cols.ID),
		Name:      psql.Where[Q, string](cols.Name),
		Email:     psql.Where[Q, string](cols.Email),
		Password:  psql.Where[Q, string](cols.Password),
		Role:      psql.Where[Q, string](cols.Role),
		CreatedAt: psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt: psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *User) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Addresses":
		rels, ok := retrieved.(AddressSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.Addresses = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	case "Carts":
		rels, ok := retrieved.(CartSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.Carts = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	case "Orders":
		rels, ok := retrieved.(OrderSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.Orders = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	default:
		return fmt.Errorf("user has no relationship %q", name)
	}
}

type userPreloader struct{}

func buildUserPreloader() userPreloader {
	return userPreloader{}
}

type userThenLoader[Q orm.Loadable] struct {
	Addresses func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Carts     func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Orders    func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildUserThenLoader[Q orm.Loadable]() userThenLoader[Q] {
	type AddressesLoadInterface interface {
		LoadAddresses(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type CartsLoadInterface interface {
		LoadCarts(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type OrdersLoadInterface interface {
		LoadOrders(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return userThenLoader[Q]{
		Addresses: thenLoadBuilder[Q](
			"Addresses",
			func(ctx context.Context, exec bob.Executor, retrieved AddressesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadAddresses(ctx, exec, mods...)
			},
		),
		Carts: thenLoadBuilder[Q](
			"Carts",
			func(ctx context.Context, exec bob.Executor, retrieved CartsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCarts(ctx, exec, mods...)
			},
		),
		Orders: thenLoadBuilder[Q](
			"Orders",
			func(ctx context.Context, exec bob.Executor, retrieved OrdersLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadOrders(ctx, exec, mods...)
			},
		),
	}
}

// LoadAddresses loads the user's Addresses into the .R struct
func (o *User) LoadAddresses(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Addresses = nil

	related, err := o.Addresses(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.Addresses = related
	return nil
}

// LoadAddresses loads the user's Addresses into the .R struct
func (os UserSlice) LoadAddresses(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	addresses, err := os.Addresses(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Addresses = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range addresses {

			if !(o.ID == rel.UserID) {
				continue
			}

			rel.R.User = o

			o.R.Addresses = append(o.R.Addresses, rel)
		}
	}

	return nil
}

// LoadCarts loads the user's Carts into the .R struct
func (o *User) LoadCarts(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Carts = nil

	related, err := o.Carts(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.Carts = related
	return nil
}

// LoadCarts loads the user's Carts into the .R struct
func (os UserSlice) LoadCarts(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	carts, err := os.Carts(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Carts = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range carts {

			if !(o.ID == rel.UserID) {
				continue
			}

			rel.R.User = o

			o.R.Carts = append(o.R.Carts, rel)
		}
	}

	return nil
}

// LoadOrders loads the user's Orders into the .R struct
func (o *User) LoadOrders(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Orders = nil

	related, err := o.Orders(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.Orders = related
	return nil
}

// LoadOrders loads the user's Orders into the .R struct
func (os UserSlice) LoadOrders(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	orders, err := os.Orders(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Orders = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range orders {

			if !(o.ID == rel.UserID) {
				continue
			}

			rel.R.User = o

			o.R.Orders = append(o.R.Orders, rel)
		}
	}

	return nil
}

type userJoins[Q dialect.Joinable] struct {
	typ       string
	Addresses modAs[Q, addressColumns]
	Carts     modAs[Q, cartColumns]
	Orders    modAs[Q, orderColumns]
}

func (j userJoins[Q]) aliasedAs(alias string) userJoins[Q] {
	return buildUserJoins[Q](buildUserColumns(alias), j.typ)
}

func buildUserJoins[Q dialect.Joinable](cols userColumns, typ string) userJoins[Q] {
	return userJoins[Q]{
		typ: typ,
		Addresses: modAs[Q, addressColumns]{
			c: Addresses.Columns,
			f: func(to addressColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Addresses.Name().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Carts: modAs[Q, cartColumns]{
			c: Carts.Columns,
			f: func(to cartColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Carts.Name().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Orders: modAs[Q, orderColumns]{
			c: Orders.Columns,
			f: func(to orderColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Orders.Name().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
