// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	models "github.com/shailendrapawar/book-store/internal/db/models"
	"github.com/stephenafamo/bob"
)

type AddressMod interface {
	Apply(context.Context, *AddressTemplate)
}

type AddressModFunc func(context.Context, *AddressTemplate)

func (f AddressModFunc) Apply(ctx context.Context, n *AddressTemplate) {
	f(ctx, n)
}

type AddressModSlice []AddressMod

func (mods AddressModSlice) Apply(ctx context.Context, n *AddressTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// AddressTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type AddressTemplate struct {
	ID            func() string
	UserID        func() string
	AddressesType func() string
	Line1         func() string
	Line2         func() null.Val[string]
	Landmark      func() null.Val[string]
	City          func() string
	Pincode       func() string
	District      func() string
	State         func() string
	Country       func() string
	IsDeleted     func() bool
	CreatedAt     func() time.Time
	UpdatedAt     func() time.Time

	r addressR
	f *Factory

	alreadyPersisted bool
}

type addressR struct {
	User *addressRUserR
}

type addressRUserR struct {
	o *UserTemplate
}

// Apply mods to the AddressTemplate
func (o *AddressTemplate) Apply(ctx context.Context, mods ...AddressMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Address
// according to the relationships in the template. Nothing is inserted into the db
func (t AddressTemplate) setModelRels(o *models.Address) {
	if t.r.User != nil {
		rel := t.r.User.o.Build()
		rel.R.Addresses = append(rel.R.Addresses, o)
		o.UserID = rel.ID // h2
		o.R.User = rel
	}
}

// BuildSetter returns an *models.AddressSetter
// this does nothing with the relationship templates
func (o AddressTemplate) BuildSetter() *models.AddressSetter {
	m := &models.AddressSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.UserID != nil {
		val := o.UserID()
		m.UserID = omit.From(val)
	}
	if o.AddressesType != nil {
		val := o.AddressesType()
		m.AddressesType = omit.From(val)
	}
	if o.Line1 != nil {
		val := o.Line1()
		m.Line1 = omit.From(val)
	}
	if o.Line2 != nil {
		val := o.Line2()
		m.Line2 = omitnull.FromNull(val)
	}
	if o.Landmark != nil {
		val := o.Landmark()
		m.Landmark = omitnull.FromNull(val)
	}
	if o.City != nil {
		val := o.City()
		m.City = omit.From(val)
	}
	if o.Pincode != nil {
		val := o.Pincode()
		m.Pincode = omit.From(val)
	}
	if o.District != nil {
		val := o.District()
		m.District = omit.From(val)
	}
	if o.State != nil {
		val := o.State()
		m.State = omit.From(val)
	}
	if o.Country != nil {
		val := o.Country()
		m.Country = omit.From(val)
	}
	if o.IsDeleted != nil {
		val := o.IsDeleted()
		m.IsDeleted = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.AddressSetter
// this does nothing with the relationship templates
func (o AddressTemplate) BuildManySetter(number int) []*models.AddressSetter {
	m := make([]*models.AddressSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Address
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use AddressTemplate.Create
func (o AddressTemplate) Build() *models.Address {
	m := &models.Address{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.UserID != nil {
		m.UserID = o.UserID()
	}
	if o.AddressesType != nil {
		m.AddressesType = o.AddressesType()
	}
	if o.Line1 != nil {
		m.Line1 = o.Line1()
	}
	if o.Line2 != nil {
		m.Line2 = o.Line2()
	}
	if o.Landmark != nil {
		m.Landmark = o.Landmark()
	}
	if o.City != nil {
		m.City = o.City()
	}
	if o.Pincode != nil {
		m.Pincode = o.Pincode()
	}
	if o.District != nil {
		m.District = o.District()
	}
	if o.State != nil {
		m.State = o.State()
	}
	if o.Country != nil {
		m.Country = o.Country()
	}
	if o.IsDeleted != nil {
		m.IsDeleted = o.IsDeleted()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.AddressSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use AddressTemplate.CreateMany
func (o AddressTemplate) BuildMany(number int) models.AddressSlice {
	m := make(models.AddressSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableAddress(m *models.AddressSetter) {
	if !(m.ID.IsValue()) {
		val := random_string(nil, "50")
		m.ID = omit.From(val)
	}
	if !(m.UserID.IsValue()) {
		val := random_string(nil, "50")
		m.UserID = omit.From(val)
	}
	if !(m.AddressesType.IsValue()) {
		val := random_string(nil, "255")
		m.AddressesType = omit.From(val)
	}
	if !(m.Line1.IsValue()) {
		val := random_string(nil, "255")
		m.Line1 = omit.From(val)
	}
	if !(m.City.IsValue()) {
		val := random_string(nil, "255")
		m.City = omit.From(val)
	}
	if !(m.Pincode.IsValue()) {
		val := random_string(nil, "10")
		m.Pincode = omit.From(val)
	}
	if !(m.District.IsValue()) {
		val := random_string(nil, "255")
		m.District = omit.From(val)
	}
	if !(m.State.IsValue()) {
		val := random_string(nil, "255")
		m.State = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Address
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *AddressTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Address) error {
	var err error

	return err
}

// Create builds a address and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *AddressTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Address, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableAddress(opt)

	if o.r.User == nil {
		AddressMods.WithNewUser().Apply(ctx, o)
	}

	var rel0 *models.User

	if o.r.User.o.alreadyPersisted {
		rel0 = o.r.User.o.Build()
	} else {
		rel0, err = o.r.User.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.UserID = omit.From(rel0.ID)

	m, err := models.Addresses.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.User = rel0

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a address and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *AddressTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Address {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a address and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *AddressTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Address {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple addresses and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o AddressTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.AddressSlice, error) {
	var err error
	m := make(models.AddressSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple addresses and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o AddressTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.AddressSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple addresses and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o AddressTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.AddressSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Address has methods that act as mods for the AddressTemplate
var AddressMods addressMods

type addressMods struct{}

func (m addressMods) RandomizeAllColumns(f *faker.Faker) AddressMod {
	return AddressModSlice{
		AddressMods.RandomID(f),
		AddressMods.RandomUserID(f),
		AddressMods.RandomAddressesType(f),
		AddressMods.RandomLine1(f),
		AddressMods.RandomLine2(f),
		AddressMods.RandomLandmark(f),
		AddressMods.RandomCity(f),
		AddressMods.RandomPincode(f),
		AddressMods.RandomDistrict(f),
		AddressMods.RandomState(f),
		AddressMods.RandomCountry(f),
		AddressMods.RandomIsDeleted(f),
		AddressMods.RandomCreatedAt(f),
		AddressMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m addressMods) ID(val string) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m addressMods) IDFunc(f func() string) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m addressMods) UnsetID() AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m addressMods) RandomID(f *faker.Faker) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.ID = func() string {
			return random_string(f, "50")
		}
	})
}

// Set the model columns to this value
func (m addressMods) UserID(val string) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.UserID = func() string { return val }
	})
}

// Set the Column from the function
func (m addressMods) UserIDFunc(f func() string) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.UserID = f
	})
}

// Clear any values for the column
func (m addressMods) UnsetUserID() AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.UserID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m addressMods) RandomUserID(f *faker.Faker) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.UserID = func() string {
			return random_string(f, "50")
		}
	})
}

// Set the model columns to this value
func (m addressMods) AddressesType(val string) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.AddressesType = func() string { return val }
	})
}

// Set the Column from the function
func (m addressMods) AddressesTypeFunc(f func() string) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.AddressesType = f
	})
}

// Clear any values for the column
func (m addressMods) UnsetAddressesType() AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.AddressesType = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m addressMods) RandomAddressesType(f *faker.Faker) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.AddressesType = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m addressMods) Line1(val string) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.Line1 = func() string { return val }
	})
}

// Set the Column from the function
func (m addressMods) Line1Func(f func() string) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.Line1 = f
	})
}

// Clear any values for the column
func (m addressMods) UnsetLine1() AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.Line1 = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m addressMods) RandomLine1(f *faker.Faker) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.Line1 = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m addressMods) Line2(val null.Val[string]) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.Line2 = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m addressMods) Line2Func(f func() null.Val[string]) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.Line2 = f
	})
}

// Clear any values for the column
func (m addressMods) UnsetLine2() AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.Line2 = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m addressMods) RandomLine2(f *faker.Faker) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.Line2 = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "255")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m addressMods) RandomLine2NotNull(f *faker.Faker) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.Line2 = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "255")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m addressMods) Landmark(val null.Val[string]) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.Landmark = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m addressMods) LandmarkFunc(f func() null.Val[string]) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.Landmark = f
	})
}

// Clear any values for the column
func (m addressMods) UnsetLandmark() AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.Landmark = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m addressMods) RandomLandmark(f *faker.Faker) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.Landmark = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "255")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m addressMods) RandomLandmarkNotNull(f *faker.Faker) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.Landmark = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "255")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m addressMods) City(val string) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.City = func() string { return val }
	})
}

// Set the Column from the function
func (m addressMods) CityFunc(f func() string) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.City = f
	})
}

// Clear any values for the column
func (m addressMods) UnsetCity() AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.City = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m addressMods) RandomCity(f *faker.Faker) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.City = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m addressMods) Pincode(val string) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.Pincode = func() string { return val }
	})
}

// Set the Column from the function
func (m addressMods) PincodeFunc(f func() string) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.Pincode = f
	})
}

// Clear any values for the column
func (m addressMods) UnsetPincode() AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.Pincode = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m addressMods) RandomPincode(f *faker.Faker) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.Pincode = func() string {
			return random_string(f, "10")
		}
	})
}

// Set the model columns to this value
func (m addressMods) District(val string) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.District = func() string { return val }
	})
}

// Set the Column from the function
func (m addressMods) DistrictFunc(f func() string) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.District = f
	})
}

// Clear any values for the column
func (m addressMods) UnsetDistrict() AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.District = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m addressMods) RandomDistrict(f *faker.Faker) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.District = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m addressMods) State(val string) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.State = func() string { return val }
	})
}

// Set the Column from the function
func (m addressMods) StateFunc(f func() string) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.State = f
	})
}

// Clear any values for the column
func (m addressMods) UnsetState() AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.State = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m addressMods) RandomState(f *faker.Faker) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.State = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m addressMods) Country(val string) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.Country = func() string { return val }
	})
}

// Set the Column from the function
func (m addressMods) CountryFunc(f func() string) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.Country = f
	})
}

// Clear any values for the column
func (m addressMods) UnsetCountry() AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.Country = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m addressMods) RandomCountry(f *faker.Faker) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.Country = func() string {
			return random_string(f, "100")
		}
	})
}

// Set the model columns to this value
func (m addressMods) IsDeleted(val bool) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.IsDeleted = func() bool { return val }
	})
}

// Set the Column from the function
func (m addressMods) IsDeletedFunc(f func() bool) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.IsDeleted = f
	})
}

// Clear any values for the column
func (m addressMods) UnsetIsDeleted() AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.IsDeleted = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m addressMods) RandomIsDeleted(f *faker.Faker) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.IsDeleted = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m addressMods) CreatedAt(val time.Time) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m addressMods) CreatedAtFunc(f func() time.Time) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m addressMods) UnsetCreatedAt() AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m addressMods) RandomCreatedAt(f *faker.Faker) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m addressMods) UpdatedAt(val time.Time) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m addressMods) UpdatedAtFunc(f func() time.Time) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m addressMods) UnsetUpdatedAt() AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m addressMods) RandomUpdatedAt(f *faker.Faker) AddressMod {
	return AddressModFunc(func(_ context.Context, o *AddressTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m addressMods) WithParentsCascading() AddressMod {
	return AddressModFunc(func(ctx context.Context, o *AddressTemplate) {
		if isDone, _ := addressWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = addressWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithUser(related).Apply(ctx, o)
		}
	})
}

func (m addressMods) WithUser(rel *UserTemplate) AddressMod {
	return AddressModFunc(func(ctx context.Context, o *AddressTemplate) {
		o.r.User = &addressRUserR{
			o: rel,
		}
	})
}

func (m addressMods) WithNewUser(mods ...UserMod) AddressMod {
	return AddressModFunc(func(ctx context.Context, o *AddressTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithUser(related).Apply(ctx, o)
	})
}

func (m addressMods) WithExistingUser(em *models.User) AddressMod {
	return AddressModFunc(func(ctx context.Context, o *AddressTemplate) {
		o.r.User = &addressRUserR{
			o: o.f.FromExistingUser(em),
		}
	})
}

func (m addressMods) WithoutUser() AddressMod {
	return AddressModFunc(func(ctx context.Context, o *AddressTemplate) {
		o.r.User = nil
	})
}
