// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"time"

	"github.com/aarondl/opt/null"
	models "github.com/shailendrapawar/book-store/internal/db/models"
	"github.com/shopspring/decimal"
)

type Factory struct {
	baseAddressMods  AddressModSlice
	baseBookMods     BookModSlice
	baseCartItemMods CartItemModSlice
	baseCartMods     CartModSlice
	baseOrderMods    OrderModSlice
	baseUserMods     UserModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewAddress(mods ...AddressMod) *AddressTemplate {
	return f.NewAddressWithContext(context.Background(), mods...)
}

func (f *Factory) NewAddressWithContext(ctx context.Context, mods ...AddressMod) *AddressTemplate {
	o := &AddressTemplate{f: f}

	if f != nil {
		f.baseAddressMods.Apply(ctx, o)
	}

	AddressModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingAddress(m *models.Address) *AddressTemplate {
	o := &AddressTemplate{f: f, alreadyPersisted: true}

	o.ID = func() string { return m.ID }
	o.UserID = func() string { return m.UserID }
	o.AddressesType = func() string { return m.AddressesType }
	o.Line1 = func() string { return m.Line1 }
	o.Line2 = func() null.Val[string] { return m.Line2 }
	o.Landmark = func() null.Val[string] { return m.Landmark }
	o.City = func() string { return m.City }
	o.Pincode = func() string { return m.Pincode }
	o.District = func() string { return m.District }
	o.State = func() string { return m.State }
	o.Country = func() string { return m.Country }
	o.IsDefault = func() bool { return m.IsDefault }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }

	ctx := context.Background()
	if m.R.User != nil {
		AddressMods.WithExistingUser(m.R.User).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewBook(mods ...BookMod) *BookTemplate {
	return f.NewBookWithContext(context.Background(), mods...)
}

func (f *Factory) NewBookWithContext(ctx context.Context, mods ...BookMod) *BookTemplate {
	o := &BookTemplate{f: f}

	if f != nil {
		f.baseBookMods.Apply(ctx, o)
	}

	BookModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingBook(m *models.Book) *BookTemplate {
	o := &BookTemplate{f: f, alreadyPersisted: true}

	o.ID = func() string { return m.ID }
	o.Isbn = func() string { return m.Isbn }
	o.Title = func() string { return m.Title }
	o.Author = func() string { return m.Author }
	o.Description = func() null.Val[string] { return m.Description }
	o.Price = func() decimal.Decimal { return m.Price }
	o.Stock = func() int32 { return m.Stock }
	o.Reserved = func() int32 { return m.Reserved }
	o.IsActive = func() bool { return m.IsActive }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }

	ctx := context.Background()
	if len(m.R.CartItems) > 0 {
		BookMods.AddExistingCartItems(m.R.CartItems...).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewCartItem(mods ...CartItemMod) *CartItemTemplate {
	return f.NewCartItemWithContext(context.Background(), mods...)
}

func (f *Factory) NewCartItemWithContext(ctx context.Context, mods ...CartItemMod) *CartItemTemplate {
	o := &CartItemTemplate{f: f}

	if f != nil {
		f.baseCartItemMods.Apply(ctx, o)
	}

	CartItemModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingCartItem(m *models.CartItem) *CartItemTemplate {
	o := &CartItemTemplate{f: f, alreadyPersisted: true}

	o.ID = func() string { return m.ID }
	o.CartID = func() string { return m.CartID }
	o.BookID = func() string { return m.BookID }
	o.Quantity = func() int32 { return m.Quantity }
	o.Price = func() decimal.Decimal { return m.Price }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }

	ctx := context.Background()
	if m.R.Book != nil {
		CartItemMods.WithExistingBook(m.R.Book).Apply(ctx, o)
	}
	if m.R.Cart != nil {
		CartItemMods.WithExistingCart(m.R.Cart).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewCart(mods ...CartMod) *CartTemplate {
	return f.NewCartWithContext(context.Background(), mods...)
}

func (f *Factory) NewCartWithContext(ctx context.Context, mods ...CartMod) *CartTemplate {
	o := &CartTemplate{f: f}

	if f != nil {
		f.baseCartMods.Apply(ctx, o)
	}

	CartModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingCart(m *models.Cart) *CartTemplate {
	o := &CartTemplate{f: f, alreadyPersisted: true}

	o.ID = func() string { return m.ID }
	o.UserID = func() string { return m.UserID }
	o.Status = func() string { return m.Status }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }

	ctx := context.Background()
	if len(m.R.CartItems) > 0 {
		CartMods.AddExistingCartItems(m.R.CartItems...).Apply(ctx, o)
	}
	if m.R.User != nil {
		CartMods.WithExistingUser(m.R.User).Apply(ctx, o)
	}
	if len(m.R.Orders) > 0 {
		CartMods.AddExistingOrders(m.R.Orders...).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewOrder(mods ...OrderMod) *OrderTemplate {
	return f.NewOrderWithContext(context.Background(), mods...)
}

func (f *Factory) NewOrderWithContext(ctx context.Context, mods ...OrderMod) *OrderTemplate {
	o := &OrderTemplate{f: f}

	if f != nil {
		f.baseOrderMods.Apply(ctx, o)
	}

	OrderModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingOrder(m *models.Order) *OrderTemplate {
	o := &OrderTemplate{f: f, alreadyPersisted: true}

	o.ID = func() string { return m.ID }
	o.UserID = func() string { return m.UserID }
	o.CartID = func() string { return m.CartID }
	o.Amount = func() decimal.Decimal { return m.Amount }
	o.DelieveryAddress = func() string { return m.DelieveryAddress }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }

	ctx := context.Background()
	if m.R.Cart != nil {
		OrderMods.WithExistingCart(m.R.Cart).Apply(ctx, o)
	}
	if m.R.User != nil {
		OrderMods.WithExistingUser(m.R.User).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewUser(mods ...UserMod) *UserTemplate {
	return f.NewUserWithContext(context.Background(), mods...)
}

func (f *Factory) NewUserWithContext(ctx context.Context, mods ...UserMod) *UserTemplate {
	o := &UserTemplate{f: f}

	if f != nil {
		f.baseUserMods.Apply(ctx, o)
	}

	UserModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingUser(m *models.User) *UserTemplate {
	o := &UserTemplate{f: f, alreadyPersisted: true}

	o.ID = func() string { return m.ID }
	o.Name = func() string { return m.Name }
	o.Email = func() string { return m.Email }
	o.Password = func() string { return m.Password }
	o.Role = func() string { return m.Role }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }

	ctx := context.Background()
	if len(m.R.Addresses) > 0 {
		UserMods.AddExistingAddresses(m.R.Addresses...).Apply(ctx, o)
	}
	if len(m.R.Carts) > 0 {
		UserMods.AddExistingCarts(m.R.Carts...).Apply(ctx, o)
	}
	if len(m.R.Orders) > 0 {
		UserMods.AddExistingOrders(m.R.Orders...).Apply(ctx, o)
	}

	return o
}

func (f *Factory) ClearBaseAddressMods() {
	f.baseAddressMods = nil
}

func (f *Factory) AddBaseAddressMod(mods ...AddressMod) {
	f.baseAddressMods = append(f.baseAddressMods, mods...)
}

func (f *Factory) ClearBaseBookMods() {
	f.baseBookMods = nil
}

func (f *Factory) AddBaseBookMod(mods ...BookMod) {
	f.baseBookMods = append(f.baseBookMods, mods...)
}

func (f *Factory) ClearBaseCartItemMods() {
	f.baseCartItemMods = nil
}

func (f *Factory) AddBaseCartItemMod(mods ...CartItemMod) {
	f.baseCartItemMods = append(f.baseCartItemMods, mods...)
}

func (f *Factory) ClearBaseCartMods() {
	f.baseCartMods = nil
}

func (f *Factory) AddBaseCartMod(mods ...CartMod) {
	f.baseCartMods = append(f.baseCartMods, mods...)
}

func (f *Factory) ClearBaseOrderMods() {
	f.baseOrderMods = nil
}

func (f *Factory) AddBaseOrderMod(mods ...OrderMod) {
	f.baseOrderMods = append(f.baseOrderMods, mods...)
}

func (f *Factory) ClearBaseUserMods() {
	f.baseUserMods = nil
}

func (f *Factory) AddBaseUserMod(mods ...UserMod) {
	f.baseUserMods = append(f.baseUserMods, mods...)
}
