// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import "context"

type contextKey string

var (
	// Relationship Contexts for addresses
	addressWithParentsCascadingCtx = newContextual[bool]("addressWithParentsCascading")
	addressRelUserCtx              = newContextual[bool]("addresses.users.addresses.addresses_user_id_fkey")

	// Relationship Contexts for books
	bookWithParentsCascadingCtx = newContextual[bool]("bookWithParentsCascading")
	bookRelCartItemsCtx         = newContextual[bool]("books.cart_items.cart_items.cart_items_book_id_fkey")
	bookRelOrderItemsCtx        = newContextual[bool]("books.order_items.order_items.order_items_book_id_fkey")

	// Relationship Contexts for cart_items
	cartItemWithParentsCascadingCtx = newContextual[bool]("cartItemWithParentsCascading")
	cartItemRelBookCtx              = newContextual[bool]("books.cart_items.cart_items.cart_items_book_id_fkey")
	cartItemRelCartCtx              = newContextual[bool]("cart_items.carts.cart_items.cart_items_cart_id_fkey")

	// Relationship Contexts for carts
	cartWithParentsCascadingCtx = newContextual[bool]("cartWithParentsCascading")
	cartRelCartItemsCtx         = newContextual[bool]("cart_items.carts.cart_items.cart_items_cart_id_fkey")
	cartRelUserCtx              = newContextual[bool]("carts.users.carts.carts_user_id_fkey")

	// Relationship Contexts for order_items
	orderItemWithParentsCascadingCtx = newContextual[bool]("orderItemWithParentsCascading")
	orderItemRelBookCtx              = newContextual[bool]("books.order_items.order_items.order_items_book_id_fkey")
	orderItemRelOrderCtx             = newContextual[bool]("order_items.orders.order_items.order_items_order_id_fkey")

	// Relationship Contexts for orders
	orderWithParentsCascadingCtx = newContextual[bool]("orderWithParentsCascading")
	orderRelOrderItemsCtx        = newContextual[bool]("order_items.orders.order_items.order_items_order_id_fkey")
	orderRelUserCtx              = newContextual[bool]("orders.users.orders.orders_user_id_fkey")

	// Relationship Contexts for users
	userWithParentsCascadingCtx = newContextual[bool]("userWithParentsCascading")
	userRelAddressesCtx         = newContextual[bool]("addresses.users.addresses.addresses_user_id_fkey")
	userRelCartsCtx             = newContextual[bool]("carts.users.carts.carts_user_id_fkey")
	userRelOrdersCtx            = newContextual[bool]("orders.users.orders.orders_user_id_fkey")
)

// Contextual is a convienience wrapper around context.WithValue and context.Value
type contextual[V any] struct {
	key contextKey
}

func newContextual[V any](key string) contextual[V] {
	return contextual[V]{key: contextKey(key)}
}

func (k contextual[V]) WithValue(ctx context.Context, val V) context.Context {
	return context.WithValue(ctx, k.key, val)
}

func (k contextual[V]) Value(ctx context.Context) (V, bool) {
	v, ok := ctx.Value(k.key).(V)
	return v, ok
}
