// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	models "github.com/shailendrapawar/book-store/internal/db/models"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
)

type BookMod interface {
	Apply(context.Context, *BookTemplate)
}

type BookModFunc func(context.Context, *BookTemplate)

func (f BookModFunc) Apply(ctx context.Context, n *BookTemplate) {
	f(ctx, n)
}

type BookModSlice []BookMod

func (mods BookModSlice) Apply(ctx context.Context, n *BookTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// BookTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type BookTemplate struct {
	ID          func() string
	Isbn        func() string
	Title       func() string
	Author      func() string
	Description func() null.Val[string]
	Price       func() decimal.Decimal
	Stock       func() int32
	Reserved    func() int32
	IsActive    func() bool
	CreatedAt   func() time.Time
	UpdatedAt   func() time.Time

	r bookR
	f *Factory

	alreadyPersisted bool
}

type bookR struct {
	CartItems  []*bookRCartItemsR
	OrderItems []*bookROrderItemsR
}

type bookRCartItemsR struct {
	number int
	o      *CartItemTemplate
}
type bookROrderItemsR struct {
	number int
	o      *OrderItemTemplate
}

// Apply mods to the BookTemplate
func (o *BookTemplate) Apply(ctx context.Context, mods ...BookMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Book
// according to the relationships in the template. Nothing is inserted into the db
func (t BookTemplate) setModelRels(o *models.Book) {
	if t.r.CartItems != nil {
		rel := models.CartItemSlice{}
		for _, r := range t.r.CartItems {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.BookID = o.ID // h2
				rel.R.Book = o
			}
			rel = append(rel, related...)
		}
		o.R.CartItems = rel
	}

	if t.r.OrderItems != nil {
		rel := models.OrderItemSlice{}
		for _, r := range t.r.OrderItems {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.BookID = o.ID // h2
				rel.R.Book = o
			}
			rel = append(rel, related...)
		}
		o.R.OrderItems = rel
	}
}

// BuildSetter returns an *models.BookSetter
// this does nothing with the relationship templates
func (o BookTemplate) BuildSetter() *models.BookSetter {
	m := &models.BookSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Isbn != nil {
		val := o.Isbn()
		m.Isbn = omit.From(val)
	}
	if o.Title != nil {
		val := o.Title()
		m.Title = omit.From(val)
	}
	if o.Author != nil {
		val := o.Author()
		m.Author = omit.From(val)
	}
	if o.Description != nil {
		val := o.Description()
		m.Description = omitnull.FromNull(val)
	}
	if o.Price != nil {
		val := o.Price()
		m.Price = omit.From(val)
	}
	if o.Stock != nil {
		val := o.Stock()
		m.Stock = omit.From(val)
	}
	if o.Reserved != nil {
		val := o.Reserved()
		m.Reserved = omit.From(val)
	}
	if o.IsActive != nil {
		val := o.IsActive()
		m.IsActive = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.BookSetter
// this does nothing with the relationship templates
func (o BookTemplate) BuildManySetter(number int) []*models.BookSetter {
	m := make([]*models.BookSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Book
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use BookTemplate.Create
func (o BookTemplate) Build() *models.Book {
	m := &models.Book{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Isbn != nil {
		m.Isbn = o.Isbn()
	}
	if o.Title != nil {
		m.Title = o.Title()
	}
	if o.Author != nil {
		m.Author = o.Author()
	}
	if o.Description != nil {
		m.Description = o.Description()
	}
	if o.Price != nil {
		m.Price = o.Price()
	}
	if o.Stock != nil {
		m.Stock = o.Stock()
	}
	if o.Reserved != nil {
		m.Reserved = o.Reserved()
	}
	if o.IsActive != nil {
		m.IsActive = o.IsActive()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.BookSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use BookTemplate.CreateMany
func (o BookTemplate) BuildMany(number int) models.BookSlice {
	m := make(models.BookSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableBook(m *models.BookSetter) {
	if !(m.ID.IsValue()) {
		val := random_string(nil, "50")
		m.ID = omit.From(val)
	}
	if !(m.Isbn.IsValue()) {
		val := random_string(nil, "20")
		m.Isbn = omit.From(val)
	}
	if !(m.Title.IsValue()) {
		val := random_string(nil, "255")
		m.Title = omit.From(val)
	}
	if !(m.Author.IsValue()) {
		val := random_string(nil, "255")
		m.Author = omit.From(val)
	}
	if !(m.Price.IsValue()) {
		val := random_decimal_Decimal(nil, "10", "2")
		m.Price = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Book
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *BookTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Book) error {
	var err error

	isCartItemsDone, _ := bookRelCartItemsCtx.Value(ctx)
	if !isCartItemsDone && o.r.CartItems != nil {
		ctx = bookRelCartItemsCtx.WithValue(ctx, true)
		for _, r := range o.r.CartItems {
			if r.o.alreadyPersisted {
				m.R.CartItems = append(m.R.CartItems, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachCartItems(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	isOrderItemsDone, _ := bookRelOrderItemsCtx.Value(ctx)
	if !isOrderItemsDone && o.r.OrderItems != nil {
		ctx = bookRelOrderItemsCtx.WithValue(ctx, true)
		for _, r := range o.r.OrderItems {
			if r.o.alreadyPersisted {
				m.R.OrderItems = append(m.R.OrderItems, r.o.Build())
			} else {
				rel1, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachOrderItems(ctx, exec, rel1...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a book and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *BookTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Book, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableBook(opt)

	m, err := models.Books.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a book and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *BookTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Book {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a book and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *BookTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Book {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple books and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o BookTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.BookSlice, error) {
	var err error
	m := make(models.BookSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple books and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o BookTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.BookSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple books and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o BookTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.BookSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Book has methods that act as mods for the BookTemplate
var BookMods bookMods

type bookMods struct{}

func (m bookMods) RandomizeAllColumns(f *faker.Faker) BookMod {
	return BookModSlice{
		BookMods.RandomID(f),
		BookMods.RandomIsbn(f),
		BookMods.RandomTitle(f),
		BookMods.RandomAuthor(f),
		BookMods.RandomDescription(f),
		BookMods.RandomPrice(f),
		BookMods.RandomStock(f),
		BookMods.RandomReserved(f),
		BookMods.RandomIsActive(f),
		BookMods.RandomCreatedAt(f),
		BookMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m bookMods) ID(val string) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m bookMods) IDFunc(f func() string) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m bookMods) UnsetID() BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m bookMods) RandomID(f *faker.Faker) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.ID = func() string {
			return random_string(f, "50")
		}
	})
}

// Set the model columns to this value
func (m bookMods) Isbn(val string) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.Isbn = func() string { return val }
	})
}

// Set the Column from the function
func (m bookMods) IsbnFunc(f func() string) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.Isbn = f
	})
}

// Clear any values for the column
func (m bookMods) UnsetIsbn() BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.Isbn = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m bookMods) RandomIsbn(f *faker.Faker) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.Isbn = func() string {
			return random_string(f, "20")
		}
	})
}

// Set the model columns to this value
func (m bookMods) Title(val string) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.Title = func() string { return val }
	})
}

// Set the Column from the function
func (m bookMods) TitleFunc(f func() string) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.Title = f
	})
}

// Clear any values for the column
func (m bookMods) UnsetTitle() BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.Title = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m bookMods) RandomTitle(f *faker.Faker) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.Title = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m bookMods) Author(val string) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.Author = func() string { return val }
	})
}

// Set the Column from the function
func (m bookMods) AuthorFunc(f func() string) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.Author = f
	})
}

// Clear any values for the column
func (m bookMods) UnsetAuthor() BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.Author = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m bookMods) RandomAuthor(f *faker.Faker) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.Author = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m bookMods) Description(val null.Val[string]) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.Description = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m bookMods) DescriptionFunc(f func() null.Val[string]) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.Description = f
	})
}

// Clear any values for the column
func (m bookMods) UnsetDescription() BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.Description = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m bookMods) RandomDescription(f *faker.Faker) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.Description = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m bookMods) RandomDescriptionNotNull(f *faker.Faker) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.Description = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m bookMods) Price(val decimal.Decimal) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.Price = func() decimal.Decimal { return val }
	})
}

// Set the Column from the function
func (m bookMods) PriceFunc(f func() decimal.Decimal) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.Price = f
	})
}

// Clear any values for the column
func (m bookMods) UnsetPrice() BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.Price = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m bookMods) RandomPrice(f *faker.Faker) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.Price = func() decimal.Decimal {
			return random_decimal_Decimal(f, "10", "2")
		}
	})
}

// Set the model columns to this value
func (m bookMods) Stock(val int32) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.Stock = func() int32 { return val }
	})
}

// Set the Column from the function
func (m bookMods) StockFunc(f func() int32) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.Stock = f
	})
}

// Clear any values for the column
func (m bookMods) UnsetStock() BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.Stock = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m bookMods) RandomStock(f *faker.Faker) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.Stock = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m bookMods) Reserved(val int32) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.Reserved = func() int32 { return val }
	})
}

// Set the Column from the function
func (m bookMods) ReservedFunc(f func() int32) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.Reserved = f
	})
}

// Clear any values for the column
func (m bookMods) UnsetReserved() BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.Reserved = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m bookMods) RandomReserved(f *faker.Faker) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.Reserved = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m bookMods) IsActive(val bool) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.IsActive = func() bool { return val }
	})
}

// Set the Column from the function
func (m bookMods) IsActiveFunc(f func() bool) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.IsActive = f
	})
}

// Clear any values for the column
func (m bookMods) UnsetIsActive() BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.IsActive = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m bookMods) RandomIsActive(f *faker.Faker) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.IsActive = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m bookMods) CreatedAt(val time.Time) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m bookMods) CreatedAtFunc(f func() time.Time) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m bookMods) UnsetCreatedAt() BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m bookMods) RandomCreatedAt(f *faker.Faker) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m bookMods) UpdatedAt(val time.Time) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m bookMods) UpdatedAtFunc(f func() time.Time) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m bookMods) UnsetUpdatedAt() BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m bookMods) RandomUpdatedAt(f *faker.Faker) BookMod {
	return BookModFunc(func(_ context.Context, o *BookTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m bookMods) WithParentsCascading() BookMod {
	return BookModFunc(func(ctx context.Context, o *BookTemplate) {
		if isDone, _ := bookWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = bookWithParentsCascadingCtx.WithValue(ctx, true)
	})
}

func (m bookMods) WithCartItems(number int, related *CartItemTemplate) BookMod {
	return BookModFunc(func(ctx context.Context, o *BookTemplate) {
		o.r.CartItems = []*bookRCartItemsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m bookMods) WithNewCartItems(number int, mods ...CartItemMod) BookMod {
	return BookModFunc(func(ctx context.Context, o *BookTemplate) {
		related := o.f.NewCartItemWithContext(ctx, mods...)
		m.WithCartItems(number, related).Apply(ctx, o)
	})
}

func (m bookMods) AddCartItems(number int, related *CartItemTemplate) BookMod {
	return BookModFunc(func(ctx context.Context, o *BookTemplate) {
		o.r.CartItems = append(o.r.CartItems, &bookRCartItemsR{
			number: number,
			o:      related,
		})
	})
}

func (m bookMods) AddNewCartItems(number int, mods ...CartItemMod) BookMod {
	return BookModFunc(func(ctx context.Context, o *BookTemplate) {
		related := o.f.NewCartItemWithContext(ctx, mods...)
		m.AddCartItems(number, related).Apply(ctx, o)
	})
}

func (m bookMods) AddExistingCartItems(existingModels ...*models.CartItem) BookMod {
	return BookModFunc(func(ctx context.Context, o *BookTemplate) {
		for _, em := range existingModels {
			o.r.CartItems = append(o.r.CartItems, &bookRCartItemsR{
				o: o.f.FromExistingCartItem(em),
			})
		}
	})
}

func (m bookMods) WithoutCartItems() BookMod {
	return BookModFunc(func(ctx context.Context, o *BookTemplate) {
		o.r.CartItems = nil
	})
}

func (m bookMods) WithOrderItems(number int, related *OrderItemTemplate) BookMod {
	return BookModFunc(func(ctx context.Context, o *BookTemplate) {
		o.r.OrderItems = []*bookROrderItemsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m bookMods) WithNewOrderItems(number int, mods ...OrderItemMod) BookMod {
	return BookModFunc(func(ctx context.Context, o *BookTemplate) {
		related := o.f.NewOrderItemWithContext(ctx, mods...)
		m.WithOrderItems(number, related).Apply(ctx, o)
	})
}

func (m bookMods) AddOrderItems(number int, related *OrderItemTemplate) BookMod {
	return BookModFunc(func(ctx context.Context, o *BookTemplate) {
		o.r.OrderItems = append(o.r.OrderItems, &bookROrderItemsR{
			number: number,
			o:      related,
		})
	})
}

func (m bookMods) AddNewOrderItems(number int, mods ...OrderItemMod) BookMod {
	return BookModFunc(func(ctx context.Context, o *BookTemplate) {
		related := o.f.NewOrderItemWithContext(ctx, mods...)
		m.AddOrderItems(number, related).Apply(ctx, o)
	})
}

func (m bookMods) AddExistingOrderItems(existingModels ...*models.OrderItem) BookMod {
	return BookModFunc(func(ctx context.Context, o *BookTemplate) {
		for _, em := range existingModels {
			o.r.OrderItems = append(o.r.OrderItems, &bookROrderItemsR{
				o: o.f.FromExistingOrderItem(em),
			})
		}
	})
}

func (m bookMods) WithoutOrderItems() BookMod {
	return BookModFunc(func(ctx context.Context, o *BookTemplate) {
		o.r.OrderItems = nil
	})
}
