// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker/v2"
	models "github.com/shailendrapawar/book-store/internal/db/models"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
)

type CartItemMod interface {
	Apply(context.Context, *CartItemTemplate)
}

type CartItemModFunc func(context.Context, *CartItemTemplate)

func (f CartItemModFunc) Apply(ctx context.Context, n *CartItemTemplate) {
	f(ctx, n)
}

type CartItemModSlice []CartItemMod

func (mods CartItemModSlice) Apply(ctx context.Context, n *CartItemTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// CartItemTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type CartItemTemplate struct {
	ID        func() string
	CartID    func() string
	BookID    func() string
	Quantity  func() int32
	Price     func() decimal.Decimal
	CreatedAt func() time.Time
	UpdatedAt func() time.Time

	r cartItemR
	f *Factory

	alreadyPersisted bool
}

type cartItemR struct {
	Book *cartItemRBookR
	Cart *cartItemRCartR
}

type cartItemRBookR struct {
	o *BookTemplate
}
type cartItemRCartR struct {
	o *CartTemplate
}

// Apply mods to the CartItemTemplate
func (o *CartItemTemplate) Apply(ctx context.Context, mods ...CartItemMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.CartItem
// according to the relationships in the template. Nothing is inserted into the db
func (t CartItemTemplate) setModelRels(o *models.CartItem) {
	if t.r.Book != nil {
		rel := t.r.Book.o.Build()
		rel.R.CartItems = append(rel.R.CartItems, o)
		o.BookID = rel.ID // h2
		o.R.Book = rel
	}

	if t.r.Cart != nil {
		rel := t.r.Cart.o.Build()
		rel.R.CartItems = append(rel.R.CartItems, o)
		o.CartID = rel.ID // h2
		o.R.Cart = rel
	}
}

// BuildSetter returns an *models.CartItemSetter
// this does nothing with the relationship templates
func (o CartItemTemplate) BuildSetter() *models.CartItemSetter {
	m := &models.CartItemSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.CartID != nil {
		val := o.CartID()
		m.CartID = omit.From(val)
	}
	if o.BookID != nil {
		val := o.BookID()
		m.BookID = omit.From(val)
	}
	if o.Quantity != nil {
		val := o.Quantity()
		m.Quantity = omit.From(val)
	}
	if o.Price != nil {
		val := o.Price()
		m.Price = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.CartItemSetter
// this does nothing with the relationship templates
func (o CartItemTemplate) BuildManySetter(number int) []*models.CartItemSetter {
	m := make([]*models.CartItemSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.CartItem
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use CartItemTemplate.Create
func (o CartItemTemplate) Build() *models.CartItem {
	m := &models.CartItem{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.CartID != nil {
		m.CartID = o.CartID()
	}
	if o.BookID != nil {
		m.BookID = o.BookID()
	}
	if o.Quantity != nil {
		m.Quantity = o.Quantity()
	}
	if o.Price != nil {
		m.Price = o.Price()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.CartItemSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use CartItemTemplate.CreateMany
func (o CartItemTemplate) BuildMany(number int) models.CartItemSlice {
	m := make(models.CartItemSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableCartItem(m *models.CartItemSetter) {
	if !(m.ID.IsValue()) {
		val := random_string(nil, "50")
		m.ID = omit.From(val)
	}
	if !(m.CartID.IsValue()) {
		val := random_string(nil, "50")
		m.CartID = omit.From(val)
	}
	if !(m.BookID.IsValue()) {
		val := random_string(nil, "50")
		m.BookID = omit.From(val)
	}
	if !(m.Price.IsValue()) {
		val := random_decimal_Decimal(nil, "10", "2")
		m.Price = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.CartItem
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *CartItemTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.CartItem) error {
	var err error

	return err
}

// Create builds a cartItem and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *CartItemTemplate) Create(ctx context.Context, exec bob.Executor) (*models.CartItem, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableCartItem(opt)

	if o.r.Book == nil {
		CartItemMods.WithNewBook().Apply(ctx, o)
	}

	var rel0 *models.Book

	if o.r.Book.o.alreadyPersisted {
		rel0 = o.r.Book.o.Build()
	} else {
		rel0, err = o.r.Book.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.BookID = omit.From(rel0.ID)

	if o.r.Cart == nil {
		CartItemMods.WithNewCart().Apply(ctx, o)
	}

	var rel1 *models.Cart

	if o.r.Cart.o.alreadyPersisted {
		rel1 = o.r.Cart.o.Build()
	} else {
		rel1, err = o.r.Cart.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.CartID = omit.From(rel1.ID)

	m, err := models.CartItems.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.Book = rel0
	m.R.Cart = rel1

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a cartItem and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *CartItemTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.CartItem {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a cartItem and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *CartItemTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.CartItem {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple cartItems and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o CartItemTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.CartItemSlice, error) {
	var err error
	m := make(models.CartItemSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple cartItems and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o CartItemTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.CartItemSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple cartItems and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o CartItemTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.CartItemSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CartItem has methods that act as mods for the CartItemTemplate
var CartItemMods cartItemMods

type cartItemMods struct{}

func (m cartItemMods) RandomizeAllColumns(f *faker.Faker) CartItemMod {
	return CartItemModSlice{
		CartItemMods.RandomID(f),
		CartItemMods.RandomCartID(f),
		CartItemMods.RandomBookID(f),
		CartItemMods.RandomQuantity(f),
		CartItemMods.RandomPrice(f),
		CartItemMods.RandomCreatedAt(f),
		CartItemMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m cartItemMods) ID(val string) CartItemMod {
	return CartItemModFunc(func(_ context.Context, o *CartItemTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m cartItemMods) IDFunc(f func() string) CartItemMod {
	return CartItemModFunc(func(_ context.Context, o *CartItemTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m cartItemMods) UnsetID() CartItemMod {
	return CartItemModFunc(func(_ context.Context, o *CartItemTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m cartItemMods) RandomID(f *faker.Faker) CartItemMod {
	return CartItemModFunc(func(_ context.Context, o *CartItemTemplate) {
		o.ID = func() string {
			return random_string(f, "50")
		}
	})
}

// Set the model columns to this value
func (m cartItemMods) CartID(val string) CartItemMod {
	return CartItemModFunc(func(_ context.Context, o *CartItemTemplate) {
		o.CartID = func() string { return val }
	})
}

// Set the Column from the function
func (m cartItemMods) CartIDFunc(f func() string) CartItemMod {
	return CartItemModFunc(func(_ context.Context, o *CartItemTemplate) {
		o.CartID = f
	})
}

// Clear any values for the column
func (m cartItemMods) UnsetCartID() CartItemMod {
	return CartItemModFunc(func(_ context.Context, o *CartItemTemplate) {
		o.CartID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m cartItemMods) RandomCartID(f *faker.Faker) CartItemMod {
	return CartItemModFunc(func(_ context.Context, o *CartItemTemplate) {
		o.CartID = func() string {
			return random_string(f, "50")
		}
	})
}

// Set the model columns to this value
func (m cartItemMods) BookID(val string) CartItemMod {
	return CartItemModFunc(func(_ context.Context, o *CartItemTemplate) {
		o.BookID = func() string { return val }
	})
}

// Set the Column from the function
func (m cartItemMods) BookIDFunc(f func() string) CartItemMod {
	return CartItemModFunc(func(_ context.Context, o *CartItemTemplate) {
		o.BookID = f
	})
}

// Clear any values for the column
func (m cartItemMods) UnsetBookID() CartItemMod {
	return CartItemModFunc(func(_ context.Context, o *CartItemTemplate) {
		o.BookID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m cartItemMods) RandomBookID(f *faker.Faker) CartItemMod {
	return CartItemModFunc(func(_ context.Context, o *CartItemTemplate) {
		o.BookID = func() string {
			return random_string(f, "50")
		}
	})
}

// Set the model columns to this value
func (m cartItemMods) Quantity(val int32) CartItemMod {
	return CartItemModFunc(func(_ context.Context, o *CartItemTemplate) {
		o.Quantity = func() int32 { return val }
	})
}

// Set the Column from the function
func (m cartItemMods) QuantityFunc(f func() int32) CartItemMod {
	return CartItemModFunc(func(_ context.Context, o *CartItemTemplate) {
		o.Quantity = f
	})
}

// Clear any values for the column
func (m cartItemMods) UnsetQuantity() CartItemMod {
	return CartItemModFunc(func(_ context.Context, o *CartItemTemplate) {
		o.Quantity = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m cartItemMods) RandomQuantity(f *faker.Faker) CartItemMod {
	return CartItemModFunc(func(_ context.Context, o *CartItemTemplate) {
		o.Quantity = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m cartItemMods) Price(val decimal.Decimal) CartItemMod {
	return CartItemModFunc(func(_ context.Context, o *CartItemTemplate) {
		o.Price = func() decimal.Decimal { return val }
	})
}

// Set the Column from the function
func (m cartItemMods) PriceFunc(f func() decimal.Decimal) CartItemMod {
	return CartItemModFunc(func(_ context.Context, o *CartItemTemplate) {
		o.Price = f
	})
}

// Clear any values for the column
func (m cartItemMods) UnsetPrice() CartItemMod {
	return CartItemModFunc(func(_ context.Context, o *CartItemTemplate) {
		o.Price = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m cartItemMods) RandomPrice(f *faker.Faker) CartItemMod {
	return CartItemModFunc(func(_ context.Context, o *CartItemTemplate) {
		o.Price = func() decimal.Decimal {
			return random_decimal_Decimal(f, "10", "2")
		}
	})
}

// Set the model columns to this value
func (m cartItemMods) CreatedAt(val time.Time) CartItemMod {
	return CartItemModFunc(func(_ context.Context, o *CartItemTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m cartItemMods) CreatedAtFunc(f func() time.Time) CartItemMod {
	return CartItemModFunc(func(_ context.Context, o *CartItemTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m cartItemMods) UnsetCreatedAt() CartItemMod {
	return CartItemModFunc(func(_ context.Context, o *CartItemTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m cartItemMods) RandomCreatedAt(f *faker.Faker) CartItemMod {
	return CartItemModFunc(func(_ context.Context, o *CartItemTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m cartItemMods) UpdatedAt(val time.Time) CartItemMod {
	return CartItemModFunc(func(_ context.Context, o *CartItemTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m cartItemMods) UpdatedAtFunc(f func() time.Time) CartItemMod {
	return CartItemModFunc(func(_ context.Context, o *CartItemTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m cartItemMods) UnsetUpdatedAt() CartItemMod {
	return CartItemModFunc(func(_ context.Context, o *CartItemTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m cartItemMods) RandomUpdatedAt(f *faker.Faker) CartItemMod {
	return CartItemModFunc(func(_ context.Context, o *CartItemTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m cartItemMods) WithParentsCascading() CartItemMod {
	return CartItemModFunc(func(ctx context.Context, o *CartItemTemplate) {
		if isDone, _ := cartItemWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = cartItemWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewBookWithContext(ctx, BookMods.WithParentsCascading())
			m.WithBook(related).Apply(ctx, o)
		}
		{

			related := o.f.NewCartWithContext(ctx, CartMods.WithParentsCascading())
			m.WithCart(related).Apply(ctx, o)
		}
	})
}

func (m cartItemMods) WithBook(rel *BookTemplate) CartItemMod {
	return CartItemModFunc(func(ctx context.Context, o *CartItemTemplate) {
		o.r.Book = &cartItemRBookR{
			o: rel,
		}
	})
}

func (m cartItemMods) WithNewBook(mods ...BookMod) CartItemMod {
	return CartItemModFunc(func(ctx context.Context, o *CartItemTemplate) {
		related := o.f.NewBookWithContext(ctx, mods...)

		m.WithBook(related).Apply(ctx, o)
	})
}

func (m cartItemMods) WithExistingBook(em *models.Book) CartItemMod {
	return CartItemModFunc(func(ctx context.Context, o *CartItemTemplate) {
		o.r.Book = &cartItemRBookR{
			o: o.f.FromExistingBook(em),
		}
	})
}

func (m cartItemMods) WithoutBook() CartItemMod {
	return CartItemModFunc(func(ctx context.Context, o *CartItemTemplate) {
		o.r.Book = nil
	})
}

func (m cartItemMods) WithCart(rel *CartTemplate) CartItemMod {
	return CartItemModFunc(func(ctx context.Context, o *CartItemTemplate) {
		o.r.Cart = &cartItemRCartR{
			o: rel,
		}
	})
}

func (m cartItemMods) WithNewCart(mods ...CartMod) CartItemMod {
	return CartItemModFunc(func(ctx context.Context, o *CartItemTemplate) {
		related := o.f.NewCartWithContext(ctx, mods...)

		m.WithCart(related).Apply(ctx, o)
	})
}

func (m cartItemMods) WithExistingCart(em *models.Cart) CartItemMod {
	return CartItemModFunc(func(ctx context.Context, o *CartItemTemplate) {
		o.r.Cart = &cartItemRCartR{
			o: o.f.FromExistingCart(em),
		}
	})
}

func (m cartItemMods) WithoutCart() CartItemMod {
	return CartItemModFunc(func(ctx context.Context, o *CartItemTemplate) {
		o.r.Cart = nil
	})
}
