// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker/v2"
	models "github.com/shailendrapawar/book-store/internal/db/models"
	"github.com/stephenafamo/bob"
)

type CartMod interface {
	Apply(context.Context, *CartTemplate)
}

type CartModFunc func(context.Context, *CartTemplate)

func (f CartModFunc) Apply(ctx context.Context, n *CartTemplate) {
	f(ctx, n)
}

type CartModSlice []CartMod

func (mods CartModSlice) Apply(ctx context.Context, n *CartTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// CartTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type CartTemplate struct {
	ID        func() string
	UserID    func() string
	CreatedAt func() time.Time
	UpdatedAt func() time.Time

	r cartR
	f *Factory

	alreadyPersisted bool
}

type cartR struct {
	CartItems []*cartRCartItemsR
	User      *cartRUserR
}

type cartRCartItemsR struct {
	number int
	o      *CartItemTemplate
}
type cartRUserR struct {
	o *UserTemplate
}

// Apply mods to the CartTemplate
func (o *CartTemplate) Apply(ctx context.Context, mods ...CartMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Cart
// according to the relationships in the template. Nothing is inserted into the db
func (t CartTemplate) setModelRels(o *models.Cart) {
	if t.r.CartItems != nil {
		rel := models.CartItemSlice{}
		for _, r := range t.r.CartItems {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.CartID = o.ID // h2
				rel.R.Cart = o
			}
			rel = append(rel, related...)
		}
		o.R.CartItems = rel
	}

	if t.r.User != nil {
		rel := t.r.User.o.Build()
		rel.R.Carts = append(rel.R.Carts, o)
		o.UserID = rel.ID // h2
		o.R.User = rel
	}
}

// BuildSetter returns an *models.CartSetter
// this does nothing with the relationship templates
func (o CartTemplate) BuildSetter() *models.CartSetter {
	m := &models.CartSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.UserID != nil {
		val := o.UserID()
		m.UserID = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.CartSetter
// this does nothing with the relationship templates
func (o CartTemplate) BuildManySetter(number int) []*models.CartSetter {
	m := make([]*models.CartSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Cart
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use CartTemplate.Create
func (o CartTemplate) Build() *models.Cart {
	m := &models.Cart{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.UserID != nil {
		m.UserID = o.UserID()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.CartSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use CartTemplate.CreateMany
func (o CartTemplate) BuildMany(number int) models.CartSlice {
	m := make(models.CartSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableCart(m *models.CartSetter) {
	if !(m.ID.IsValue()) {
		val := random_string(nil, "50")
		m.ID = omit.From(val)
	}
	if !(m.UserID.IsValue()) {
		val := random_string(nil, "50")
		m.UserID = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Cart
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *CartTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Cart) error {
	var err error

	isCartItemsDone, _ := cartRelCartItemsCtx.Value(ctx)
	if !isCartItemsDone && o.r.CartItems != nil {
		ctx = cartRelCartItemsCtx.WithValue(ctx, true)
		for _, r := range o.r.CartItems {
			if r.o.alreadyPersisted {
				m.R.CartItems = append(m.R.CartItems, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachCartItems(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a cart and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *CartTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Cart, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableCart(opt)

	if o.r.User == nil {
		CartMods.WithNewUser().Apply(ctx, o)
	}

	var rel1 *models.User

	if o.r.User.o.alreadyPersisted {
		rel1 = o.r.User.o.Build()
	} else {
		rel1, err = o.r.User.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.UserID = omit.From(rel1.ID)

	m, err := models.Carts.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.User = rel1

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a cart and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *CartTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Cart {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a cart and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *CartTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Cart {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple carts and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o CartTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.CartSlice, error) {
	var err error
	m := make(models.CartSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple carts and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o CartTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.CartSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple carts and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o CartTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.CartSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Cart has methods that act as mods for the CartTemplate
var CartMods cartMods

type cartMods struct{}

func (m cartMods) RandomizeAllColumns(f *faker.Faker) CartMod {
	return CartModSlice{
		CartMods.RandomID(f),
		CartMods.RandomUserID(f),
		CartMods.RandomCreatedAt(f),
		CartMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m cartMods) ID(val string) CartMod {
	return CartModFunc(func(_ context.Context, o *CartTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m cartMods) IDFunc(f func() string) CartMod {
	return CartModFunc(func(_ context.Context, o *CartTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m cartMods) UnsetID() CartMod {
	return CartModFunc(func(_ context.Context, o *CartTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m cartMods) RandomID(f *faker.Faker) CartMod {
	return CartModFunc(func(_ context.Context, o *CartTemplate) {
		o.ID = func() string {
			return random_string(f, "50")
		}
	})
}

// Set the model columns to this value
func (m cartMods) UserID(val string) CartMod {
	return CartModFunc(func(_ context.Context, o *CartTemplate) {
		o.UserID = func() string { return val }
	})
}

// Set the Column from the function
func (m cartMods) UserIDFunc(f func() string) CartMod {
	return CartModFunc(func(_ context.Context, o *CartTemplate) {
		o.UserID = f
	})
}

// Clear any values for the column
func (m cartMods) UnsetUserID() CartMod {
	return CartModFunc(func(_ context.Context, o *CartTemplate) {
		o.UserID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m cartMods) RandomUserID(f *faker.Faker) CartMod {
	return CartModFunc(func(_ context.Context, o *CartTemplate) {
		o.UserID = func() string {
			return random_string(f, "50")
		}
	})
}

// Set the model columns to this value
func (m cartMods) CreatedAt(val time.Time) CartMod {
	return CartModFunc(func(_ context.Context, o *CartTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m cartMods) CreatedAtFunc(f func() time.Time) CartMod {
	return CartModFunc(func(_ context.Context, o *CartTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m cartMods) UnsetCreatedAt() CartMod {
	return CartModFunc(func(_ context.Context, o *CartTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m cartMods) RandomCreatedAt(f *faker.Faker) CartMod {
	return CartModFunc(func(_ context.Context, o *CartTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m cartMods) UpdatedAt(val time.Time) CartMod {
	return CartModFunc(func(_ context.Context, o *CartTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m cartMods) UpdatedAtFunc(f func() time.Time) CartMod {
	return CartModFunc(func(_ context.Context, o *CartTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m cartMods) UnsetUpdatedAt() CartMod {
	return CartModFunc(func(_ context.Context, o *CartTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m cartMods) RandomUpdatedAt(f *faker.Faker) CartMod {
	return CartModFunc(func(_ context.Context, o *CartTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m cartMods) WithParentsCascading() CartMod {
	return CartModFunc(func(ctx context.Context, o *CartTemplate) {
		if isDone, _ := cartWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = cartWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithUser(related).Apply(ctx, o)
		}
	})
}

func (m cartMods) WithUser(rel *UserTemplate) CartMod {
	return CartModFunc(func(ctx context.Context, o *CartTemplate) {
		o.r.User = &cartRUserR{
			o: rel,
		}
	})
}

func (m cartMods) WithNewUser(mods ...UserMod) CartMod {
	return CartModFunc(func(ctx context.Context, o *CartTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithUser(related).Apply(ctx, o)
	})
}

func (m cartMods) WithExistingUser(em *models.User) CartMod {
	return CartModFunc(func(ctx context.Context, o *CartTemplate) {
		o.r.User = &cartRUserR{
			o: o.f.FromExistingUser(em),
		}
	})
}

func (m cartMods) WithoutUser() CartMod {
	return CartModFunc(func(ctx context.Context, o *CartTemplate) {
		o.r.User = nil
	})
}

func (m cartMods) WithCartItems(number int, related *CartItemTemplate) CartMod {
	return CartModFunc(func(ctx context.Context, o *CartTemplate) {
		o.r.CartItems = []*cartRCartItemsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m cartMods) WithNewCartItems(number int, mods ...CartItemMod) CartMod {
	return CartModFunc(func(ctx context.Context, o *CartTemplate) {
		related := o.f.NewCartItemWithContext(ctx, mods...)
		m.WithCartItems(number, related).Apply(ctx, o)
	})
}

func (m cartMods) AddCartItems(number int, related *CartItemTemplate) CartMod {
	return CartModFunc(func(ctx context.Context, o *CartTemplate) {
		o.r.CartItems = append(o.r.CartItems, &cartRCartItemsR{
			number: number,
			o:      related,
		})
	})
}

func (m cartMods) AddNewCartItems(number int, mods ...CartItemMod) CartMod {
	return CartModFunc(func(ctx context.Context, o *CartTemplate) {
		related := o.f.NewCartItemWithContext(ctx, mods...)
		m.AddCartItems(number, related).Apply(ctx, o)
	})
}

func (m cartMods) AddExistingCartItems(existingModels ...*models.CartItem) CartMod {
	return CartModFunc(func(ctx context.Context, o *CartTemplate) {
		for _, em := range existingModels {
			o.r.CartItems = append(o.r.CartItems, &cartRCartItemsR{
				o: o.f.FromExistingCartItem(em),
			})
		}
	})
}

func (m cartMods) WithoutCartItems() CartMod {
	return CartModFunc(func(ctx context.Context, o *CartTemplate) {
		o.r.CartItems = nil
	})
}
