// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"encoding/json"
	"testing"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker/v2"
	models "github.com/shailendrapawar/book-store/internal/db/models"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
)

type OrderMod interface {
	Apply(context.Context, *OrderTemplate)
}

type OrderModFunc func(context.Context, *OrderTemplate)

func (f OrderModFunc) Apply(ctx context.Context, n *OrderTemplate) {
	f(ctx, n)
}

type OrderModSlice []OrderMod

func (mods OrderModSlice) Apply(ctx context.Context, n *OrderTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// OrderTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type OrderTemplate struct {
	ID              func() string
	UserID          func() string
	Status          func() string
	DiscountValue   func() decimal.Decimal
	DiscountType    func() string
	GrossAmount     func() decimal.Decimal
	NetAmount       func() decimal.Decimal
	ShippingAddress func() types.JSON[json.RawMessage]
	ShippingCity    func() string
	ShippingState   func() string
	ShippingPincode func() string
	PaymentStatus   func() string
	PaymentMethod   func() string
	CreatedAt       func() time.Time
	UpdatedAt       func() time.Time

	r orderR
	f *Factory

	alreadyPersisted bool
}

type orderR struct {
	User *orderRUserR
}

type orderRUserR struct {
	o *UserTemplate
}

// Apply mods to the OrderTemplate
func (o *OrderTemplate) Apply(ctx context.Context, mods ...OrderMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Order
// according to the relationships in the template. Nothing is inserted into the db
func (t OrderTemplate) setModelRels(o *models.Order) {
	if t.r.User != nil {
		rel := t.r.User.o.Build()
		rel.R.Orders = append(rel.R.Orders, o)
		o.UserID = rel.ID // h2
		o.R.User = rel
	}
}

// BuildSetter returns an *models.OrderSetter
// this does nothing with the relationship templates
func (o OrderTemplate) BuildSetter() *models.OrderSetter {
	m := &models.OrderSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.UserID != nil {
		val := o.UserID()
		m.UserID = omit.From(val)
	}
	if o.Status != nil {
		val := o.Status()
		m.Status = omit.From(val)
	}
	if o.DiscountValue != nil {
		val := o.DiscountValue()
		m.DiscountValue = omit.From(val)
	}
	if o.DiscountType != nil {
		val := o.DiscountType()
		m.DiscountType = omit.From(val)
	}
	if o.GrossAmount != nil {
		val := o.GrossAmount()
		m.GrossAmount = omit.From(val)
	}
	if o.NetAmount != nil {
		val := o.NetAmount()
		m.NetAmount = omit.From(val)
	}
	if o.ShippingAddress != nil {
		val := o.ShippingAddress()
		m.ShippingAddress = omit.From(val)
	}
	if o.ShippingCity != nil {
		val := o.ShippingCity()
		m.ShippingCity = omit.From(val)
	}
	if o.ShippingState != nil {
		val := o.ShippingState()
		m.ShippingState = omit.From(val)
	}
	if o.ShippingPincode != nil {
		val := o.ShippingPincode()
		m.ShippingPincode = omit.From(val)
	}
	if o.PaymentStatus != nil {
		val := o.PaymentStatus()
		m.PaymentStatus = omit.From(val)
	}
	if o.PaymentMethod != nil {
		val := o.PaymentMethod()
		m.PaymentMethod = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.OrderSetter
// this does nothing with the relationship templates
func (o OrderTemplate) BuildManySetter(number int) []*models.OrderSetter {
	m := make([]*models.OrderSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Order
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use OrderTemplate.Create
func (o OrderTemplate) Build() *models.Order {
	m := &models.Order{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.UserID != nil {
		m.UserID = o.UserID()
	}
	if o.Status != nil {
		m.Status = o.Status()
	}
	if o.DiscountValue != nil {
		m.DiscountValue = o.DiscountValue()
	}
	if o.DiscountType != nil {
		m.DiscountType = o.DiscountType()
	}
	if o.GrossAmount != nil {
		m.GrossAmount = o.GrossAmount()
	}
	if o.NetAmount != nil {
		m.NetAmount = o.NetAmount()
	}
	if o.ShippingAddress != nil {
		m.ShippingAddress = o.ShippingAddress()
	}
	if o.ShippingCity != nil {
		m.ShippingCity = o.ShippingCity()
	}
	if o.ShippingState != nil {
		m.ShippingState = o.ShippingState()
	}
	if o.ShippingPincode != nil {
		m.ShippingPincode = o.ShippingPincode()
	}
	if o.PaymentStatus != nil {
		m.PaymentStatus = o.PaymentStatus()
	}
	if o.PaymentMethod != nil {
		m.PaymentMethod = o.PaymentMethod()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.OrderSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use OrderTemplate.CreateMany
func (o OrderTemplate) BuildMany(number int) models.OrderSlice {
	m := make(models.OrderSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableOrder(m *models.OrderSetter) {
	if !(m.ID.IsValue()) {
		val := random_string(nil, "50")
		m.ID = omit.From(val)
	}
	if !(m.UserID.IsValue()) {
		val := random_string(nil, "50")
		m.UserID = omit.From(val)
	}
	if !(m.GrossAmount.IsValue()) {
		val := random_decimal_Decimal(nil, "10", "2")
		m.GrossAmount = omit.From(val)
	}
	if !(m.NetAmount.IsValue()) {
		val := random_decimal_Decimal(nil, "10", "2")
		m.NetAmount = omit.From(val)
	}
	if !(m.ShippingAddress.IsValue()) {
		val := random_types_JSON_json_RawMessage_(nil)
		m.ShippingAddress = omit.From(val)
	}
	if !(m.ShippingCity.IsValue()) {
		val := random_string(nil, "255")
		m.ShippingCity = omit.From(val)
	}
	if !(m.ShippingState.IsValue()) {
		val := random_string(nil, "255")
		m.ShippingState = omit.From(val)
	}
	if !(m.ShippingPincode.IsValue()) {
		val := random_string(nil, "10")
		m.ShippingPincode = omit.From(val)
	}
	if !(m.PaymentMethod.IsValue()) {
		val := random_string(nil, "20")
		m.PaymentMethod = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Order
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *OrderTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Order) error {
	var err error

	return err
}

// Create builds a order and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *OrderTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Order, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableOrder(opt)

	if o.r.User == nil {
		OrderMods.WithNewUser().Apply(ctx, o)
	}

	var rel0 *models.User

	if o.r.User.o.alreadyPersisted {
		rel0 = o.r.User.o.Build()
	} else {
		rel0, err = o.r.User.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.UserID = omit.From(rel0.ID)

	m, err := models.Orders.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.User = rel0

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a order and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *OrderTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Order {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a order and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *OrderTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Order {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple orders and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o OrderTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.OrderSlice, error) {
	var err error
	m := make(models.OrderSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple orders and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o OrderTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.OrderSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple orders and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o OrderTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.OrderSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Order has methods that act as mods for the OrderTemplate
var OrderMods orderMods

type orderMods struct{}

func (m orderMods) RandomizeAllColumns(f *faker.Faker) OrderMod {
	return OrderModSlice{
		OrderMods.RandomID(f),
		OrderMods.RandomUserID(f),
		OrderMods.RandomStatus(f),
		OrderMods.RandomDiscountValue(f),
		OrderMods.RandomDiscountType(f),
		OrderMods.RandomGrossAmount(f),
		OrderMods.RandomNetAmount(f),
		OrderMods.RandomShippingAddress(f),
		OrderMods.RandomShippingCity(f),
		OrderMods.RandomShippingState(f),
		OrderMods.RandomShippingPincode(f),
		OrderMods.RandomPaymentStatus(f),
		OrderMods.RandomPaymentMethod(f),
		OrderMods.RandomCreatedAt(f),
		OrderMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m orderMods) ID(val string) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m orderMods) IDFunc(f func() string) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetID() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderMods) RandomID(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.ID = func() string {
			return random_string(f, "50")
		}
	})
}

// Set the model columns to this value
func (m orderMods) UserID(val string) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.UserID = func() string { return val }
	})
}

// Set the Column from the function
func (m orderMods) UserIDFunc(f func() string) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.UserID = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetUserID() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.UserID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderMods) RandomUserID(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.UserID = func() string {
			return random_string(f, "50")
		}
	})
}

// Set the model columns to this value
func (m orderMods) Status(val string) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.Status = func() string { return val }
	})
}

// Set the Column from the function
func (m orderMods) StatusFunc(f func() string) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.Status = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetStatus() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.Status = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderMods) RandomStatus(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.Status = func() string {
			return random_string(f, "20")
		}
	})
}

// Set the model columns to this value
func (m orderMods) DiscountValue(val decimal.Decimal) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.DiscountValue = func() decimal.Decimal { return val }
	})
}

// Set the Column from the function
func (m orderMods) DiscountValueFunc(f func() decimal.Decimal) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.DiscountValue = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetDiscountValue() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.DiscountValue = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderMods) RandomDiscountValue(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.DiscountValue = func() decimal.Decimal {
			return random_decimal_Decimal(f, "10", "2")
		}
	})
}

// Set the model columns to this value
func (m orderMods) DiscountType(val string) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.DiscountType = func() string { return val }
	})
}

// Set the Column from the function
func (m orderMods) DiscountTypeFunc(f func() string) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.DiscountType = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetDiscountType() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.DiscountType = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderMods) RandomDiscountType(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.DiscountType = func() string {
			return random_string(f, "20")
		}
	})
}

// Set the model columns to this value
func (m orderMods) GrossAmount(val decimal.Decimal) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.GrossAmount = func() decimal.Decimal { return val }
	})
}

// Set the Column from the function
func (m orderMods) GrossAmountFunc(f func() decimal.Decimal) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.GrossAmount = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetGrossAmount() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.GrossAmount = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderMods) RandomGrossAmount(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.GrossAmount = func() decimal.Decimal {
			return random_decimal_Decimal(f, "10", "2")
		}
	})
}

// Set the model columns to this value
func (m orderMods) NetAmount(val decimal.Decimal) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.NetAmount = func() decimal.Decimal { return val }
	})
}

// Set the Column from the function
func (m orderMods) NetAmountFunc(f func() decimal.Decimal) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.NetAmount = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetNetAmount() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.NetAmount = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderMods) RandomNetAmount(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.NetAmount = func() decimal.Decimal {
			return random_decimal_Decimal(f, "10", "2")
		}
	})
}

// Set the model columns to this value
func (m orderMods) ShippingAddress(val types.JSON[json.RawMessage]) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.ShippingAddress = func() types.JSON[json.RawMessage] { return val }
	})
}

// Set the Column from the function
func (m orderMods) ShippingAddressFunc(f func() types.JSON[json.RawMessage]) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.ShippingAddress = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetShippingAddress() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.ShippingAddress = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderMods) RandomShippingAddress(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.ShippingAddress = func() types.JSON[json.RawMessage] {
			return random_types_JSON_json_RawMessage_(f)
		}
	})
}

// Set the model columns to this value
func (m orderMods) ShippingCity(val string) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.ShippingCity = func() string { return val }
	})
}

// Set the Column from the function
func (m orderMods) ShippingCityFunc(f func() string) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.ShippingCity = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetShippingCity() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.ShippingCity = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderMods) RandomShippingCity(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.ShippingCity = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m orderMods) ShippingState(val string) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.ShippingState = func() string { return val }
	})
}

// Set the Column from the function
func (m orderMods) ShippingStateFunc(f func() string) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.ShippingState = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetShippingState() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.ShippingState = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderMods) RandomShippingState(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.ShippingState = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m orderMods) ShippingPincode(val string) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.ShippingPincode = func() string { return val }
	})
}

// Set the Column from the function
func (m orderMods) ShippingPincodeFunc(f func() string) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.ShippingPincode = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetShippingPincode() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.ShippingPincode = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderMods) RandomShippingPincode(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.ShippingPincode = func() string {
			return random_string(f, "10")
		}
	})
}

// Set the model columns to this value
func (m orderMods) PaymentStatus(val string) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.PaymentStatus = func() string { return val }
	})
}

// Set the Column from the function
func (m orderMods) PaymentStatusFunc(f func() string) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.PaymentStatus = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetPaymentStatus() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.PaymentStatus = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderMods) RandomPaymentStatus(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.PaymentStatus = func() string {
			return random_string(f, "20")
		}
	})
}

// Set the model columns to this value
func (m orderMods) PaymentMethod(val string) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.PaymentMethod = func() string { return val }
	})
}

// Set the Column from the function
func (m orderMods) PaymentMethodFunc(f func() string) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.PaymentMethod = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetPaymentMethod() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.PaymentMethod = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderMods) RandomPaymentMethod(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.PaymentMethod = func() string {
			return random_string(f, "20")
		}
	})
}

// Set the model columns to this value
func (m orderMods) CreatedAt(val time.Time) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m orderMods) CreatedAtFunc(f func() time.Time) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetCreatedAt() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderMods) RandomCreatedAt(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m orderMods) UpdatedAt(val time.Time) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m orderMods) UpdatedAtFunc(f func() time.Time) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetUpdatedAt() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderMods) RandomUpdatedAt(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m orderMods) WithParentsCascading() OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		if isDone, _ := orderWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = orderWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithUser(related).Apply(ctx, o)
		}
	})
}

func (m orderMods) WithUser(rel *UserTemplate) OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		o.r.User = &orderRUserR{
			o: rel,
		}
	})
}

func (m orderMods) WithNewUser(mods ...UserMod) OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithUser(related).Apply(ctx, o)
	})
}

func (m orderMods) WithExistingUser(em *models.User) OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		o.r.User = &orderRUserR{
			o: o.f.FromExistingUser(em),
		}
	})
}

func (m orderMods) WithoutUser() OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		o.r.User = nil
	})
}
