// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker/v2"
	models "github.com/shailendrapawar/book-store/internal/db/models"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
)

type OrderMod interface {
	Apply(context.Context, *OrderTemplate)
}

type OrderModFunc func(context.Context, *OrderTemplate)

func (f OrderModFunc) Apply(ctx context.Context, n *OrderTemplate) {
	f(ctx, n)
}

type OrderModSlice []OrderMod

func (mods OrderModSlice) Apply(ctx context.Context, n *OrderTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// OrderTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type OrderTemplate struct {
	ID               func() string
	UserID           func() string
	CartID           func() string
	Amount           func() decimal.Decimal
	DelieveryAddress func() string
	CreatedAt        func() time.Time
	UpdatedAt        func() time.Time

	r orderR
	f *Factory

	alreadyPersisted bool
}

type orderR struct {
	Cart *orderRCartR
	User *orderRUserR
}

type orderRCartR struct {
	o *CartTemplate
}
type orderRUserR struct {
	o *UserTemplate
}

// Apply mods to the OrderTemplate
func (o *OrderTemplate) Apply(ctx context.Context, mods ...OrderMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Order
// according to the relationships in the template. Nothing is inserted into the db
func (t OrderTemplate) setModelRels(o *models.Order) {
	if t.r.Cart != nil {
		rel := t.r.Cart.o.Build()
		rel.R.Orders = append(rel.R.Orders, o)
		o.CartID = rel.ID // h2
		o.R.Cart = rel
	}

	if t.r.User != nil {
		rel := t.r.User.o.Build()
		rel.R.Orders = append(rel.R.Orders, o)
		o.UserID = rel.ID // h2
		o.R.User = rel
	}
}

// BuildSetter returns an *models.OrderSetter
// this does nothing with the relationship templates
func (o OrderTemplate) BuildSetter() *models.OrderSetter {
	m := &models.OrderSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.UserID != nil {
		val := o.UserID()
		m.UserID = omit.From(val)
	}
	if o.CartID != nil {
		val := o.CartID()
		m.CartID = omit.From(val)
	}
	if o.Amount != nil {
		val := o.Amount()
		m.Amount = omit.From(val)
	}
	if o.DelieveryAddress != nil {
		val := o.DelieveryAddress()
		m.DelieveryAddress = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.OrderSetter
// this does nothing with the relationship templates
func (o OrderTemplate) BuildManySetter(number int) []*models.OrderSetter {
	m := make([]*models.OrderSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Order
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use OrderTemplate.Create
func (o OrderTemplate) Build() *models.Order {
	m := &models.Order{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.UserID != nil {
		m.UserID = o.UserID()
	}
	if o.CartID != nil {
		m.CartID = o.CartID()
	}
	if o.Amount != nil {
		m.Amount = o.Amount()
	}
	if o.DelieveryAddress != nil {
		m.DelieveryAddress = o.DelieveryAddress()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.OrderSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use OrderTemplate.CreateMany
func (o OrderTemplate) BuildMany(number int) models.OrderSlice {
	m := make(models.OrderSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableOrder(m *models.OrderSetter) {
	if !(m.ID.IsValue()) {
		val := random_string(nil, "50")
		m.ID = omit.From(val)
	}
	if !(m.UserID.IsValue()) {
		val := random_string(nil, "50")
		m.UserID = omit.From(val)
	}
	if !(m.CartID.IsValue()) {
		val := random_string(nil, "50")
		m.CartID = omit.From(val)
	}
	if !(m.Amount.IsValue()) {
		val := random_decimal_Decimal(nil, "10", "2")
		m.Amount = omit.From(val)
	}
	if !(m.DelieveryAddress.IsValue()) {
		val := random_string(nil, "255")
		m.DelieveryAddress = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Order
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *OrderTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Order) error {
	var err error

	return err
}

// Create builds a order and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *OrderTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Order, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableOrder(opt)

	if o.r.Cart == nil {
		OrderMods.WithNewCart().Apply(ctx, o)
	}

	var rel0 *models.Cart

	if o.r.Cart.o.alreadyPersisted {
		rel0 = o.r.Cart.o.Build()
	} else {
		rel0, err = o.r.Cart.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.CartID = omit.From(rel0.ID)

	if o.r.User == nil {
		OrderMods.WithNewUser().Apply(ctx, o)
	}

	var rel1 *models.User

	if o.r.User.o.alreadyPersisted {
		rel1 = o.r.User.o.Build()
	} else {
		rel1, err = o.r.User.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.UserID = omit.From(rel1.ID)

	m, err := models.Orders.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.Cart = rel0
	m.R.User = rel1

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a order and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *OrderTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Order {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a order and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *OrderTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Order {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple orders and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o OrderTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.OrderSlice, error) {
	var err error
	m := make(models.OrderSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple orders and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o OrderTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.OrderSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple orders and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o OrderTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.OrderSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Order has methods that act as mods for the OrderTemplate
var OrderMods orderMods

type orderMods struct{}

func (m orderMods) RandomizeAllColumns(f *faker.Faker) OrderMod {
	return OrderModSlice{
		OrderMods.RandomID(f),
		OrderMods.RandomUserID(f),
		OrderMods.RandomCartID(f),
		OrderMods.RandomAmount(f),
		OrderMods.RandomDelieveryAddress(f),
		OrderMods.RandomCreatedAt(f),
		OrderMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m orderMods) ID(val string) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m orderMods) IDFunc(f func() string) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetID() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderMods) RandomID(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.ID = func() string {
			return random_string(f, "50")
		}
	})
}

// Set the model columns to this value
func (m orderMods) UserID(val string) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.UserID = func() string { return val }
	})
}

// Set the Column from the function
func (m orderMods) UserIDFunc(f func() string) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.UserID = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetUserID() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.UserID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderMods) RandomUserID(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.UserID = func() string {
			return random_string(f, "50")
		}
	})
}

// Set the model columns to this value
func (m orderMods) CartID(val string) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.CartID = func() string { return val }
	})
}

// Set the Column from the function
func (m orderMods) CartIDFunc(f func() string) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.CartID = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetCartID() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.CartID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderMods) RandomCartID(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.CartID = func() string {
			return random_string(f, "50")
		}
	})
}

// Set the model columns to this value
func (m orderMods) Amount(val decimal.Decimal) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.Amount = func() decimal.Decimal { return val }
	})
}

// Set the Column from the function
func (m orderMods) AmountFunc(f func() decimal.Decimal) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.Amount = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetAmount() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.Amount = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderMods) RandomAmount(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.Amount = func() decimal.Decimal {
			return random_decimal_Decimal(f, "10", "2")
		}
	})
}

// Set the model columns to this value
func (m orderMods) DelieveryAddress(val string) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.DelieveryAddress = func() string { return val }
	})
}

// Set the Column from the function
func (m orderMods) DelieveryAddressFunc(f func() string) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.DelieveryAddress = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetDelieveryAddress() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.DelieveryAddress = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderMods) RandomDelieveryAddress(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.DelieveryAddress = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m orderMods) CreatedAt(val time.Time) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m orderMods) CreatedAtFunc(f func() time.Time) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetCreatedAt() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderMods) RandomCreatedAt(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m orderMods) UpdatedAt(val time.Time) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m orderMods) UpdatedAtFunc(f func() time.Time) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetUpdatedAt() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderMods) RandomUpdatedAt(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m orderMods) WithParentsCascading() OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		if isDone, _ := orderWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = orderWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewCartWithContext(ctx, CartMods.WithParentsCascading())
			m.WithCart(related).Apply(ctx, o)
		}
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithUser(related).Apply(ctx, o)
		}
	})
}

func (m orderMods) WithCart(rel *CartTemplate) OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		o.r.Cart = &orderRCartR{
			o: rel,
		}
	})
}

func (m orderMods) WithNewCart(mods ...CartMod) OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		related := o.f.NewCartWithContext(ctx, mods...)

		m.WithCart(related).Apply(ctx, o)
	})
}

func (m orderMods) WithExistingCart(em *models.Cart) OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		o.r.Cart = &orderRCartR{
			o: o.f.FromExistingCart(em),
		}
	})
}

func (m orderMods) WithoutCart() OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		o.r.Cart = nil
	})
}

func (m orderMods) WithUser(rel *UserTemplate) OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		o.r.User = &orderRUserR{
			o: rel,
		}
	})
}

func (m orderMods) WithNewUser(mods ...UserMod) OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithUser(related).Apply(ctx, o)
	})
}

func (m orderMods) WithExistingUser(em *models.User) OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		o.r.User = &orderRUserR{
			o: o.f.FromExistingUser(em),
		}
	})
}

func (m orderMods) WithoutUser() OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		o.r.User = nil
	})
}
