// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker/v2"
	models "github.com/shailendrapawar/book-store/internal/db/models"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
)

type OrderItemMod interface {
	Apply(context.Context, *OrderItemTemplate)
}

type OrderItemModFunc func(context.Context, *OrderItemTemplate)

func (f OrderItemModFunc) Apply(ctx context.Context, n *OrderItemTemplate) {
	f(ctx, n)
}

type OrderItemModSlice []OrderItemMod

func (mods OrderItemModSlice) Apply(ctx context.Context, n *OrderItemTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// OrderItemTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type OrderItemTemplate struct {
	ID         func() string
	OrderID    func() string
	BookID     func() string
	Title      func() string
	Price      func() decimal.Decimal
	Quantity   func() int32
	TotalPrice func() decimal.Decimal
	CreatedAt  func() time.Time
	UpdatedAt  func() time.Time

	r orderItemR
	f *Factory

	alreadyPersisted bool
}

type orderItemR struct {
	Book  *orderItemRBookR
	Order *orderItemROrderR
}

type orderItemRBookR struct {
	o *BookTemplate
}
type orderItemROrderR struct {
	o *OrderTemplate
}

// Apply mods to the OrderItemTemplate
func (o *OrderItemTemplate) Apply(ctx context.Context, mods ...OrderItemMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.OrderItem
// according to the relationships in the template. Nothing is inserted into the db
func (t OrderItemTemplate) setModelRels(o *models.OrderItem) {
	if t.r.Book != nil {
		rel := t.r.Book.o.Build()
		rel.R.OrderItems = append(rel.R.OrderItems, o)
		o.BookID = rel.ID // h2
		o.R.Book = rel
	}

	if t.r.Order != nil {
		rel := t.r.Order.o.Build()
		rel.R.OrderItems = append(rel.R.OrderItems, o)
		o.OrderID = rel.ID // h2
		o.R.Order = rel
	}
}

// BuildSetter returns an *models.OrderItemSetter
// this does nothing with the relationship templates
func (o OrderItemTemplate) BuildSetter() *models.OrderItemSetter {
	m := &models.OrderItemSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.OrderID != nil {
		val := o.OrderID()
		m.OrderID = omit.From(val)
	}
	if o.BookID != nil {
		val := o.BookID()
		m.BookID = omit.From(val)
	}
	if o.Title != nil {
		val := o.Title()
		m.Title = omit.From(val)
	}
	if o.Price != nil {
		val := o.Price()
		m.Price = omit.From(val)
	}
	if o.Quantity != nil {
		val := o.Quantity()
		m.Quantity = omit.From(val)
	}
	if o.TotalPrice != nil {
		val := o.TotalPrice()
		m.TotalPrice = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.OrderItemSetter
// this does nothing with the relationship templates
func (o OrderItemTemplate) BuildManySetter(number int) []*models.OrderItemSetter {
	m := make([]*models.OrderItemSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.OrderItem
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use OrderItemTemplate.Create
func (o OrderItemTemplate) Build() *models.OrderItem {
	m := &models.OrderItem{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.OrderID != nil {
		m.OrderID = o.OrderID()
	}
	if o.BookID != nil {
		m.BookID = o.BookID()
	}
	if o.Title != nil {
		m.Title = o.Title()
	}
	if o.Price != nil {
		m.Price = o.Price()
	}
	if o.Quantity != nil {
		m.Quantity = o.Quantity()
	}
	if o.TotalPrice != nil {
		m.TotalPrice = o.TotalPrice()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.OrderItemSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use OrderItemTemplate.CreateMany
func (o OrderItemTemplate) BuildMany(number int) models.OrderItemSlice {
	m := make(models.OrderItemSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableOrderItem(m *models.OrderItemSetter) {
	if !(m.ID.IsValue()) {
		val := random_string(nil, "50")
		m.ID = omit.From(val)
	}
	if !(m.OrderID.IsValue()) {
		val := random_string(nil, "50")
		m.OrderID = omit.From(val)
	}
	if !(m.BookID.IsValue()) {
		val := random_string(nil, "50")
		m.BookID = omit.From(val)
	}
	if !(m.Title.IsValue()) {
		val := random_string(nil, "255")
		m.Title = omit.From(val)
	}
	if !(m.Price.IsValue()) {
		val := random_decimal_Decimal(nil, "10", "2")
		m.Price = omit.From(val)
	}
	if !(m.Quantity.IsValue()) {
		val := random_int32(nil)
		m.Quantity = omit.From(val)
	}
	if !(m.TotalPrice.IsValue()) {
		val := random_decimal_Decimal(nil, "10", "2")
		m.TotalPrice = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.OrderItem
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *OrderItemTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.OrderItem) error {
	var err error

	return err
}

// Create builds a orderItem and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *OrderItemTemplate) Create(ctx context.Context, exec bob.Executor) (*models.OrderItem, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableOrderItem(opt)

	if o.r.Book == nil {
		OrderItemMods.WithNewBook().Apply(ctx, o)
	}

	var rel0 *models.Book

	if o.r.Book.o.alreadyPersisted {
		rel0 = o.r.Book.o.Build()
	} else {
		rel0, err = o.r.Book.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.BookID = omit.From(rel0.ID)

	if o.r.Order == nil {
		OrderItemMods.WithNewOrder().Apply(ctx, o)
	}

	var rel1 *models.Order

	if o.r.Order.o.alreadyPersisted {
		rel1 = o.r.Order.o.Build()
	} else {
		rel1, err = o.r.Order.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.OrderID = omit.From(rel1.ID)

	m, err := models.OrderItems.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.Book = rel0
	m.R.Order = rel1

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a orderItem and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *OrderItemTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.OrderItem {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a orderItem and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *OrderItemTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.OrderItem {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple orderItems and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o OrderItemTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.OrderItemSlice, error) {
	var err error
	m := make(models.OrderItemSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple orderItems and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o OrderItemTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.OrderItemSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple orderItems and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o OrderItemTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.OrderItemSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// OrderItem has methods that act as mods for the OrderItemTemplate
var OrderItemMods orderItemMods

type orderItemMods struct{}

func (m orderItemMods) RandomizeAllColumns(f *faker.Faker) OrderItemMod {
	return OrderItemModSlice{
		OrderItemMods.RandomID(f),
		OrderItemMods.RandomOrderID(f),
		OrderItemMods.RandomBookID(f),
		OrderItemMods.RandomTitle(f),
		OrderItemMods.RandomPrice(f),
		OrderItemMods.RandomQuantity(f),
		OrderItemMods.RandomTotalPrice(f),
		OrderItemMods.RandomCreatedAt(f),
		OrderItemMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m orderItemMods) ID(val string) OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m orderItemMods) IDFunc(f func() string) OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m orderItemMods) UnsetID() OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderItemMods) RandomID(f *faker.Faker) OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.ID = func() string {
			return random_string(f, "50")
		}
	})
}

// Set the model columns to this value
func (m orderItemMods) OrderID(val string) OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.OrderID = func() string { return val }
	})
}

// Set the Column from the function
func (m orderItemMods) OrderIDFunc(f func() string) OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.OrderID = f
	})
}

// Clear any values for the column
func (m orderItemMods) UnsetOrderID() OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.OrderID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderItemMods) RandomOrderID(f *faker.Faker) OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.OrderID = func() string {
			return random_string(f, "50")
		}
	})
}

// Set the model columns to this value
func (m orderItemMods) BookID(val string) OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.BookID = func() string { return val }
	})
}

// Set the Column from the function
func (m orderItemMods) BookIDFunc(f func() string) OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.BookID = f
	})
}

// Clear any values for the column
func (m orderItemMods) UnsetBookID() OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.BookID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderItemMods) RandomBookID(f *faker.Faker) OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.BookID = func() string {
			return random_string(f, "50")
		}
	})
}

// Set the model columns to this value
func (m orderItemMods) Title(val string) OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.Title = func() string { return val }
	})
}

// Set the Column from the function
func (m orderItemMods) TitleFunc(f func() string) OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.Title = f
	})
}

// Clear any values for the column
func (m orderItemMods) UnsetTitle() OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.Title = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderItemMods) RandomTitle(f *faker.Faker) OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.Title = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m orderItemMods) Price(val decimal.Decimal) OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.Price = func() decimal.Decimal { return val }
	})
}

// Set the Column from the function
func (m orderItemMods) PriceFunc(f func() decimal.Decimal) OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.Price = f
	})
}

// Clear any values for the column
func (m orderItemMods) UnsetPrice() OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.Price = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderItemMods) RandomPrice(f *faker.Faker) OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.Price = func() decimal.Decimal {
			return random_decimal_Decimal(f, "10", "2")
		}
	})
}

// Set the model columns to this value
func (m orderItemMods) Quantity(val int32) OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.Quantity = func() int32 { return val }
	})
}

// Set the Column from the function
func (m orderItemMods) QuantityFunc(f func() int32) OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.Quantity = f
	})
}

// Clear any values for the column
func (m orderItemMods) UnsetQuantity() OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.Quantity = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderItemMods) RandomQuantity(f *faker.Faker) OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.Quantity = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m orderItemMods) TotalPrice(val decimal.Decimal) OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.TotalPrice = func() decimal.Decimal { return val }
	})
}

// Set the Column from the function
func (m orderItemMods) TotalPriceFunc(f func() decimal.Decimal) OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.TotalPrice = f
	})
}

// Clear any values for the column
func (m orderItemMods) UnsetTotalPrice() OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.TotalPrice = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderItemMods) RandomTotalPrice(f *faker.Faker) OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.TotalPrice = func() decimal.Decimal {
			return random_decimal_Decimal(f, "10", "2")
		}
	})
}

// Set the model columns to this value
func (m orderItemMods) CreatedAt(val time.Time) OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m orderItemMods) CreatedAtFunc(f func() time.Time) OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m orderItemMods) UnsetCreatedAt() OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderItemMods) RandomCreatedAt(f *faker.Faker) OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m orderItemMods) UpdatedAt(val time.Time) OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m orderItemMods) UpdatedAtFunc(f func() time.Time) OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m orderItemMods) UnsetUpdatedAt() OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderItemMods) RandomUpdatedAt(f *faker.Faker) OrderItemMod {
	return OrderItemModFunc(func(_ context.Context, o *OrderItemTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m orderItemMods) WithParentsCascading() OrderItemMod {
	return OrderItemModFunc(func(ctx context.Context, o *OrderItemTemplate) {
		if isDone, _ := orderItemWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = orderItemWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewBookWithContext(ctx, BookMods.WithParentsCascading())
			m.WithBook(related).Apply(ctx, o)
		}
		{

			related := o.f.NewOrderWithContext(ctx, OrderMods.WithParentsCascading())
			m.WithOrder(related).Apply(ctx, o)
		}
	})
}

func (m orderItemMods) WithBook(rel *BookTemplate) OrderItemMod {
	return OrderItemModFunc(func(ctx context.Context, o *OrderItemTemplate) {
		o.r.Book = &orderItemRBookR{
			o: rel,
		}
	})
}

func (m orderItemMods) WithNewBook(mods ...BookMod) OrderItemMod {
	return OrderItemModFunc(func(ctx context.Context, o *OrderItemTemplate) {
		related := o.f.NewBookWithContext(ctx, mods...)

		m.WithBook(related).Apply(ctx, o)
	})
}

func (m orderItemMods) WithExistingBook(em *models.Book) OrderItemMod {
	return OrderItemModFunc(func(ctx context.Context, o *OrderItemTemplate) {
		o.r.Book = &orderItemRBookR{
			o: o.f.FromExistingBook(em),
		}
	})
}

func (m orderItemMods) WithoutBook() OrderItemMod {
	return OrderItemModFunc(func(ctx context.Context, o *OrderItemTemplate) {
		o.r.Book = nil
	})
}

func (m orderItemMods) WithOrder(rel *OrderTemplate) OrderItemMod {
	return OrderItemModFunc(func(ctx context.Context, o *OrderItemTemplate) {
		o.r.Order = &orderItemROrderR{
			o: rel,
		}
	})
}

func (m orderItemMods) WithNewOrder(mods ...OrderMod) OrderItemMod {
	return OrderItemModFunc(func(ctx context.Context, o *OrderItemTemplate) {
		related := o.f.NewOrderWithContext(ctx, mods...)

		m.WithOrder(related).Apply(ctx, o)
	})
}

func (m orderItemMods) WithExistingOrder(em *models.Order) OrderItemMod {
	return OrderItemModFunc(func(ctx context.Context, o *OrderItemTemplate) {
		o.r.Order = &orderItemROrderR{
			o: o.f.FromExistingOrder(em),
		}
	})
}

func (m orderItemMods) WithoutOrder() OrderItemMod {
	return OrderItemModFunc(func(ctx context.Context, o *OrderItemTemplate) {
		o.r.Order = nil
	})
}
