// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var AddressErrors = &addressErrors{
	ErrUniqueAddressesPkey: &UniqueConstraintError{
		schema:  "",
		table:   "addresses",
		columns: []string{"id"},
		s:       "addresses_pkey",
	},
}

type addressErrors struct {
	ErrUniqueAddressesPkey *UniqueConstraintError
}
