// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var BookErrors = &bookErrors{
	ErrUniqueBooksPkey: &UniqueConstraintError{
		schema:  "",
		table:   "books",
		columns: []string{"id"},
		s:       "books_pkey",
	},

	ErrUniqueBooksIsbnKey: &UniqueConstraintError{
		schema:  "",
		table:   "books",
		columns: []string{"isbn"},
		s:       "books_isbn_key",
	},
}

type bookErrors struct {
	ErrUniqueBooksPkey *UniqueConstraintError

	ErrUniqueBooksIsbnKey *UniqueConstraintError
}
