// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var CartItemErrors = &cartItemErrors{
	ErrUniqueCartItemsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "cart_items",
		columns: []string{"id"},
		s:       "cart_items_pkey",
	},
}

type cartItemErrors struct {
	ErrUniqueCartItemsPkey *UniqueConstraintError
}
