// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var CartErrors = &cartErrors{
	ErrUniqueCartsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "carts",
		columns: []string{"id"},
		s:       "carts_pkey",
	},
}

type cartErrors struct {
	ErrUniqueCartsPkey *UniqueConstraintError
}
