// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var OrderItemErrors = &orderItemErrors{
	ErrUniqueOrderItemsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "order_items",
		columns: []string{"id"},
		s:       "order_items_pkey",
	},
}

type orderItemErrors struct {
	ErrUniqueOrderItemsPkey *UniqueConstraintError
}
