// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Addresses = Table[
	addressColumns,
	addressIndexes,
	addressForeignKeys,
	addressUniques,
	addressChecks,
]{
	Schema: "",
	Name:   "addresses",
	Columns: addressColumns{
		ID: column{
			Name:      "id",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UserID: column{
			Name:      "user_id",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		AddressesType: column{
			Name:      "addresses_type",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Line1: column{
			Name:      "line1",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Line2: column{
			Name:      "line2",
			DBType:    "character varying",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Landmark: column{
			Name:      "landmark",
			DBType:    "character varying",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		City: column{
			Name:      "city",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Pincode: column{
			Name:      "pincode",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		District: column{
			Name:      "district",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		State: column{
			Name:      "state",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Country: column{
			Name:      "country",
			DBType:    "character varying",
			Default:   "'india'::character varying",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		IsDefault: column{
			Name:      "is_default",
			DBType:    "boolean",
			Default:   "false",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp without time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp without time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: addressIndexes{
		AddressesPkey: index{
			Type: "btree",
			Name: "addresses_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "addresses_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: addressForeignKeys{
		AddressesAddressesUserIDFkey: foreignKey{
			constraint: constraint{
				Name:    "addresses.addresses_user_id_fkey",
				Columns: []string{"user_id"},
				Comment: "",
			},
			ForeignTable:   "users",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type addressColumns struct {
	ID            column
	UserID        column
	AddressesType column
	Line1         column
	Line2         column
	Landmark      column
	City          column
	Pincode       column
	District      column
	State         column
	Country       column
	IsDefault     column
	CreatedAt     column
	UpdatedAt     column
}

func (c addressColumns) AsSlice() []column {
	return []column{
		c.ID, c.UserID, c.AddressesType, c.Line1, c.Line2, c.Landmark, c.City, c.Pincode, c.District, c.State, c.Country, c.IsDefault, c.CreatedAt, c.UpdatedAt,
	}
}

type addressIndexes struct {
	AddressesPkey index
}

func (i addressIndexes) AsSlice() []index {
	return []index{
		i.AddressesPkey,
	}
}

type addressForeignKeys struct {
	AddressesAddressesUserIDFkey foreignKey
}

func (f addressForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.AddressesAddressesUserIDFkey,
	}
}

type addressUniques struct{}

func (u addressUniques) AsSlice() []constraint {
	return []constraint{}
}

type addressChecks struct{}

func (c addressChecks) AsSlice() []check {
	return []check{}
}
