// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Books = Table[
	bookColumns,
	bookIndexes,
	bookForeignKeys,
	bookUniques,
	bookChecks,
]{
	Schema: "",
	Name:   "books",
	Columns: bookColumns{
		ID: column{
			Name:      "id",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Isbn: column{
			Name:      "isbn",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Title: column{
			Name:      "title",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Author: column{
			Name:      "author",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Description: column{
			Name:      "description",
			DBType:    "text",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Price: column{
			Name:      "price",
			DBType:    "numeric",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Stock: column{
			Name:      "stock",
			DBType:    "integer",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Reserved: column{
			Name:      "reserved",
			DBType:    "integer",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		IsActive: column{
			Name:      "is_active",
			DBType:    "boolean",
			Default:   "true",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp without time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp without time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: bookIndexes{
		BooksPkey: index{
			Type: "btree",
			Name: "books_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		BooksIsbnKey: index{
			Type: "btree",
			Name: "books_isbn_key",
			Columns: []indexColumn{
				{
					Name:         "isbn",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "books_pkey",
		Columns: []string{"id"},
		Comment: "",
	},

	Uniques: bookUniques{
		BooksIsbnKey: constraint{
			Name:    "books_isbn_key",
			Columns: []string{"isbn"},
			Comment: "",
		},
	},
	Checks: bookChecks{
		BooksPriceCheck: check{
			constraint: constraint{
				Name:    "books_price_check",
				Columns: []string{"price"},
				Comment: "",
			},
			Expression: "(price > (0)::numeric)",
		},
		BooksReservedCheck: check{
			constraint: constraint{
				Name:    "books_reserved_check",
				Columns: []string{"reserved"},
				Comment: "",
			},
			Expression: "(reserved >= 0)",
		},
		BooksStockCheck: check{
			constraint: constraint{
				Name:    "books_stock_check",
				Columns: []string{"stock"},
				Comment: "",
			},
			Expression: "(stock >= 0)",
		},
		StockReservedCheck: check{
			constraint: constraint{
				Name:    "stock_reserved_check",
				Columns: []string{"reserved", "stock"},
				Comment: "",
			},
			Expression: "(reserved <= stock)",
		},
	},
	Comment: "",
}

type bookColumns struct {
	ID          column
	Isbn        column
	Title       column
	Author      column
	Description column
	Price       column
	Stock       column
	Reserved    column
	IsActive    column
	CreatedAt   column
	UpdatedAt   column
}

func (c bookColumns) AsSlice() []column {
	return []column{
		c.ID, c.Isbn, c.Title, c.Author, c.Description, c.Price, c.Stock, c.Reserved, c.IsActive, c.CreatedAt, c.UpdatedAt,
	}
}

type bookIndexes struct {
	BooksPkey    index
	BooksIsbnKey index
}

func (i bookIndexes) AsSlice() []index {
	return []index{
		i.BooksPkey, i.BooksIsbnKey,
	}
}

type bookForeignKeys struct{}

func (f bookForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type bookUniques struct {
	BooksIsbnKey constraint
}

func (u bookUniques) AsSlice() []constraint {
	return []constraint{
		u.BooksIsbnKey,
	}
}

type bookChecks struct {
	BooksPriceCheck    check
	BooksReservedCheck check
	BooksStockCheck    check
	StockReservedCheck check
}

func (c bookChecks) AsSlice() []check {
	return []check{
		c.BooksPriceCheck, c.BooksReservedCheck, c.BooksStockCheck, c.StockReservedCheck,
	}
}
