// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Carts = Table[
	cartColumns,
	cartIndexes,
	cartForeignKeys,
	cartUniques,
	cartChecks,
]{
	Schema: "",
	Name:   "carts",
	Columns: cartColumns{
		ID: column{
			Name:      "id",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UserID: column{
			Name:      "user_id",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Status: column{
			Name:      "status",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp without time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp without time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: cartIndexes{
		CartsPkey: index{
			Type: "btree",
			Name: "carts_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "carts_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: cartForeignKeys{
		CartsCartsUserIDFkey: foreignKey{
			constraint: constraint{
				Name:    "carts.carts_user_id_fkey",
				Columns: []string{"user_id"},
				Comment: "",
			},
			ForeignTable:   "users",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type cartColumns struct {
	ID        column
	UserID    column
	Status    column
	CreatedAt column
	UpdatedAt column
}

func (c cartColumns) AsSlice() []column {
	return []column{
		c.ID, c.UserID, c.Status, c.CreatedAt, c.UpdatedAt,
	}
}

type cartIndexes struct {
	CartsPkey index
}

func (i cartIndexes) AsSlice() []index {
	return []index{
		i.CartsPkey,
	}
}

type cartForeignKeys struct {
	CartsCartsUserIDFkey foreignKey
}

func (f cartForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.CartsCartsUserIDFkey,
	}
}

type cartUniques struct{}

func (u cartUniques) AsSlice() []constraint {
	return []constraint{}
}

type cartChecks struct{}

func (c cartChecks) AsSlice() []check {
	return []check{}
}
