// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var CartItems = Table[
	cartItemColumns,
	cartItemIndexes,
	cartItemForeignKeys,
	cartItemUniques,
	cartItemChecks,
]{
	Schema: "",
	Name:   "cart_items",
	Columns: cartItemColumns{
		ID: column{
			Name:      "id",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CartID: column{
			Name:      "cart_id",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		BookID: column{
			Name:      "book_id",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Quantity: column{
			Name:      "quantity",
			DBType:    "integer",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Price: column{
			Name:      "price",
			DBType:    "numeric",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp without time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp without time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: cartItemIndexes{
		CartItemsPkey: index{
			Type: "btree",
			Name: "cart_items_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "cart_items_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: cartItemForeignKeys{
		CartItemsCartItemsBookIDFkey: foreignKey{
			constraint: constraint{
				Name:    "cart_items.cart_items_book_id_fkey",
				Columns: []string{"book_id"},
				Comment: "",
			},
			ForeignTable:   "books",
			ForeignColumns: []string{"id"},
		},
		CartItemsCartItemsCartIDFkey: foreignKey{
			constraint: constraint{
				Name:    "cart_items.cart_items_cart_id_fkey",
				Columns: []string{"cart_id"},
				Comment: "",
			},
			ForeignTable:   "carts",
			ForeignColumns: []string{"id"},
		},
	},

	Checks: cartItemChecks{
		CartItemsPriceCheck: check{
			constraint: constraint{
				Name:    "cart_items_price_check",
				Columns: []string{"price"},
				Comment: "",
			},
			Expression: "(price > (0)::numeric)",
		},
		CartItemsQuantityCheck: check{
			constraint: constraint{
				Name:    "cart_items_quantity_check",
				Columns: []string{"quantity"},
				Comment: "",
			},
			Expression: "(quantity >= 0)",
		},
	},
	Comment: "",
}

type cartItemColumns struct {
	ID        column
	CartID    column
	BookID    column
	Quantity  column
	Price     column
	CreatedAt column
	UpdatedAt column
}

func (c cartItemColumns) AsSlice() []column {
	return []column{
		c.ID, c.CartID, c.BookID, c.Quantity, c.Price, c.CreatedAt, c.UpdatedAt,
	}
}

type cartItemIndexes struct {
	CartItemsPkey index
}

func (i cartItemIndexes) AsSlice() []index {
	return []index{
		i.CartItemsPkey,
	}
}

type cartItemForeignKeys struct {
	CartItemsCartItemsBookIDFkey foreignKey
	CartItemsCartItemsCartIDFkey foreignKey
}

func (f cartItemForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.CartItemsCartItemsBookIDFkey, f.CartItemsCartItemsCartIDFkey,
	}
}

type cartItemUniques struct{}

func (u cartItemUniques) AsSlice() []constraint {
	return []constraint{}
}

type cartItemChecks struct {
	CartItemsPriceCheck    check
	CartItemsQuantityCheck check
}

func (c cartItemChecks) AsSlice() []check {
	return []check{
		c.CartItemsPriceCheck, c.CartItemsQuantityCheck,
	}
}
