// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Orders = Table[
	orderColumns,
	orderIndexes,
	orderForeignKeys,
	orderUniques,
	orderChecks,
]{
	Schema: "",
	Name:   "orders",
	Columns: orderColumns{
		ID: column{
			Name:      "id",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UserID: column{
			Name:      "user_id",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CartID: column{
			Name:      "cart_id",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Amount: column{
			Name:      "amount",
			DBType:    "numeric",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		DelieveryAddress: column{
			Name:      "delievery_address",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp without time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp without time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: orderIndexes{
		OrdersPkey: index{
			Type: "btree",
			Name: "orders_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "orders_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: orderForeignKeys{
		OrdersOrdersCartIDFkey: foreignKey{
			constraint: constraint{
				Name:    "orders.orders_cart_id_fkey",
				Columns: []string{"cart_id"},
				Comment: "",
			},
			ForeignTable:   "carts",
			ForeignColumns: []string{"id"},
		},
		OrdersOrdersUserIDFkey: foreignKey{
			constraint: constraint{
				Name:    "orders.orders_user_id_fkey",
				Columns: []string{"user_id"},
				Comment: "",
			},
			ForeignTable:   "users",
			ForeignColumns: []string{"id"},
		},
	},

	Checks: orderChecks{
		OrdersAmountCheck: check{
			constraint: constraint{
				Name:    "orders_amount_check",
				Columns: []string{"amount"},
				Comment: "",
			},
			Expression: "(amount > (0)::numeric)",
		},
	},
	Comment: "",
}

type orderColumns struct {
	ID               column
	UserID           column
	CartID           column
	Amount           column
	DelieveryAddress column
	CreatedAt        column
	UpdatedAt        column
}

func (c orderColumns) AsSlice() []column {
	return []column{
		c.ID, c.UserID, c.CartID, c.Amount, c.DelieveryAddress, c.CreatedAt, c.UpdatedAt,
	}
}

type orderIndexes struct {
	OrdersPkey index
}

func (i orderIndexes) AsSlice() []index {
	return []index{
		i.OrdersPkey,
	}
}

type orderForeignKeys struct {
	OrdersOrdersCartIDFkey foreignKey
	OrdersOrdersUserIDFkey foreignKey
}

func (f orderForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.OrdersOrdersCartIDFkey, f.OrdersOrdersUserIDFkey,
	}
}

type orderUniques struct{}

func (u orderUniques) AsSlice() []constraint {
	return []constraint{}
}

type orderChecks struct {
	OrdersAmountCheck check
}

func (c orderChecks) AsSlice() []check {
	return []check{
		c.OrdersAmountCheck,
	}
}
