// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var OrderItems = Table[
	orderItemColumns,
	orderItemIndexes,
	orderItemForeignKeys,
	orderItemUniques,
	orderItemChecks,
]{
	Schema: "",
	Name:   "order_items",
	Columns: orderItemColumns{
		ID: column{
			Name:      "id",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		OrderID: column{
			Name:      "order_id",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		BookID: column{
			Name:      "book_id",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Title: column{
			Name:      "title",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Price: column{
			Name:      "price",
			DBType:    "numeric",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Quantity: column{
			Name:      "quantity",
			DBType:    "integer",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		TotalPrice: column{
			Name:      "total_price",
			DBType:    "numeric",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp without time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp without time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: orderItemIndexes{
		OrderItemsPkey: index{
			Type: "btree",
			Name: "order_items_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "order_items_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: orderItemForeignKeys{
		OrderItemsOrderItemsBookIDFkey: foreignKey{
			constraint: constraint{
				Name:    "order_items.order_items_book_id_fkey",
				Columns: []string{"book_id"},
				Comment: "",
			},
			ForeignTable:   "books",
			ForeignColumns: []string{"id"},
		},
		OrderItemsOrderItemsOrderIDFkey: foreignKey{
			constraint: constraint{
				Name:    "order_items.order_items_order_id_fkey",
				Columns: []string{"order_id"},
				Comment: "",
			},
			ForeignTable:   "orders",
			ForeignColumns: []string{"id"},
		},
	},

	Checks: orderItemChecks{
		OrderItemsPriceCheck: check{
			constraint: constraint{
				Name:    "order_items_price_check",
				Columns: []string{"price"},
				Comment: "",
			},
			Expression: "(price >= (0)::numeric)",
		},
		OrderItemsQuantityCheck: check{
			constraint: constraint{
				Name:    "order_items_quantity_check",
				Columns: []string{"quantity"},
				Comment: "",
			},
			Expression: "(quantity > 0)",
		},
		OrderItemsTotalPriceCheck: check{
			constraint: constraint{
				Name:    "order_items_total_price_check",
				Columns: []string{"total_price"},
				Comment: "",
			},
			Expression: "(total_price > (0)::numeric)",
		},
	},
	Comment: "",
}

type orderItemColumns struct {
	ID         column
	OrderID    column
	BookID     column
	Title      column
	Price      column
	Quantity   column
	TotalPrice column
	CreatedAt  column
	UpdatedAt  column
}

func (c orderItemColumns) AsSlice() []column {
	return []column{
		c.ID, c.OrderID, c.BookID, c.Title, c.Price, c.Quantity, c.TotalPrice, c.CreatedAt, c.UpdatedAt,
	}
}

type orderItemIndexes struct {
	OrderItemsPkey index
}

func (i orderItemIndexes) AsSlice() []index {
	return []index{
		i.OrderItemsPkey,
	}
}

type orderItemForeignKeys struct {
	OrderItemsOrderItemsBookIDFkey  foreignKey
	OrderItemsOrderItemsOrderIDFkey foreignKey
}

func (f orderItemForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.OrderItemsOrderItemsBookIDFkey, f.OrderItemsOrderItemsOrderIDFkey,
	}
}

type orderItemUniques struct{}

func (u orderItemUniques) AsSlice() []constraint {
	return []constraint{}
}

type orderItemChecks struct {
	OrderItemsPriceCheck      check
	OrderItemsQuantityCheck   check
	OrderItemsTotalPriceCheck check
}

func (c orderItemChecks) AsSlice() []check {
	return []check{
		c.OrderItemsPriceCheck, c.OrderItemsQuantityCheck, c.OrderItemsTotalPriceCheck,
	}
}
